### ISSUE TITLE
[Feature Request] Validation on Input Parameters

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#1000]
**Is your feature request related to a problem? Please describe.**
The Input Parameters in workspace configurations currently don't support much validation. For example:
- entering an invalid instance type is accepted, and you don't find out until someone goes to launch it
- copying an AMI ID from the AWS console brings in extra whitespace at the end; this is not automatically stripped and instead workspace launches fail (as seen in the image below)

<img width="317" alt="image" src="https://user-images.githubusercontent.com/900469/171785732-bf56c550-16f1-4333-925a-f9be9c797d0c.png">

**Describe the solution you'd like**
Validation on these fields where possible. For example:
- strip leading or trailing whitespace
- validate instance types (or, to avoid having to keep it up-to-date with new launches, perhaps just validate the structure)
- validate structure of ARNs, CIDRs, and IDs where possible

**Describe alternatives you've considered**
The only other alternative I can think of is the configuring admin double-checking each value they're entering, and then starting up a workspace of their own afterwards to make sure they didn't make a mistake. This is all a good idea to do anyway, but validation would be an extra help here :)

**Comment by maghirardelli** [comment]
Hi @tdmalone, Thank you for bringing this to our attention. I have added this item to our backlog. For now, we recommend the configuring admin to double-check the values as you mentioned.
