### ISSUE TITLE
[Feature Request] Enable Sagemaker Studio product from service catalog and import the studio UI through the workbench 

### ISSUE THREAD

**Issue by aswin2025** [awslabs/service-workbench-on-aws#1002]
**Is your feature request related to a problem? Please describe.**
No, its a part of an enhancement

**Describe the solution you'd like**
We have tried multiple templates that launch the sagemaker studio and are configured with the workbench. Its giving an error as it is not compatible with the workbench. Is there any workaround for the same?.

**Comment by kcadette** [comment]
Hello @aswin2025,  thank you for raising this. There is not a workaround at this time. I've added your request to my team's backlog.
