### ISSUE TITLE
[Bug] External ID is not url encoded before being sent to CFN

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#1003]
**Describe the bug**
When onboarding a new AWS account, if you enter a random external ID with:
- a `%` in it, the CloudFormation console loads a WSOD (with an error in the dev console noting an invalid URL)
- a `#` in it, any parameter values following the ExternalId are missing
- a `&` in it will probably also cause issues but I didn't happen to have this in mine

This is due to the user-supplied value for ExternalId being passed verbatim to the CloudFormation console URL, without being encoded to make it URL-safe.

**To Reproduce**
1. In the Service Workbench UI, go to the Accounts page and the AWS Accounts tab
2. Click on Add AWS Account
3. Fill out the fields, and enter a random external ID containing some special characters - in this case, at least `%` or `#`
4. Click Onboard AWS Account, and either use the 'I have admin access' option and click the 'Create Stack' button, or the 'I do not have admin access' option and copy and visit the URL

**Expected behavior**
The CloudFormation console to load without errors and with all necessary parameters entered.

**Screenshots**

![image](https://user-images.githubusercontent.com/900469/173984799-9720751c-7a43-491d-aadc-d2c86481005a.png)

![image](https://user-images.githubusercontent.com/900469/173985092-3faf98c3-391e-417f-a50d-f75ed583507b.png)
![image](https://user-images.githubusercontent.com/900469/173985136-b41009bf-b261-4359-94bb-145c0276c79f.png)

**Versions (please complete the following information):**
- v5.0.0

**Additional context**
n/a

**Comment by kpark277** [comment]
Hi @tdmalone, thank you for bringing this to our attention; I am able to reproduce the bug; % creates an invalid character for the externalId, while both # and & cause anything after and including these characters to be excluded from the externalId. I have added this item to our backlog. For now, please avoid these three characters when setting your externalId.

**Comment by tdmalone** [comment]
Adding response so this doesn't get closed
