### ISSUE TITLE
[Bug] Cannot mount cross region open data

### ISSUE THREAD

**Issue by dengmingtong** [awslabs/service-workbench-on-aws#1004]
**Describe the bug**
Suppose my swb is in us-east-1 region, I create a linux workspace and try to mount https://registry.opendata.aws/hecatomb/ open data which is hosted on S3 us-west-2 region.

The workspace can be created successfully, but the hecatomb data cannot be mounted to the EC2 instance.

I think it should be a common bug when swb try to mount cross region data.
I did some debug as below:
Below is S3Mount parameter in cloudformation
[{"id":"hecatomb","readable":true,"writeable":false,"bucket":"hecatombdatabases","prefix":"/"}]

in the main/solution/post-deployment/config/environment-files/bin/mount_s3.sh file, there is code as below:
        if [ "$s3_role_arn" == "null" ]
        then
            printf 'Mounting internal study "%s" at "%s"\n' "$study_id" "$study_dir"
            goofys --region $region --acl "bucket-owner-full-control" "${s3_bucket}:${s3_prefix}" "$study_dir"

The region is the workspace region, not s3 bucket region. 
I think this cause the error of mounting data.

Could you try to fix this bug?

Thanks
Mingtong

**Comment by ssvegaraju** [comment]
Hi @dengmingtong, thanks for bringing up this issue! I've added this to our team's backlog.

**Comment by SanketD92** [comment]
Hi @dengmingtong, have you enabled TRE (AppStream) in your SWB deployment? Cross-region study mounting is not supported in TRE environments.

**Comment by dengmingtong** [comment]
No, I did not enable TRE feature. You can repeat this issue when you mount another regions data.

**Comment by dengmingtong** [comment]
any update?

**Comment by tdmalone** [comment]
This still appears to be a problem in the latest version of SWB; it has already spawned two possible duplicate issues too, in #1013 and #1045.

Appears to be quite an oversight that mounting of open data is only supported in the same region...

**Comment by BoPeng** [comment]
I have also encountered this bug. There are 119 open data on SWB but none of them appears to be available to `us-east-2`.  Please

1. If this is a limitation of SWB, can we list the region of the datasets so that we know what datasets are available? 
2. @SanketD92 mentioned TRE (AppStream) could solve this issue. Could you elaborate how AppStream helps and how to enable AppStream?

Edit: The following is the configuration flag about AppStream, which says enable AppStream is a one-way process and we should proceed with caution. It would be helpful if someone can point me to the section in the documentation that talks about AppStream.

```python
# Determine whether workspace should be accessible only through AppStream
# NOTE: Once the isAppStremEnabled is set to true, the AppStrem feature will be enabled and can NOT be toggled off.
# If you toggle the AppStream feature from true to false and redeploy the whole solution, the backend stack deployment should error out with following message:
# Error validating existing stack policy: Unknown logical id 'LogicalResourceId/AppStream*' in statement {} - stack policies can only be applied to logical ids referenced in the template
# Stack policies are applied here: addons/addon-stack-policy/packages/stack-policy/lib/steps/update-cfn-stack-policy.js
#isAppStreamEnabled: false
```

**Comment by tdmalone** [comment]
@BoPeng You can work around this by adding a script to your AMIs to mount the open data buckets either without specifying the region, or alternatively by looking up and specifying the correct region. (I think it should work just without specifying the region - the problem is that the script that ships with SWB hardcodes `--region us-east-1`).

You can create a script based off the existing `mount_s3.sh` that's added by the SWB bootstrap script.

**Comment by BoPeng** [comment]
@tdmalone Why do we even have option `--region` for command `goofys` in `mount_s3.sh` if the region can be auto detected?

https://github.com/awslabs/service-workbench-on-aws/blob/1d2fe14e04218070aa7034a9868002643da88bc6/main/solution/post-deployment/config/environment-files/bin/mount_s3.sh#L80

I just tried this command with a dataset in `us-east-1`, the first two commands work, and the third does not, so it is better not to specify `--region` at all.

```
goofys gdc-target-phs000218-2-open /mnt/fah
goofys --region us-east-1 gdc-target-phs000218-2-open /mnt/fah
goofys --region us-east-2 gdc-target-phs000218-2-open /mnt/fah
```

**Comment by tdmalone** [comment]
@BoPeng I'm not sure! There may be a reason, but I haven't done enough testing with it. First thing I'd want to check with your first command is whether it still works for non `us-east-1` buckets. If it does, you're probably right.

**Comment by BoPeng** [comment]
Yes, I actually tried to mount another dataset on `us-east-2` and it worked.

```
# goofys fah-public-data-covid19-cryptic-pockets /mnt/fah
# goofys --region us-east-1 fah-public-data-covid19-cryptic-pockets /mnt/fah
2023/04/18 22:48:10.938951 main.FATAL Unable to mount file system, see syslog for details
# goofys --region us-east-2 fah-public-data-covid19-cryptic-pockets /mnt/fah
# goofys gdc-target-phs000218-2-open /mnt/fah
# goofys --region us-east-1 gdc-target-phs000218-2-open /mnt/fah
# goofys --region us-east-2 gdc-target-phs000218-2-open /mnt/fah
2023/04/18 22:49:02.777306 main.FATAL Unable to mount file system, see syslog for details
# echo $?
```

In any case, it does not hurt to do something like the following to try both options

```sh
                goofys --profile $study_id --acl "bucket-owner-full-control" \
                "${s3_bucket}:${s3_prefix}" "$study_dir" || \
                goofys --region $bucket_region --profile $study_id --acl "bucket-owner-full-control" \
                "${s3_bucket}:${s3_prefix}" "$study_dir"
```


ref: 
* https://registry.opendata.aws/target/ is on `us-east-1`
* https://registry.opendata.aws/foldingathome-covid19/ on `us-east-2`

**Comment by BoPeng** [comment]
I created a PR to demonstrate the idea, although I do not have a test environment to test the patch.
