### ISSUE TITLE
[Feature Request] Support for deployments using a private API Gateway

### ISSUE THREAD

**Issue by fsrodriguezm** [awslabs/service-workbench-on-aws#1005]
**Is your feature request related to a problem? Please describe.**
We are deploying this solution in a Gov Cloud account and we are required to use a private API gateway.

**Describe the solution you'd like**
It would be nice to pass in an argument when running the environment deployment script so that the solution is configured to use a private API gateway.

**Describe alternatives you've considered**
This change will require changing the way the code makes API calls.

**Comment by SanketD92** [comment]
Thank you for creating this feature request. I'll create a ticket in our team's backlog.
