### ISSUE TITLE
[Feature Request] Support ECS (likely via Fargate) as a launchable product

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#1007]
**Is your feature request related to a problem? Please describe.**
The Service Workbench UI makes compute easy to access for researchers who aren't familiar with, or comfortable with using, the AWS console. This works great for EC2 instances, but in some cases we also have researchers who wish to run a container. 

**Describe the solution you'd like**
ECS Fargate available as a workspace type in Service Workbench.

**Describe alternatives you've considered**
- **Launching an EC2 AMI with Docker installed and configured.** This would work, but is cumbersome and involves eg. a non-Linux-literate person needing to understand how to use the Docker CLI.
- **Providing an eg. EKS cluster outside of Service Workbench.** This would allow containers to be launched without researchers having to care about the compute available to serve it, but it would still require some technical ability eg. to put together YAML manifests.
- **Providing our own Service Catalog product and importing it in to Service Workbench.** I'm not sure how Service Workbench would deal with this (or if it would even pick it up and allow it to be imported), but if it is possible to use this as a way of writing a 'plugin' (for lack of a better term) for SWB, this might be feasible.

**Comment by SanketD92** [comment]
Thank you for creating this feature request. I'll create a ticket in our team's backlog.

Could you provide a sample use-case for this environment type, with an emphasis on parameterization needed. This would help us set up environment type config values when we work on provisioning such a workspace.

**Comment by tdmalone** [comment]
Thanks @SanketD92!

In terms of a use case, we've had a bit of a think and realised the ways people use containers could end up being fairly broad. So I've had a stab at something that might be able to work in a range of situations:
- when a hosting account is onboarded, Service Workbench creates an ECS Cluster along with the VPC (in the 'initial-stack-xxxxxxxxx' stack)
- the Service Catalog portfolio provides an 'ECS Fargate' workspace type
- workspace type configurations provide parameterisation of task size (CPU & memory), architecture, and ephemeral storage
- when users request a workspace, they'd need the ability to specify the container image URI (presumably this could either be supplied as a public URI eg. on Docker Hub, or as a private ECR URI as long as the relevant roles had been given pull access), as well as custom environment variables
  - the parameterisation here makes this workspace type slightly different to the others, in that none of the others have additional parameters for the user...  I'm not sure how additionally complex that makes this proposal
- studies can still be 'mounted' to a workspace/container, but if that's difficult to do via S3 into Fargate it might mean that study data needs to be stored on EFS instead??

Combining the params in the workspace type configuration with those specified by the user, would then allow an ECS task definition to be created in the hosting account, and then run as a standalone task - this would represent a Service Workbench 'workspace'. Once the container runs to completion it would need to save its output into the egress store, and the egress store would need to be remain available to the user somehow in order to obtain that output.

(Prior to all this of course, the user will have iterated locally on their Docker image until they were happy with it, and pushed it up to a registry. They'd use the env vars and/or mounted study to actually provide the data or inputs that would be crunched by the task).

I'm not entirely sure how the egress store part of this would work - perhaps Service Workbench considers the 'instance' 'stopped' once the task finishes, and then when the user is finished they can 'terminate' the instance, which would delete the task definition & clean up the egress store, etc.? They'd just need a way to access the egress store without a live instance...
