### ISSUE TITLE
Not able to deploy dev.yml file for next steps in installation

### ISSUE THREAD

**Issue by shres3007** [awslabs/service-workbench-on-aws#1011]
Below is the image, not able able to achieve this step of my installation of Service Workbench on AWS.
<img width="523" alt="image" src="https://user-images.githubusercontent.com/71344127/177359378-68259faa-06b2-4a0a-996b-352748589ebb.png">

Serverless Error ---------------------------------------
 
  Stack with id dev-va-sw-preDeployment does not exist
 
Above error is coming while deploying dev.yml file. I'm performing all the steps of installation using cloud9 on lab learner using aws academy lab.
please help ASAP!

**Comment by Bingjiling** [comment]
Hi @shres3007,

Thanks for reaching out! Could you please share a link to the tutorial you're following and at which step you ran into this issue? Also could you please share what's in your dev.yml file?

Thanks,
Yanyu

**Comment by shres3007** [comment]
> hi @Bingjiling
 thanks for reply.
this is what i am using, https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/Service_Workbench_Install_Guide.pdf, stuck at pg 5 of this guide.
as i am using AWS Console through a learner lab from AWS academy. 
while deploying my dev.yml, stacks are creating but deleting as i do not have authorized access for creating a role as i am not a root user or any other user.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/71344127/177946929-bf6388fb-4c51-4695-98ea-c6b85b97e85d.png)

find the attachment of dev.yml
[dev (1).zip](https://github.com/awslabs/service-workbench-on-aws/files/9070205/dev.1.zip)

please guide me how can i resolve this problem, let me know ASAP!

thanks
Shreshta

**Comment by ebrahim989** [comment]
I am receiving the same error: dev-va-sw-preDeployment. Could you help @shres3007 @Bingjiling @gazzyt @shres3007

**Comment by ebrahim989** [comment]
@shres3007 Did you come right with this issue ? I am having a similar issue. Could you share your resolution on this case please.

**Comment by SanketD92** [comment]
Hello @shres3007, @ebrahim989,

The AWS credentials performing the installation is suggested to have admin permissions over the main account so as to make deployment go smoothly. This would allow creating the various AWS resources listed out in the solution's CloudFormation templates; whereas insufficient permissions will make the CloudFormation stack to rollback and delete.

Regards,
Sanket

**Comment by ebrahim989** [comment]
Thank you, I managed to come right with this issue. Was definitely credentials I needed to change.

**Comment by shres3007** [comment]
Hey Sanket, Thank you!
I understood, but I don't have access for main account. I can only use AWS Console through AWS Learner Lab which does not have admin permissions. 
So you are saying i can only deploy through main account of AWS console.

**Comment by ebrahim989** [comment]
Hello, I haven't tested on lab account but I would say main account works better.

**Comment by shres3007** [comment]
hello, yes correct but i don't have access of main account. that's why i asked how can i implement with Learner Lab AWS Console.

thank you

**Comment by portisto** [comment]
i'm using an admin account and i still get the same error. How do you check in Cloud9 which account is doing the execution?

**Comment by ebrahim989** [comment]
I found the account under the AWS credentials directory. It rotates the keys automatically. I preferred the EC2 method rather than Cloud9

**Comment by portisto** [comment]
thanks @ebrahim989 . I've dug deeper into why the stack create was failing and found it it was due to a known node version issue (it's required to use v14 and my version was v16). That particular issue is recorded here: https://github.com/awslabs/service-workbench-on-aws/issues/879

**Comment by ebrahim989** [comment]
Aah I see, yes correct. I had similar issues at first.

**Comment by maghirardelli** [comment]
Hi all! Is there any remaining issues here or can this issue be closed? We also have recently published a release that would work with node version v16 during deployment.

Thanks,
Marianna
