### ISSUE TITLE
[Feature Request] Auto-stop for EC2

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#1012]
We need a way to automatically stop EC2 instances when no one is using them. Students and new researchers may not remember to turn off their instances, draining research funding with inactive devices.

A solution where the instance has no active connections (ssh, rdp) and inactivity would be the best. (This has been requested for EMR instances as well.) If the user can select parameters related to this at creation that would be useful too, but not required.

**Comment by nguyen102** [comment]
Thanks for your request. I've added this feature request to our backlog. We'll keep this ticket updated with any news related to the feature.

**Comment by simranmakwana** [comment]
Hi, just wanted to ask if there is an update or proposed timeline for this work?

**Comment by manics** [comment]
We've [implemented](https://github.com/hic-infra/hic-tre-packer-images/blob/765e0e9a39c71b646a79dc89167989df8bd32186/modules/autohibernate.ps1#L1-L7) something similar to this using hibernation, e.g. add `powercfg /change hibernate-timeout-ac $Env:AUTOHIBERNATE_TIME` to the Packer template scripts.

This has the advantage that the workspace state is kept, so people are less likely to be annoyed if their instance is shutdown in the middle of some unsaved work. Note that you'll need to modify the workspace CF template to add [`HibernationOptions`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance-hibernationoptions.html)
```yaml
      HibernationOptions:
        Configured: "true"
```
There are other prerequisites for hibernation including instance type and disk space, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Hibernate.html

**Comment by srpiatt** [comment]
@manics How does the state in SWB UI note the workspace hibernation? Does it show it as 'stopped' and selecting the 'start' option starts it from hibernation? Have you experienced any issues with this flow from a UI perspective?

**Comment by manics** [comment]
@srpiatt It just shows as `stopped` and can be started as usual- the same as if an instance is shutdown from inside instead of using the SWB `stop` button.
