### ISSUE TITLE
[Feature Request] Ability to create new user roles

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#1017]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to create new user roles in the SWB UI, which means that AMIs have to be made available to all 'researchers' rather than giving a certain class of researchers, for example, access to more expensive instance types.

**Describe the solution you'd like**
Ability to create new roles in the SWB UI.

**Describe alternatives you've considered**
It's probably possible to manually add roles to the relevant DynamoDB tables, but given this isn't 'officially' supported in the UI, it feels a tad hacky.

**Additional context**
An 'Add Role' button and associated dialog on this page:
![image](https://user-images.githubusercontent.com/900469/181135542-47cebe0d-538f-4e8f-9bbc-5c9be317a541.png)

**Comment by tdmalone** [comment]
An update:
> It's probably possible to manually add roles to the relevant DynamoDB tables, but given this isn't 'officially' supported in the UI, it feels a tad hacky.

This doesn't actually solve the problem, as there's a bunch of code that makes it through to the `-apiHandler` Lambda function that references the `researcher` role by name. One of these is an `isInternalResearcher` function that references the name of the role, but that function doesn't appear to always be used and other times the name of the role is referenced directly as well.

**Comment by kpark277** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.

**Comment by tdmalone** [comment]
Adding a response so this doesn't get closed ;)

**Comment by paolosach** [comment]
Plus one to this request, it would be a really nice to have feature

**Comment by michaeldavistira** [comment]
I would say this is more that a nice to have feature, without it seems difficult to manage project more complex than basic ones
