### ISSUE TITLE
[Bug] start-image-builder.js using deprecated AppStream image

### ISSUE THREAD

**Issue by rikkibar** [awslabs/service-workbench-on-aws#1019]
In service-workbench-on-aws/scripts/appstream

The start-image-builder.js is now using a deprecated AppStream image 'AppStream-WinServer2019-10-08-2021' which is stopping the builder from running.

This should be replaced with the latest version 'AppStream-WinServer2019-07-12-2022'.

**Comment by kpark277** [comment]
Hi @rikkibar , thank you for bringing this to our attention. We will test with the new image and put up a PR shortly.

**Comment by SanketD92** [comment]
Fix has been merged.
