### ISSUE TITLE
[Bug] Error creating CodeBuild

### ISSUE THREAD

**Issue by ebrahim989** [awslabs/service-workbench-on-aws#1020]
Hello , I am attempting to deploy the AWS Service Workbench but getting the error that CodeBuild failed at custom setup.
I tried researching and found the following error attached.  Please advise how i can resolve.

**Comment by kpark277** [comment]
Hi @ebrahim989, can you provide a screenshot of the parameters for your moham stack?

Based on the stack structure present in your screenshot, this looks like an outdated/no longer supported version. We recommend using the most recent release of SWB (v5.2.0).

**Comment by ebrahim989** [comment]
Thank you @kpark277 . I used the default parameters as i was trying to test deployment. Where can i find the latest version v5.2.0 ?

**Comment by kpark277** [comment]
Source code for v5.2.0 can be found [here](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v5.2.0).

Please let us know if you run into a similar issue with v5.2.0.

**Comment by ebrahim989** [comment]
Thank you @kpark277 . Where do i find the CloudFormation template for 5.2.0 ?

**Comment by ebrahim989** [comment]
I am using the CloudFormation template from here: https://docs.aws.amazon.com/solutions/latest/service-workbench-on-aws/automated-deployment.html

**Comment by kpark277** [comment]
v5.2.0 no longer has one collective template for all of Service Workbench. We recommend using scripts/environment-deploy.sh as seen in the [installation guide](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/Service_Workbench_Install_Guide.pdf).

**Comment by ebrahim989** [comment]
Thank you , much appreciated.

**Comment by ebrahim989** [comment]
Hello @kpark277 , I seem to be hitting this erro:

 Credentials Error --------------------------------------

  CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
      at IncomingMessage.<anonymous> (/root/service-workbench-on-aws/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/util.js:904:34)
      at IncomingMessage.emit (events.js:412:35)
      at IncomingMessage.emit (domain.js:475:12)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

**Comment by SanketD92** [comment]
Hi @ebrahim989, please go through the [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html) configuration process on your machine. The deployment script depends on AWS profile credentials linked in your `main/config/<stage>.yml` file.

**Comment by ebrahim989** [comment]
Thank you @SanketD92! Are you saying that I should deploy via EC2 instance? Could you elaborate a little bit more please? Your guidance is appreciated.

**Comment by SanketD92** [comment]
It's up to you where you want to deploy from, but the system you choose needs to have the right permissions to the main AWS account (if you were trying to deploy from your local machine/laptop, you would need to set up AWS CLI).

The installation guide provides step by step instructions for installation, and suggests creating a Cloud9 instance or an EC2 Linux instance in the main account for deployment.

**Comment by ebrahim989** [comment]
Thank you @SanketD92. I have used the EC2 installation guide and using the ssh to deploy the scripts and that's how I got the error. Should I install aws cli on the Linux machine?

**Comment by SanketD92** [comment]
Please check if the EC2 instance already has AWS CLI configured. If it is, you would find AWS profiles listed in these files:
`~/.aws/config` and `~/.aws/credentials`. If not, then you would need to configure AWS CLI on the machine.

Also check what permissions the EC2 instance role has. For deployment purposes, we suggest the deploying AWS profile has admin privileges.

**Comment by ebrahim989** [comment]
Thank you @SanketD92 I will give that a try tomorrow and get back to you with an update.

**Comment by ebrahim989** [comment]
Hello @SanketD92 , I seem to be getting the following error after attempting to deploy (I added full permissions to EC2 and created added the aws profile:

![image](https://user-images.githubusercontent.com/70583720/183254248-8b907b5b-4c66-4a2e-9385-10742cffbb2d.png)

**Comment by ebrahim989** [comment]
I am now getting this error while using Cloud9:
Stack with id dev-va-sw-preDeployment does not exist

Could you please assist ? @SanketD92 @kpark277

**Comment by ebrahim989** [comment]
This is the last error i am getting whille using Cloud9 Deployment method, could you kindly help:

Stack with id dev-va-sw-preDeployment does not exist

Could you please assist ? @SanketD92 @kpark277

**Comment by ebrahim989** [comment]
It seems to be related to this error:
Resource handler returned message: "Uploaded file must be a non-empty zip (Service: Lambda, Status Code: 400, Request ID: )" (RequestToken:, HandlerErrorCode: InvalidRequest)

**Comment by ebrahim989** [comment]
Hello @SanketD92 @kpark277 , My latest error is:

 
Invoking pre-deployment steps

 
  Serverless Error ---------------------------------------
 
  The security token included in the request is invalid

**Comment by ebrahim989** [comment]
This is via the Cloud9 Deployment. I keep getting the error:

Invoking pre-deployment steps

 
  Serverless Error ---------------------------------------
 
  The security token included in the request is invalid

**Comment by SanketD92** [comment]
It seems your temporary credentials might have [expired](https://docs.aws.amazon.com/cloud9/latest/user-guide/troubleshooting.html#troubleshooting-cli-invalid-token). Please try with active temporary credentials.

**Comment by ebrahim989** [comment]
I used the EC2 option and got everything operational. For some reason the Cloud9 kept giving me security token issue.
