### ISSUE TITLE
[Feature Request] Support for multiple instance types eg. like with launch templates

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#1023]
**Is your feature request related to a problem? Please describe.**
We’re providing instance types to researchers that sometimes have constrained capacity (eg. p3), which results in a broken user experience when ‘insufficient capacity’ errors appear.

**Describe the solution you'd like**
Other than more capacity ;) It would be great if SWB could support launch templates, so we could provide multiple instance types that could fulfil the request.

**Describe alternatives you've considered**
The only other alternatives I can think of are to re-deploy SWB in regions with more capacity (not really feasible, especially with regional compliance constraints); or provide separate workspace configurations for researchers with different instance types (not a good user experience, because they then have to cycle through and wait 5 minutes for launches to fail before trying another one).

**Comment by Bingjiling** [comment]
Hi @tdmalone,

Thanks for the request! 

I looked up for the 'insufficient capacity' error and it seems to be a transient issue that should resolve itself. Are you running into this issue often? And for the solution, do you mean to have the multiple instance types to try out when deploying a EC2 instance type?

Thanks,
Yanyu

**Comment by tdmalone** [comment]
Hi Yanyu,

Sorry for the delay in responding. Yes in an ideal world it should be a transient issue, but it's also bad UX for a researcher who doesn't understand how the cloud works and then comes back to research IT asking why they haven't been given the capacity. In addition in the case of some instance types - I'm finding particularly with `p3` instances in `ap-southeast-2` - capacity is sometimes very regularly constrained and researchers currently have to just keep retrying, sometimes tens of times and at different times of the day, hoping that they'll be able to get through. So in those cases it's not really transient.

For the solution, yes I was referring to having multiple instance types to try out, however I figured that rather than implementing that as a direct solution in SWB, it could make sense to support launch templates which already implement that functionality (along with a lot more, such as spot instances). In other words, I was thinking that at some point there might just end up being requests to re-implement more of the same functionality that is already available via launch templates, so why not do it all in one go :)

In the above example, with support for multiple instance types (or launch templates), we could say configure a `p3` instance as the preference but then fall back to a `g4dn` when capacity is constrained. It's obviously not exactly the same thing but it could help a researcher avoid the 'insufficient capacity' error and still get a workspace running.

**Comment by FernandoAranda** [comment]
Hi @tdmalone  thanks for reaching out, I've added this feature request to our backlog. We'll keep this ticket updated with any news related to the feature.

**Comment by tdmalone** [comment]
Adding response so this doesn't get closed
