### ISSUE TITLE
EOL'ed Node.js functions

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#1024]
Service Workbench is currently using the nodejs12.x runtime for most of its Lambda functions (all except `Cognito-PreSignUp`), which is being EOL'ed by AWS.

AWS has started sending the following to accounts that have Service Workbench installed in them:

> We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Node.js 12 runtime.
>
> We are ending support for Node.js 12 in AWS Lambda. This follows Node.js 12 End-Of-Life (EOL) reached on April 30, 2022.
>
> As described in the Lambda runtime support policy, end of support for language runtimes in Lambda happens in two stages. Starting November 14, 2022, Lambda will no longer apply security patches and other updates to the Node.js 12 runtime used by Lambda functions, and functions using Node.js 12 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 12 runtime. Starting December 14, 2022, you will no longer be able to update existing functions using the Node.js 12 runtime.
>
> We recommend that you upgrade your existing Node.js 12 functions to Node.js 16 before November 14, 2022.
>
> End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.

Are there plans to upgrade Service Workbench Lambda functions to nodejs16.x before November?

**Comment by nguyen102** [comment]
Hi,

Thanks for bringing this to our attention. We have added this to our backlog and will prioritize making the update. We'll let you know soon what our ECD for this is.

-Tim

**Comment by maghirardelli** [comment]
Thanks for your issue on this!

:tada: Service Workbench on AWS (V1) [v5.2.3](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v5.2.3) has been released! This release includes the upgrade to using NodeJS runtime 16x in all Lambda functions and using Serverless v3 during deployment of components :tada:
