### ISSUE TITLE
[Bug] Service Workbench UI can't be reached after re-installation

### ISSUE THREAD

**Issue by ElenaKosobrodova** [awslabs/service-workbench-on-aws#1026]
**Describe the bug**
After re-installation of Service Workbench UI, I see an empty page. JavaScript console shows MIME Type error for one of chunks. See the screenshot below. I found that index.html is not updated correctly after re-installation. The last two filenames names of the chunks belonging to /JS folder are not updated. The error was replicated in two accounts. After manual correction of index.html, Service Workbench UI can be reached without any problem.

**To Reproduce**
1. Re-install Service Workbench UI
2. Open Service Workbench UI

**Expected behavior**
See Log in page.

**Screenshots**

![image](https://user-images.githubusercontent.com/47466926/185012346-b3b1723a-d500-4420-885d-84e5546bc78a.png)

**Versions (please complete the following information):**
 - Release Version installed: v5.0.0

**Additional context**

**Comment by Bingjiling** [comment]
Hi @ElenaKosobrodova,

Thanks for reaching out! Could you please share more details on how you Re-installed Service Workbench UI? Did you run the deployment script for just the UI package or did you make changes through AWS Console?

Thanks,
Yanyu

**Comment by ElenaKosobrodova** [comment]
Hi Yanyu,

I was asked to add custom user roles. Sam Annis-Brown (AWS Sr. Solutions
Architect) advised me to fork service-workbench-on-aws repository and add
minor changes to 3 files. One of the files contains a userRoleItems
dictionary where I added two new roles. The remaining files,
user-authz-utils.js and is-role.js, are responsible for authorization. The
added changes simply make permissions slightly wider and allow using
researcher-* roles.  They should not affect packing and index.html. To
re-install Service workbench, I  run scripts/environment-deploy.sh
"${Environment}" for the forked repository.

Best regards,
Elena

**Comment by Bingjiling** [comment]
Hi Elena,

Thanks for the information! Could you please share the link of the fork? And we can try to reproducing the issue on our side. 

Thanks,
Yanyu

**Comment by ElenaKosobrodova** [comment]
It was our internal issue. We fixed it.

**Comment by ElenaKosobrodova** [comment]
Hi Yanyu,

https://github.com/uon-cloud-project/service-workbench-on-aws-fork

Best regards,
Elena
