### ISSUE TITLE
[Feature Request] Support for Amazon Braket notebook instances

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#1033]
**Describe the solution you'd like**
Basically just support for launching Braket notebooks - it could work quite similarly to launching SageMaker notebooks.

**Comment by kpark277** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.

**Comment by tdmalone** [comment]
Adding response so this doesn't get closed
