### ISSUE TITLE
[Bug] CI/CD pipeline staging environment is missing permissions

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#1034]
**Describe the bug**
The CI/CD staging environment is missing IAM permissions to deploy to the environment represented by the `stgEnvName` setting.

In `main/cicd/cicd-pipeline/config/infra/cloudformation.yml`, a number of references to `envName` need to have `stgEnvName` added to them, and some references to `namespace` also need a similar setting eg. `stgNamespace` to be created and referenced.

**Comment by tdmalone** [comment]
Quick warning for anyone trying this themselves - you'll likely hit policy character limits, so you'll need to shorten some resource constraints.

eg. `arn:aws:iam::${AWS::AccountId}:role/${self:custom.settings.envName}-va-${self:custom.settings.solutionName}-edgeLambda-RoleCloudFrontInterceptor-*'` - which you'll need to duplicate to also reference `stgEnvName` - could be shortened to `arn:aws:iam::${AWS::AccountId}:role/${self:custom.settings.envName}-va-${self:custom.settings.solutionName}-*'` without any real loss in security. Some statements, such as the `iam:PassRole` for the Lambda role, could also be combined into other statements.

**Comment by SanketD92** [comment]
Hi @tdmalone, thank you for opening this issue. I've created a ticket in our backlog for this bug.

**Comment by SanketD92** [comment]
The fix has been merged. Let us know if this is still blocking you.
