### ISSUE TITLE
[Bug] Minor: Done button disabled when updating onboarded accounts

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#1043]
**Describe the bug**
When updating onboarded accounts, the _Done_ button is disabled, including after clicking _Update Stack_:
![image](https://user-images.githubusercontent.com/900469/193211948-4154e9a9-254b-45af-b5fa-7a3a6201501b.png)

To enable it, you have to click to the _Onboard New Account_ tab and check the box:
![image](https://user-images.githubusercontent.com/900469/193212223-01dbe7a7-feb2-42ea-b4a4-8566d932ac65.png)

It seems like the button just isn't aware that there's no checkbox to select on the _Update Onboarded Account_ tab.

**Versions (please complete the following information):**
 - 5.2.2

**Comment by kpark277** [comment]
Hi @tdmalone, thank you for reporting this bug. I am able to reproduce this and have created an item in our backlog to handle it.

**Comment by tdmalone** [comment]
Adding response so this doesn't get closed
