### ISSUE TITLE
[Bug] Open data filtering not working for certain datasets

### ISSUE THREAD

**Issue by emerson131** [awslabs/service-workbench-on-aws#1044]
The open data filter lambda is supposed to filter data based on tags specified in the lambda. However, in addition to the tags the lambda also filters out datasets if all the resources for that dataset are not s3 resources. This makes valid open datasets from being made available in Service Workbench

**To Reproduce**
1. Go to main/solution/backend/src/lambdas/open-data-scrape-handler
2. Add 'satellite imagery' as an additional tag in the filterTags variable
3. Run the Lambda
4. We will expect to see the himawari dataset to be made availble 'https://github.com/awslabs/open-data-registry/blob/main/datasets/noaa-himawari.yaml'
5. However this does not happen

**Expected behavior**
We should be able to see the himawari dataset made available in open data selection list

**Versions (please complete the following information):**
 - 5.2.0

**Additional context**
This is due to the following piece of code where the condition expects every resource to be an s3 resource, which may not be the case in the published open data set. In the example above for the himawari dataset, the resource types contain s3 and sns resources.

```
const fetchOpenData = async ({ fileUrls, requiredTags, log, fetchFile }) => {
  log.info(`Fetching ${fileUrls.length} metadata files`);
  const metadata = await Promise.all(fileUrls.map(fetchFile));
  log.info(`Filtering for ${requiredTags} tags and resources with valid ARNs`);
  const validS3Arn = new RegExp(/^arn:aws:s3:.*:.*:.+$/);
  const filtered = metadata.filter(({ tags, resources }) => {
    return (
      requiredTags.some(filterTag => tags.includes(filterTag)) &&
      resources.every(resource => {
        return resource.type === 'S3 Bucket' && validS3Arn.test(resource.arn);
      })
    );
  });
  return filtered;
};
```

**Comment by ssvegaraju** [comment]
Hi, thanks for bringing this to our attention! I'll go ahead and add this to our team's backlog.
