### ISSUE TITLE
[Bug] Mount failure for open datasets

### ISSUE THREAD

**Issue by emerson131** [awslabs/service-workbench-on-aws#1045]
**Describe the bug**
Open datasets fail to get mounted on ec2 instances 

**To Reproduce**
1. Select an open study on service workbench ( noaa-himawari)
2. Create a workspace in ec2
3. The datasets do not get mounted in the /home/ec2/studies/noaa-himawari path

**Expected behavior**
The opendata datasets should get mounted at the above location

**Versions (please complete the following information):**
 - Release Version installed : 5.2.0

**Additional context**
This is due to a bug in the mount_s3.sh file. In the above instance, the open dataset s3 location does not have a region, However the goofys mounting action tries to mount this dataset using the default instance region.

**Comment by ssvegaraju** [comment]
Hi, thanks for raising this issue, I've also added it our team's backlog! We'll update when there's any more information here.

**Comment by emerson131** [comment]
Additional Info
In another instance for mounting usgs-lidar dataset , both of the open dataset s3 location does not have a region and for one of the s3 locations, the open dataset can only be mounted if the requester pays flag is set during mounting. So even if you fix the mounting action to support mounting without region as mentioned in above , you will still need to add logic in the mounting code to successfully mount in case the s3 dataset requires the requester pays flag to be set. 

https://github.com/awslabs/open-data-registry/blob/main/datasets/usgs-lidar.yaml

**Comment by emerson131** [comment]
FYI: Just running goofys without the --region flag works for open datasets ( If requester pays is False). For requester pays, we need to add the corresponding flag for goofys (--requester-pays). Only problem is that SWB does not store this information in dydb and hence does not pass it on when the instances are provisioned with mounts

**Comment by tdmalone** [comment]
Possible duplicate of https://github.com/awslabs/service-workbench-on-aws/issues/1004

**Comment by kpark277** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.

**Comment by tdmalone** [comment]
Adding a response so this doesn't get closed.
