### ISSUE TITLE
[Bug] environment-delete.sh pretends that resources are deleted even when they're not

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#1059]
If `environment-delete.sh` has trouble loading credentials, it just pretends that deletion succeeds:

```
$ sh scripts/environment-delete.sh dev

--- Removing associated Service Catalog portfolio

Unable to locate credentials. You can configure credentials by running "aws configure".

...

- Emptying bucket -dev-syd-XXXXX-raas-master-artifacts ...                                                             
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --bucket: expected one argument


usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --bucket: expected one argument

- Emptying bucket -dev-syd-XXXXX-raas-master-artifacts ...  Done !                                                     
- Deleting bucket -dev-syd-XXXXX-raas-master-artifacts ... 
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --bucket: expected one argument

Done !

...

---- SSM Parameters
Deleting param /dev/XXXXX/jwt/secret
Unable to locate credentials. You can configure credentials by running "aws configure".

Deleting param /dev/XXXXX/user/root/password
Unable to locate credentials. You can configure credentials by running "aws configure".

*******************************************************************
*****     ----- ENVIRONMENT DELETED SUCCESSFULLY  🎉!! -----     *****
*******************************************************************
```

When credentials then are supplied to the environment, other errors are ignored too:

```
Starting to clear the application for stage [dev] ...

--- Removing associated Service Catalog portfolio

An error occurred (ResourceInUseException) when calling the DeletePortfolio operation: Portfolio port-njjmmttusbc3w is still shared with other accounts.

[script continues]
```

Also, if credentials are supplied via `$AWS_PROFILE` being exported in the environment, it only works at the start of the script. At some point, the script unsets `$AWS_PROFILE` (https://github.com/awslabs/service-workbench-on-aws/blob/mainline/scripts/environment-delete.sh#L204) but then expects credentials to still be available. When they're not, calls to the `aws` command end up trying to use the name of a bucket as the profile name instead:

```
- Emptying bucket XXXXXXXXXXXX-dev-syd-XXXXXX-studydata ...                                                             
The config profile (external-templates) could not be found

The config profile (external-templates) could not be found
- Emptying bucket XXXXXXXXXXXX-dev-syd-XXXXXX-studydata ...  Done !                                                     
- Emptying bucket XXXXXXXXXXXX-dev-syd-XXXXXX-external-templates ...                                                    
The config profile (external-templates) could not be found
```

**Comment by tdmalone** [comment]
It appears part of this issue may have been introduced with this commit:
https://github.com/emerson131/swb-customised/commit/a8439261949f00c18f2a761518036a9756676235#diff-830827598402a7eae1523ba8f52f3a25b2a0d49667b372a818cab8df585b4ad7

**Comment by tdmalone** [comment]
It appears part of this issue may have been introduced by:
https://github.com/awslabs/service-workbench-on-aws/commit/a8439261949f00c18f2a761518036a9756676235#diff-830827598402a7eae1523ba8f52f3a25b2a0d49667b372a818cab8df585b4ad7

**Comment by tdmalone** [comment]
Another issue with this script is that it doesn't quote parameters, eg.:
```
$ aws s3api delete-object --bucket $bucket --key $key --version-id $versionId
```
which in this case causes errors if object keys have spaces in them.

I'd recommend running `shellcheck` over this (and other) scripts to avoid issues like this. Shellcheck currently reports 84 issues with this script, including the above line.

**Comment by tdmalone** [comment]
Calls to `sls remove` also need to be replaced by `serverless remove`. `sls` is a 'structured list' app (https://npmjs.com/package/sls) and results in eg. this:
```
- Removing Stack Pre-Deployment ...
.../Library/pnpm/store/v3/tmp/dlx-43419  |   +1 +
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/tim/Library/pnpm/store/v3
  Virtual store is at:             ../../../../../../../../../Library/pnpm/store/v3/tmp/dlx-43419/node_modules/.pnpm
.../Library/pnpm/store/v3/tmp/dlx-43419  | Progress: resolved 1, reused 1, downloaded 0, added 1, done
./
 ├─config/
 │ ├─build(+)/
 │ ├─infra(+)/
 │ └─settings(+)/
 ├─node_modules/
 │ ├─@amzn(+)/
 │ ├─@babel(+)/
 │ ├─aws-sdk(+)/
 │ ├─babel-loader(+)/
 │ ├─babel-plugin-source-map-support(+)/
 │ ├─copy-webpack-plugin(+)/
 ...
```

rather than this:
```
- Removing Stack Pre-Deployment ...
.../Library/pnpm/store/v3/tmp/dlx-47383  |  WARN  deprecated querystring@0.2.0
.../Library/pnpm/store/v3/tmp/dlx-47383  |  WARN  deprecated querystring@0.2.1
.../Library/pnpm/store/v3/tmp/dlx-47383  |  WARN  deprecated superagent@7.1.6
.../Library/pnpm/store/v3/tmp/dlx-47383  |  WARN  deprecated @types/keyv@4.2.0
.../Library/pnpm/store/v3/tmp/dlx-47383  | +416 ++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/tim/Library/pnpm/store/v3
  Virtual store is at:             ../../../../../../../../../Library/pnpm/store/v3/tmp/dlx-47383/node_modules/.pnpm
.../Library/pnpm/store/v3/tmp/dlx-47383  | Progress: resolved 416, reused 416, downloaded 0, added 416, done
Running "serverless" from node_modules
Removing syd-XXXXXX-preDeployment from stage devstg (ap-southeast-2)

✔ Service syd-XXXXXX-preDeployment has been successfully removed (16s)
```

This seems to be a similar problem to that which is documented in https://github.com/awslabs/service-workbench-on-aws/issues/1016

**Comment by SanketD92** [comment]
Hi @tdmalone,

Thank you for opening this issue.

Running the script using valid credentials is a pre-requisite. It does not have logic built-in to select an AWS profile automatically.

Since the admin who can install SWB also has access to the main AWS account and can make custom edits to SWB resources, like those preventing simple deletion (eg. attaching a managed policy to SWB IAM role), the steps in the `environment-delete.sh` script are designed to skip over errors and proceed to the next set of resources. The script therefore makes a best effort in cleaning up an SWB installation to minimize manual deletion from the user on the AWS console. However, if resources were not found or deletion errored out due to any reason, they will need to be deleted by the user by visiting the console.

There are some opportunities for improvement that you've pointed out (like managing AWS_PROFILE between steps) that we'll take a look into.

**Comment by SanketD92** [comment]
Bug fixes have been merged to the script. Hope this helps in your cleanup attempts.
