### ISSUE TITLE
[Question] Update pipeline yaml file in s3?

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#1063]
**What's on your mind?**
Say an administrator wants to change one option (like `brandPageTitle`) in the yml stage file that the CI/CD pipeline uses, with no other pipeline or setting changes. If they change the stage file saved in the artifacts S3 folder and then click the `Release change` button in CodePipeline, is it the same as running the cicd script like this? `./scripts/cicd-deploy.sh $STAGE`

**Versions (please complete the following information):**
 - Release Version installed 5.0.0

**Comment by nguyen102** [comment]
Hi,

If an admin wants to change the configuration of the SWB Web App, they can change the settings file in the S3 artifact bucket. The CI/CD pipeline downloads that file and uses that configuration for deploying the SWB Web App. Once the new file is in the S3 bucket, you can update the WebApp by clicking `Release change`. That will trigger the pipeline to pick up to deploy the WebApp using the new config file.

The script `./scripts/cicd-deploy.sh` is for changing the pipeline itself. For example if you wanted to add a new stage to the pipeline to notify you when a deployment succeed, you will use `cicd-deploy.sh` to deploy that change.

I hope that helps!
-Tim

**Comment by srpiatt** [comment]
Great! This is what I was hoping for, but wasn't sure. Thank you!
