### ISSUE TITLE
[Bug] Sagemaker autostop script not pulling from s3 bucket

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#1065]
**Describe the bug**
We encountered an interesting issue regarding the auto stop script. We had no code changes, but suddenly, Sagemaker instances started hanging around for days, with no use. Looking into the instance, the cron job was failing, because the autostop.py script had a syntax error. When I look at the script, it has this line `print(f'Notebook idle state set as {idle} because no kernel has been detected.')` which caused the syntax error. However, the file on the repo, as well as the s3 bucket, does not contain this line. So, after some digging, I found that this line was introduced here, in this commit [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/commit/fdace58a6b9401c53dc17f5c64bef3ec40dbc70e). What I don't understand is how it got into the Sagemaker notebook, and why it's not being overridden by the custom config start we have here [sagemaker-notebook-instance.cfn.yml](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/sagemaker-notebook-instance.cfn.yml#L264-L272) This script and repo was updated in the last 16 hours to remove this syntax error.

**To Reproduce**
Launch a Sagemaker instance. You can tell which version of the script it's using by looking at the autostop script, `less /usr/local/bin/autostop.py` and find lines 96-101.

The AWS version of the script on the `awslabs/service-workbench-on-aws` repo has these lines, [reference](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/autostop.py#L96-L100)
```
if notebook['kernel']['connections'] == 0:
    if not is_idle(notebook['kernel']['last_activity']):
        idle = False
else:
    idle = False
```
And on the `aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples` repo, [reference](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/auto-stop-idle/autostop.py#L96-L101)
```
if notebook['kernel']['connections'] == 0:
    if not is_idle(notebook['kernel']['last_activity']):
        idle = False
else:
    idle = False
    print('Notebook idle state set as %s because no kernel has been detected.' % idle)
```

**Expected behavior**
The autostop script in the s3 bucket should be the one used for SWB Sagemaker instances.

**Screenshots**
<img width="1510" alt="Screen Shot 2022-11-16 at 12 14 21 PM" src="https://user-images.githubusercontent.com/21109191/202251401-67da0253-e74e-40e9-8150-99a4a27017ff.png">

**Versions (please complete the following information):**
 - SWB 4.3.1

**Comment by aws-tyler** [comment]
Just want to verify that the autostop script in your bucket had not been updated at some point in the past unexpectedly. Is that correct?

**Comment by srpiatt** [comment]
Yes-- none of the files on the s3 bucket were changed in several months. I also downloaded the autostop script from the bucket to verify manually that it matches the SWB repo version.

**Comment by maghirardelli** [comment]
I was not able to replicate this in v5.2.2:
<img width="937" alt="Screen Shot 2022-11-30 at 3 34 26 PM" src="https://user-images.githubusercontent.com/43092418/204903064-013c1899-2763-4c88-8cce-7b39128b0240.png">

If you look at the CloudWatch log group /aws/sagemaker/NotebookInstances/BasicNotebookInstance-<id>/LifecycleConfigOnStart do you see the following output (would be towards the end):
<img width="960" alt="Screen Shot 2022-11-30 at 3 36 08 PM" src="https://user-images.githubusercontent.com/43092418/204903303-d180144c-62d9-4775-a233-83687012715b.png">
This is triggered on start of the instance.

**Comment by srpiatt** [comment]
The screenshot you posted was from your instance, correct? Do you see the lines, 
```
print('Notebook is not idle:', notebook['kernel']['execution_state'])
idle = False
``` 
this line comes from this repo [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/master/scripts/auto-stop-idle/autostop.py#L100-L101). It should be only the one line, like below
```
idle = False
``` 
which comes from SWB here [awslabs/service-workbench-on-aws](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/autostop.py#L100)

The s3 file says it's downloaded, but for whatever reason it's not using that downloaded file, and instead using the file on aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples. This introduces SWB to vulnerabilities when this code is changes and a bug is introduced in that repo. SWB should instead use the autostop script that it has saved in s3, because that is locked and changes that aren't intended wouldn't be introduced.

**Comment by maghirardelli** [comment]
The screenshot is from my instance, yes. SWB repo contains the lines:
```
print('Notebook is not idle:', notebook['kernel']['execution_state'])
idle = False
```
[here](https://github.com/awslabs/service-workbench-on-aws/blob/61200d06d1a607b9c0a209240813b261ade2c5e9/main/solution/post-deployment/config/environment-files/offline-packages/sagemaker/autostop.py#L105). It is the lines:
```
idle = False
print('Notebook idle state set as %s because no kernel has been detected.' % idle)
```
that I thought you said were presenting the problem (that are in the samples repo but not SWB). Is that correct?

However, I see that my instance is not stopping even though the autostop script is the same as the SWB repo.

Where did you see the error on the cron job for the autostop?

**Comment by maghirardelli** [comment]
Also, to clarify, you see that the Cloudwatch logs copy from the s3 bucket to local and that the s3 bucket file is the correct file? Yet, you see the wrong file when you less the file on the instance?

**Comment by srpiatt** [comment]
Oh, you're right I was looking at the wrong line. My apologies! 

Yes- for us it's successfully copying the correct file from s3 (which I downloaded to verify), but the autostop script (`/usr/local/bin/autostop.py`) is the wrong copy.

**Comment by maghirardelli** [comment]
Got it. And where do you see the cron job failing?

**Comment by srpiatt** [comment]
Because it was not overwriting the autostop script with the one from our s3 bucket, and instead defaulting to the script from `aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples`,  when the repo owners introduced this commit: https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/commit/fdace58a6b9401c53dc17f5c64bef3ec40dbc70e, the cron job failed on lines like `print(f'Notebook idle state set as {idle} since kernel connections are ignored.')`, stating that the `print(f` part was invalid syntax.

I guess the key issue is really why it didn't overwrite this default script with the s3 one, considering it successfully downloaded the one from s3. Secondly, it seems odd that this repo is somehow the default autostop script that the Sagemaker system uses. This introduces bugs if there's a failure in that script or a malicious commit.

**Comment by maghirardelli** [comment]
Yes, I see the problem in the other repo's commit. I am still trying to debug how the script is on your Sagemaker instance.

Got ~two~ three more questions:
1. Where _in you account_ did you see that error message from the cron job? CloudWatch logs? Sagemaker? etc.
2. Are you working with AppStream-enabled SWB? Does Sagemaker have to go through AppStream to connect?
3. What is the output from running this command in a terminal on the sagemaker instance: `/usr/bin/python /usr/local/bin/autostop.py --time 300 --ignore-connections`?

**Comment by srpiatt** [comment]
Sure. :D Yeah I don't know how the script was there automatically. I didn't see any code in our repo that would cause it to pull from there.

We do not have appstream enabled, but we do send traffic through a proxy lambda as well as a firewall instance. However, all the environment files that get downloaded for the bootstrap process were successful, so I don't think it was a network issue.

The reason I checked the autostop script was because I saw no note in the `/var/log/autostop.log` file that the script is sent to via cron job. So I ran the script by hand.

For instance, right now autostop is not working. There's no messaging that tells you it's not working. When you look at the cron logs it shows this, with no errors. The `/var/log/autostop.log` script doesn't show any messages or errors.
```
[root@ip-10-10-57-235 ec2-user]# grep autostop /var/log/cron | tail -n 1
Dec  1 18:14:01 ip-10-10-57-235 CROND[9860]: (root) CMD (/usr/bin/python /usr/local/bin/autostop.py --time 3600 --ignore-connections >> /var/log/autostop.log)
```

But if you run the autostop script exactly as the cron job has it, like below, you get an error /right now/ related to a boto3 import issue.
```
[root@ip-10-10-57-235 ec2-user]# /usr/bin/python /usr/local/bin/autostop.py --time 3600
Traceback (most recent call last):
  File "/usr/local/bin/autostop.py", line 18, in <module>
    import boto3
ImportError: No module named boto3
```

Boto3 changes were introduced in a commit here, [in the on-start script on aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples](https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/commit/13b4023c9dca45fea58b2129fe5848619284653a#diff-54051e148aa00ee3fa158cc346d6c243418d14718a6760171ef562887977748f)

**Comment by maghirardelli** [comment]
Yup, so I also get that problem when I try to invoke the autostop script (and my autostop script matches the SWB one). I think that is the root cause of this problem. I will add a backlog item to figure out why boto3 is not being imported correctly so that sagemaker notebooks can use them for autostop. 

It still does not explain why you got the amazon-sagemaker-notebook-instance-lifecycle-config-samples in the instance. Was that only present in one instance or all instances? Is it possible someone manually changed the files when trying to debug the autostop not working?

Thanks so much for working through this with me!

**Comment by srpiatt** [comment]
Yeah, no problem-- thanks for your patience and attention! :D

I don't believe that the files have been altered. I am currently the only person on my team actively responsible for doing admin/infrastructure activities for these systems. I've tried this on new instances to rule out individual Sagemaker systems changes by users. We have two different version of SWB deployed-- maybe there's a difference between versions.

**Comment by nguyen102** [comment]
@srpiatt please upgrade your SWB installation to the latest release [v5.2.5](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v5.2.5). Sagemaker made a change that caused all new instances to be spun up with the AL2 operating system. New Sagemaker instances will no longer be able to mount studies or autostop without the fix in v5.2.5

**Comment by maghirardelli** [comment]
Hi! I also want to note that you may need to stop and start any affected instances after upgrade and deploying SWB v5.2.5.

If this fixes your issue, please go ahead and close this issue. I am going to mark as closing-soon-if-no-response so we will close in about 7 days if we do not hear that this did not resolve the issue.

Thank you for the report!

**Comment by srpiatt** [comment]
I pulled the changes committed for v5.2.5 into our forked repository, which is locked at 5.0.0 version. Auto stop works. Still not sure how the file got replaced with the one in that repo, but it's a non-issue at the moment. Thank you! :D
