### ISSUE TITLE
[Question] Limited Open Data list, 106/366

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#1068]
We noticed that the open data list in SWB is showing 106 studies, but the list on [aws.amazon.com/opendata](https://aws.amazon.com/opendata/) shows 366 data sets with an open data license. Is the study data getting grouped or filtered in some way before it gets added to SWB?

**Versions (please complete the following information):**
 - 4.3.1 & 5.0.0

**Comment by aws-tyler** [comment]
[These](https://github.com/awslabs/service-workbench-on-aws/blob/0602c2af9bd32001db91bf796cc491b2f5f130cf/main/solution/backend/src/lambdas/open-data-scrape-handler/handler-impl.js#L53) are the tags that are used for filtering.

**Comment by maghirardelli** [comment]
Additionally, we query from the GitHub repo: https://github.com/awslabs/open-data-registry owned by AWS, which indexes the [Registry of Open Data on AWS](https://registry.opendata.aws/). This is a slightly different link than what you provided. This is handled in the `openDataScrapeHandler` lambda.

**Comment by srpiatt** [comment]
Great! Thanks so much for providing the filter list and links-- Very much appreciated. :D
