### ISSUE TITLE
[Feature Request] Personal folders for users

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#1069]
Users need to save/backup files that they're working on for research projects. We need to be able to allow users to save their WIP files and data on the secured AWS networks and buckets, so they aren't tempted to move potentially sensitive files onto their personal devices or to some other cloud solution. For EC2 based instances, local files stay between start/stop but get removed on termination and are not sharable between a users's instances. In addition to that, for Sagemaker, local files are cleaned up between start/stop as well.

To work around this, we've been adding 'personal folders' under a study/bucket by hand for each user. This allows users to save files between start, stop, and terminate for any instance they create for a project. This is not scalable, however, as it requires manual creation and a stack update each time we add a new private folder.

The perfect solution/feature would allow a user to have a personal folder for each project which they can attach to any instance launched from that project. It would have to be project specific, because we intend to connect many institutions as study data sources, and derived data from those sources should remain on the source AWS accounts/buckets for security and compliance reasons. Ideally, this private folder would be added/enabled automatically upon adding a user to a project and automatically mounted for all instanced launched in that project.

**Comment by aws-tyler** [comment]
We'll add this to our backlog and work on it based on team priorities. Thanks!
