### ISSUE TITLE
[Bug] Project detail buttons don't reorder

### ISSUE THREAD

**Issue by DA-Osborne** [awslabs/service-workbench-on-aws#1070]
**Describe the bug**
On the accounts page, under projects, reordering the projects by one of the columns doesn't rearrange the blue 'Detail' buttons. Therefore, each Detail button no longer corresponds to the associated project in that row.

**To Reproduce**
1. Go to Accounts, then Projects tab.
2. Select the 'Detail' button for the first entry. The displayed entry will be correct.
3. Close this pop up.
4. Click on 'Project Name' column to sort them.
5. Select the 'Detail' button for the first entry. The displayed entry will be incorrect, and show the one from before.

**Expected behavior**
The correct project should pop up corresponding to the project in that row position.

**Screenshots**
![Screenshot_2022-11-18 15 30 25_fhhCdW](https://user-images.githubusercontent.com/43732435/202617657-31f18916-2b16-401f-a913-e2e683bede8b.png)

(Selecting the button at the top arrow brings up the project below it for example)

**Versions (please complete the following information):**
Version Beta 5.2.2

**Comment by kpark277** [comment]
Thank you, @DA-Osborne for identifying this issue. We have added this to our backlog and plan to begin working on a fix.
