### ISSUE TITLE
[Bug] Can't sort by project on Users page

### ISSUE THREAD

**Issue by DA-Osborne** [awslabs/service-workbench-on-aws#1072]
**Describe the bug**
Trying to sort by 'Project' on the Users page does not put the Users in order of project name.
(Sorting by Status works for 'Active', but 'Inactive' and 'Pending' are also out of order. All other columns sort normally.)

**To Reproduce**
1. Go to Users.
2. Click on Project column.
3. Users will rearrange, but not in Project name order.

**Expected behavior**
The list will sort by the name of the project in alphabetical order.

**Screenshots**
![Screenshot_2022-11-24 15 31 27_7yWHfO](https://user-images.githubusercontent.com/43732435/203694753-ee78b2b8-e40e-4718-a425-09aa6b15fb34.png)

**Versions (please complete the following information):**
 - Version Beta 5.2.2

**Comment by maghirardelli** [comment]
Thanks for your submission! We have added this item to our backlog!

**Comment by DA-Osborne** [comment]
I discovered that you can fix this by adding an accessor with the value 'projectId' to the Project column in the UserList.js file.
