### ISSUE TITLE
[Bug] Sagemaker AWS Credentials not Populating

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#1073]
When a Sagemaker notebook is launched with an associated study, the study folders are not mounted. Digging into this, I see that in the `~/.aws` folder there is no credentials file, which is generated by the `mount_s3.sh` script.

**To Reproduce**
- Create a new data source (or use an existing one).
- Select it and create a new Sagemaker instance using those studies. (Ensure that the folder has files so you can see them if they mount.)
- After the instance launches, connect to it and see if the study folders are connected. If not, open a terminal and run `ls ~/.aws` to see if the credential file is there.

**Expected behavior**
The study folders are mounted using the assumed roles in the AWS credentials file, generated by `mount_s3.sh` script.

**Screenshots**
<img width="702" alt="Screen Shot 2022-11-30 at 11 27 45 AM" src="https://user-images.githubusercontent.com/21109191/204853707-789607d5-6fca-4a77-911d-50a5c36a549b.png">
<img width="526" alt="Screen Shot 2022-11-30 at 11 27 36 AM" src="https://user-images.githubusercontent.com/21109191/204853710-824ddc98-dfb5-4c8b-abbe-f19fa2453640.png">

**Versions (please complete the following information):**
 - Versions 5.0.0 & 4.3.1

**Additional context**
This may or may not be associated with the other bug I noted with mounting s3 studies folders, [[Bug] SWB Sagemaker Study permission denied](https://github.com/awslabs/service-workbench-on-aws/issues/1067). It seems both of these issues are new, within the last couple weeks. And the environment has had no new deployments or changes within that time. Previous to these last couple weeks we had no issues with Sagemaker and study folders mounting.

**Comment by maghirardelli** [comment]
Thanks for the bug report! We are aware of the issue mounting studies to Sagemaker instances and are actively trying to resolve it. We will let you know if we need any more info to help in our debugging.

**Comment by simranmakwana** [comment]
Although I am able to successfully mount studies to RStudio instances, I have noticed that it is inconsistent. 
When an RStudio instance is first launched, the user must open the terminal. This triggers some code to run automatically which then mounts the studies, making them visible in the file viewer. However, we have noticed that sometimes the studies are never mounted and the sub-folders are not visible to the user. This appears to happen randomly. When we stop, restart, and click into the terminal tab, the issue is resolved.

**Comment by nguyen102** [comment]
@srpiatt please check the latest release [v5.2.5](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v5.2.5) for the fix to this issue.

**Comment by maghirardelli** [comment]
Hi! I also want to note that you may need to stop and start any affected instances after upgrade and deploying SWB v5.2.5.

If this fixes your issue, please go ahead and close this issue. I am going to mark as closing-soon-if-no-response so we will close in about 7 days if we do not hear that this did not resolve the issue.

Thank you for the report!

**Comment by srpiatt** [comment]
I pulled the changes committed for v5.2.5 into our forked repository, which is locked at 5.0.0 version. Credentials file is created and the studies folder is able to mount. Thank you! :D

**Comment by nitzanbenzvi** [comment]
Same happen to me in version 5.2.6, terminal trick didn't resolve the issue

**Comment by srpiatt** [comment]
This worked for a while, but I just tried launching another instance today to test if we're still encountering a different permissions issue, and encountered this bug again. We have the changes from the v5.2.5 SWB version pulled, as I noted before. I verified that we haven't regressed and that the changes are present in this instance. This is what we're seeing in this new instance, as of today.

<img width="586" alt="Screen Shot 2023-01-09 at 4 29 30 PM" src="https://user-images.githubusercontent.com/21109191/211414692-dd7f4d08-3564-43e3-93b8-839c46f33646.png">

Can anyone confirm that they're also seeing this bug again?

**Comment by nguyen102** [comment]
A new issue popped up that cause this issue to appear again. Please try updating to version 5.2.7.

**Comment by srpiatt** [comment]
Thanks! I'll give it a try. Is the change related to this commit, [https://github.com/awslabs/service-workbench-on-aws/commit/bdf978b1c909c37207902f1b29b0fd05b5b24208](https://github.com/awslabs/service-workbench-on-aws/commit/bdf978b1c909c37207902f1b29b0fd05b5b24208)? Until we update our fork to the latest version, we have to cherry pick these sorts of fixes. If yes, I can test that out today and close the ticket again if all good. :)

**Comment by nguyen102** [comment]
yep, that's it!

**Comment by srpiatt** [comment]
The changes worked for me. Thanks again, Tim! :D
