### ISSUE TITLE
[Bug] Sagemaker instance does not stop automatically

### ISSUE THREAD

**Issue by ElenaKosobrodova** [awslabs/service-workbench-on-aws#1076]
**Describe the bug**

Idle Sagemaker Notebook instances do not stop after specified time.

SWB runs autostop.py script to automatically stop Sagemaker Notebook instance. The script is used by `on-start` lifecycle rule of the instance CFN template. According to LifecycleConfigOnStart logs, some packages are missing and autostop script doesn’t work.
**To Reproduce**
1. Make sure AutoStopIdleTimeInMinutes parameter in workspace type config is set to a required time (30 minutes in our case)
2. Create a new workspace with Sagemaker notebook instance
3. Leave the instance idle for the time specified (AutoStopIdleTimeInMinutes )
4. After the specified time see that the instance is not stopped

**Expected behavior**
Idle Sagemaker Notebook instance automatically stops after specified time.

**Screenshots**
<img width="1308" alt="Screen Shot 2022-12-07 at 10 43 09 am" src="https://user-images.githubusercontent.com/47466926/206049662-5ff12457-8bd4-42bd-b12f-ce68fdfacaf6.png">

**Versions (please complete the following information):**
 - Release Version installed v5.0.0

**Additional context**

**Comment by maghirardelli** [comment]
Thank you. We are aware of this issue and have a backlog item to resolve this! See https://github.com/awslabs/service-workbench-on-aws/issues/1065 for more information.

**Comment by nguyen102** [comment]
Hi, please check the latest release [v5.2.5](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v5.2.5) for the fix to this issue.

**Comment by maghirardelli** [comment]
Hi! I also want to note that you may need to stop and start any affected instances after upgrade and deploying SWB v5.2.5.

If this fixes your issue, please go ahead and close this issue. I am going to mark as closing-soon-if-no-response so we will close in about 7 days if we do not hear that this did not resolve the issue.

Thank you for the report!

**Comment by ElenaKosobrodova** [comment]
Hi Marianna,
Thank you. I am going to migrate to v5.2.5 tomorrow. If everything goes
well, I'll close the ticket soon.

**Comment by SanketD92** [comment]
Closing this issue since the fix was merged, please feel free to reopen the issue if it persists on your end.
