### ISSUE TITLE
[Bug] More descriptive error message for "null is not an object" while trying to connect to Sagemaker notebook. 

### ISSUE THREAD

**Issue by simranmakwana** [awslabs/service-workbench-on-aws#1081]
**Describe the bug**
Users get the error "null is not an object" when pop-ups are enabled in SWB (reference:[ issue #620](https://github.com/awslabs/service-workbench-on-aws/issues/620))
This error is illegible to the user and causes confusion. Can we make the error message more clear such as:
"Service Workbench is encountering an error showing content. Please enable pop-ups and refresh the page."

**To Reproduce**
1. Diable pop-ups 
2. Connect to a workspace

**Expected behavior**
If the workspace is unable to open, a more legible error message should be shown, such as "Service Workbench is encountering an error showing content. Please enable pop-ups and refresh the page."

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v4.3.1 and v5.0.0]

**Additional context**

**Comment by kpark277** [comment]
Hi @simranmakwana, thank you for creating this issue. There are currently no plans to enrich the error messages in the UI; the recommendation is for you to customize the error messages within your installation of SWB as you see fit. Please reply back if there are any concerns with this approach. Thank you!
