### ISSUE TITLE
[Bug] study fail to mount in SWB 5.2.6 SageMaker Jupyter Notebook

### ISSUE THREAD

**Issue by jxuamazon** [awslabs/service-workbench-on-aws#1089]
**Describe the bug**
SWB 5.2.6 version - SageMaker jupyter notebook workspace can not mount a study.  see error in /var/log/message
/usr/local/bin/goofys[7248]: main.FATAL Mounting file system: Mount: mount: running fusermount: exec: "fusermount": executable file not found in $PATH#012#012stderr:

Looks like the FUSE package failed to install during on-start.  if run "sudo yum install fuse" then you can run /usr/local./share/workspace-environment/bin/mount_sh.sh /usr/local/etc/s3-mounts.json to mount the study. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]
 - Is the deployment from a forked version of the repository?

**Additional context**

**Comment by pbabz** [comment]
Thanks for reporting this issue. We are currently investigating the issue on versions 5.2.5 and 5.2.6.

**Comment by pbabz** [comment]
With the linked PR, the issue is now resolved and part of the 5.2.7 release.
