### ISSUE TITLE
[Bug] new user password creation issue

### ISSUE THREAD

**Issue by rpomaris** [awslabs/service-workbench-on-aws#1090]
**Describe the bug**
On a new SWB install, I can log in as root@example.com and create new users in the GUI. But when I try to log in as one of the new users, and use "reset password" to create a new password, I get the error "Could not reset password for the account, please contact support or try again." I am able to create a new user through Cognito (and log onto SWB, activate that new user, and log in as that user). But I cannot log in as a new user created through SWB.

**To Reproduce**
1. Following the [Installation Guide](https://raw.githubusercontent.com/awslabs/service-workbench-on-aws/mainline/docs/Service_Workbench_Install_Guide.pdf), install SWB in a new Isengard account using EC2.
2. Set a password for the root@example.com user and log on as that user
3. Create a new user (see screenshot) using an adapted version of your Amazon email as the username (e.g. rpomaris+researcher-1@amazon.com).
4. Log out of SWB. At login page, click "reset password." For the new user, input the username for the newly created user. See error.

**Expected behavior**
When I hit "reset password" for a new user, I expect to receive an email with a link to reset the password for the new user. 

**Screenshots**
![cannot-reset-password](https://user-images.githubusercontent.com/30879508/209984383-193c72e5-e036-4387-b72b-e7a14cac099b.png)
![users-created](https://user-images.githubusercontent.com/30879508/209984396-0515a280-30d6-45ba-bfde-40c3bf596ee2.png)

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3] **5.2.6** (I'm not sure how to check this, but I cloned from Github on 12/21, so I think this is right)
 - Is the deployment from a forked version of the repository? No.

**Additional context**

Things I've tried that didn't work:

- Using my standard amazon email address (rpomaris@amazon.com) instead of an adapted version (rpomaris+researcher-1@amazon.com)
- Using my gmail email
- Setting the new user as "guest" and as "internal-guest" instead of as "researcher"

The only thing that worked was creating a new user in Cognito.

**Comment by pbabz** [comment]
Hi, thanks for reaching out!

The flow for user creation requires the user to "sign up" via the login page. Creating a user via the User Portal doesn't create an entry in Cognito (the authentication system), so you won't be able to reset a password.

Make sure to create an account using the login page (see the "Sign up" hyper link at the bottom) before trying to change the password 
<img width="362" alt="image" src="https://user-images.githubusercontent.com/112134735/209992415-73f2a6e5-19ac-4404-ba96-207cc868326c.png">

**Comment by rpomaris** [comment]
Got it - thank you! This worked.
