### ISSUE TITLE
[Bug] no InstanceType dropdown on Sagemaker Workspace Configuration

### ISSUE THREAD

**Issue by rpomaris** [awslabs/service-workbench-on-aws#1091]
**Describe the bug**
When creating a Sagemaker Workspace configuration, the field "InstanceType" has no viable dropdown options. I'm not sure if this is expected behavior. I wrote in an instance type (g4dn.xlarge), which triggered an error on Workspace creation listing out the ml.* family instances I can write in. 

**To Reproduce**

In the SWB console, create Workspace, and edit Configuration Input Parameters.

**Expected behavior**
When setting the Workspace Configuration, I expect InstanceType to have a dropdown menu with all the viable instance type options.

**Screenshots**
![instance-type-selection](https://user-images.githubusercontent.com/30879508/210010977-3124e829-7c9d-4f7d-ad13-5242bd762437.png)
![image](https://user-images.githubusercontent.com/30879508/210010996-2da63521-a87e-43ad-b103-f7acec9f8fad.png)

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3] - 5.6.3
 - Is the deployment from a forked version of the repository? - no

**Additional context**

**Comment by pbabz** [comment]
Hi, this is expected behavior. This sounds like a feature request, I'll add it to our backlog.

**Comment by rpomaris** [comment]
Got it. Thank you!
