### ISSUE TITLE
[Feature Request] AWS Synthetics Canaries failing to monitor SWB - 403 error

### ISSUE THREAD

**Issue by avillach** [awslabs/service-workbench-on-aws#1093]
Hi,
I tired to use AWS  Synthetics Canaries  to monitor SWB (v5.0) and I'm getting a 403 Application denied error
Is there anything to change on AWS Synthetics Canaries default script OR on SWB to enable it to work?

Thanks!

Paul

**Comment by pbabz** [comment]
Hi Paul,

We don't have a reference implementation for integrating with AWS Synthetics Canaries, so I'll add this to the backlog with other requests.

 In the meantime, perhaps dig deeper into [Synthetics Canaries]( https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries.html)? It seems you may need to   modify roles/permissions to establish a relationship between the two systems.

**Comment by maghirardelli** [comment]
Closing due to no response
