### ISSUE TITLE
[Feature Request] Invalid diskSizeGB not detected until workplace is being created

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1105]
**Is your feature request related to a problem? Please describe.**
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/9889312/212991326-c5a31fd4-0563-41dc-b1b4-eb5c277dbaca.png">

`10GB` instead of `10` is accepted but a workplace fail to create when the configuration is used.

**Describe the solution you'd like**
This field should only accept a number.

**Additional context**
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/9889312/212991196-bfc5e71c-572c-4476-b87e-0fc378870242.png">

**Comment by maghirardelli** [comment]
Hi @BoPeng!

I am unsure what feature you would like here. The `DiskSizeGB` field must be a number for the EMR instance to launch. Our documentation ("Service_Workbench_Post_Deployment_Guide.pdf") states the field is not available in the drop-down menu with this context: "DiskSizeGB (>=10)" which implies the supplied value should be a number without the "GB". Please let me know more specifically what feature you are looking for here!

Thanks,
Mar

**Comment by BoPeng** [comment]
Hi, @maghirardelli 

As a web developer myself, I believe that invalid user input should be identified and corrected as early as possible. As it stands now, I can enter arbitrary values for disksize, the system acknowledges that the configuration is correctly created and saved, and then gives an error when the configuration is used, forcing me to edit the configuration and create the workplace again, with little confidence that the configuration will work.

I have seen many such issues with Service Workbench and reported some of them (e.g. #1106). I will stop doing so if these are not considered as bugs by you guys.

**Comment by maghirardelli** [comment]
Thanks for the response!

Yes, I see what you mean here. This form certainly has room for improvement to validate the values before users save the configuration. I will add a backlog item so we can work on this in the future!

On another note, if you are a web developer and have any free time (😄), feel free to contribute to the codebase if you find simple fixes. More information can be found in our [contributing](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/CONTRIBUTING.md) documentation. 

Thank you,
Mar

**Comment by BoPeng** [comment]
Thanks @maghirardelli , I have contributed to numerous open-source projects and will be happy to contribute to service workbench once I become familiar with the project and its code base.
