### ISSUE TITLE
[Feature Request] Instance type is not supported reported only during the creation of workplace

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1106]
**Is your feature request related to a problem? Please describe.**

When creating a workplace, an error message is returned saying `Instance type "t2.xlarge" is not supported`. 
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/9889312/212996949-cbc7812c-0eec-4386-8bb8-2a459e07ad91.png">

**Describe the solution you'd like**
A list of supported instance types can be provided during the creation of configurations, or the user provided instance type should be validated during the creation of the config. With the current design, even when the workplace is failed to create, it is unclear which instance types are supported so we can only proceed with trial and error.

PS: `t2.2xlarge` also failed so it is unlikely that the instance type is not powerful enough, and there must be some restrictions for the image or my account somewhere.

**Comment by BoPeng** [comment]
Just a quick update: I created a configuration for SageMaker using one of the recommended instance types (https://docs.aws.amazon.com/sagemaker/latest/dg/notebooks-available-instance-types.html) and I am able to create a sagemaker workplace. It is still unclear what instance types that EMR-V1 supports though.

**Comment by maghirardelli** [comment]
I do not believe t2.xlarge is a supported type for EMR. Please reference the [AWS Documentation](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-supported-instance-types.html#emr-instance-types-by-region) for available instance types. We do not maintain lists of supported instance types as the supported instance types are managed by the underlying AWS services.

**Comment by BoPeng** [comment]
Thanks for providing the link to supported instance types for EMR. It should have saved us a lot of guesswork if the product description or the configuration creation interface provides a link to EMR documentation.

**Comment by maghirardelli** [comment]
Thanks for bringing this to our attention! If you are able, you could always open a Pull Request with your proposal of where this link could live to best help users!

**Comment by kpark277** [comment]
Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.
