### ISSUE TITLE
[Question] Browser Cookies

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#1107]
Does the SWB application save any cookies before or after user login?

Our legal team is considering wether we need to add a cookie notice or not. I did not see any cookies set in chrome devtools when I loaded SWB, but I wanted to double check.

 - Release Version installed: 5.0.0

**Comment by maghirardelli** [comment]
Hi @srpiatt!

Thank you for the question! When we look in the browser, we don't see a value in the `Cookies` field, but there are values stored in `Local Storage`.  So, SWB does not have a cookie present but we still store data in the browser.

The code for login calls a method to [`saveIdToken`](https://github.com/awslabs/service-workbench-on-aws/blob/9edbc12bd85e0ddf4c2b271775b2fd41d9c2c236/addons/addon-base-ui/packages/base-ui/src/models/authentication/Authentication.js#L144), which saves the id token in [local storage](https://github.com/awslabs/service-workbench-on-aws/blob/9edbc12bd85e0ddf4c2b271775b2fd41d9c2c236/addons/addon-base-ui/packages/base-ui/src/helpers/utils.js#L88). Please let us know if you need any more info!

Thanks,
Mar
