### ISSUE TITLE
[Bug] Duplicate and insufficient documentation

### ISSUE THREAD

**Issue by juluriaj** [awslabs/service-workbench-on-aws#1108]
**Describe the bug**
SWB documentation versions have different instructions to install SWB. PDF documents seems outdated than github.io. Please consider deleting PDF versions and redirect users to github.io which seems like maintained well. 

**To Reproduce**
1. Go to https://github.com/awslabs/service-workbench-on-aws 
2. Click on Docs
3. Click to open any PDF document
4. Compare the contents with github.io version of the docs to find differences. Examples are installation instructions, configuration guides

**Expected behavior**
Update PDFs with latest instructions or redirect users to github.io version of the docs.

**Comment by pbabz** [comment]
Hi juluriaj, hopefully you found the documentation that is relevant to what you are trying to do. If you like, you can always send a PR to help update (or remove) outdated documentation!

**Comment by juluriaj** [comment]
I would love to contribute. Does my alias need to be part of Github team? Please send me the instructions, so I can make changes and submit a PR.

From: pbabz ***@***.***>
Reply-To: awslabs/service-workbench-on-aws ***@***.***>
Date: Monday, January 23, 2023 at 1:57 PM
To: awslabs/service-workbench-on-aws ***@***.***>
Cc: "Juluri, Abhilash" ***@***.***>, Author ***@***.***>
Subject: Re: [awslabs/service-workbench-on-aws] [Bug] Duplicate and insufficient documentation (Issue #1108)


Hi juluriaj, hopefully you found the documentation that is relevant to what you are trying to do. If you like, you can always send a PR to help update (or remove) outdated documentation!

**Comment by maghirardelli** [comment]
You do not need to be part of the Github team to submit a PR. Simply open a PR, and we can review it as we can to merge into `develop`. Please see our [Contributing](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/CONTRIBUTING.md) documentation.

**Comment by juluriaj** [comment]
submitted PR towards this issue and 1109

**Comment by maghirardelli** [comment]
Thank you so much! We will take a look!

**Comment by maghirardelli** [comment]
Closing as PR #1111 has been merged.
