### ISSUE TITLE
[Bug] Instructions to integrate with Azure AD is insufficient

### ISSUE THREAD

**Issue by juluriaj** [awslabs/service-workbench-on-aws#1109]
**Describe the bug**
Instructions to integrate with Azure AD for ID federation is insufficient. Users are unable to configure Azure AD without seeking additional help from AWS teams.

**To Reproduce**
1. Go to https://awslabs.github.io/service-workbench-on-aws-cn/configuration_guide/activedirectory
2. Start following instructions to integrate Azure AD
3. You will notice that the instructions are not sufficient for the user to complete the integration

**Expected behavior**
A clear and concise steps need to be documented to integrate Azure AD with AWS SWB.

**Comment by pbabz** [comment]
HI juluriaj,
Feel free to open a PR with documentation updates if you can!

**Comment by juluriaj** [comment]
submitted PR with updated documentation

**Comment by maghirardelli** [comment]
Thank you so much! We will take a look!
