### ISSUE TITLE
[Bug] pull 1110 introduced a bug - study mount fails on jupyter notebook

### ISSUE THREAD

**Issue by jxuamazon** [awslabs/service-workbench-on-aws#1112]
**Describe the bug**

Jupyter Notebook fail to mount study in the latest beta code, as the result of this:   https://github.com/awslabs/service-workbench-on-aws/pull/1110 
 
This is the error: 
      File "/home/ec2-user/.jupyter/jupyter_notebook_config.py", line 795, in <module>
        c.NotebookApp.kernel_manager_class = AsyncMappingKernelManager
    NameError: name 'AsyncMappingKernelManager' is not defined

---------------------- fix: 
boostrap.sh line 73 
c.NotebookApp.kernel_manager_class = AsyncMappingKernelManager  
-  AsyncMappingKernelManager was not defined ,

line 48 : 
from notebook.services.kernels.kernelmanager import MappingKernelManager   
should be  
from notebook.services.kernels.kernelmanager import AsyncMappingKernelManager

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]
 - Is the deployment from a forked version of the repository?

**Additional context**

**Comment by maghirardelli** [comment]
This issue should be resolved with the merging of this PR: https://github.com/awslabs/service-workbench-on-aws/pull/1114. Thanks @jxuamazon and @SanketD92 for the quick resolution!
