### ISSUE TITLE
Password change option for local users

### ISSUE THREAD

**Issue by mahbuburrahman** [awslabs/service-workbench-on-aws#1117]
How can a local user change their password from the service workbench interface/dashboard after being added?

**Comment by FernandoAranda** [comment]
Hi @mahbuburrahman thanks for reaching out, passwords are handled by Amazon Cognito so the only way to do it from service wokbench application would be clicking` forgot password?` link from login screen and following instructions.

-Fernando

**Comment by mahbuburrahman** [comment]
@FernandoAranda  thank you for your comment. I am not sure why I am unable to see the 'forgot password' link on the login page. The only information I can see is the login information. A screenshot has been attached for your reference.
![Screen Shot 2023-01-31 at 6 03 47 PM](https://user-images.githubusercontent.com/6240443/215904778-6e08da1c-c8a6-4808-bc81-9856cf576d9e.jpg)

**Comment by FernandoAranda** [comment]
Hi @mahbuburrahman, allowing forget password is a setting from Amazon Cognito you can enable it in your user pool > Sign-in Experience > User Account Recovery 
![image](https://user-images.githubusercontent.com/20051513/216118055-bc0fe11d-1339-4c56-9702-2b3079cfb98b.png)
![image](https://user-images.githubusercontent.com/20051513/216118246-038ab716-6827-4c39-a981-fd01699b8a0c.png)

**Comment by mahbuburrahman** [comment]
@FernandoAranda Thanks! I will explore it.

**Comment by FernandoAranda** [comment]
Hi @mahbuburrahman  let us know if there is anything else we can help you with

**Comment by mahbuburrahman** [comment]
@FernandoAranda after exploring, I see that I am currently not using federated login – looks like there is no Cognito pool in the management account for SWB. Can you please let me know this Cognito user pool available for non federated login?

**Comment by krupeshd1** [comment]
Hey Fernando, just a comment about the above - the Customer is running an old version of SWB (1.0.0) that has not been upgraded - it was using local users / passwords - it was entirely based on CloudFormation I believe - 

What is the upgrade path and process to get to the latest stable version? Is it possible?

Regards,
Krupesh

**Comment by aws-tyler** [comment]
Hey @krupeshd1 ! You can check out the ["Import Service Catalog Products" section of the Post Deployment Guide](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/Service_Workbench_Post_Deployment_Guide.pdf) to get instructions on how to upgrade.

**Comment by krupeshd1** [comment]
Hey Tyler,

Thank you - where does it highlight how to upgrade the initial deployment of SWB? Specifically these:



Service-Workbench-on-AWS 1.0.0 cnh-swb cnh-test Post-Deployment
--
  | cnh-test-va-cnh-swb-edgeLambda | CREATE_COMPLETE | 2022-04-06 17:26:29 UTC-0400 | Service-Workbench-on-AWS 1.0.0 cnh-swb cnh-test Edge-Lambda
  | cnh-test-va-cnh-swb-backend | CREATE_COMPLETE | 2022-04-06 17:19:55 UTC-0400 | Service-Workbench-on-AWS 1.0.0 cnh-swb cnh-test Backend
  | cnh-test-va-cnh-swb-infrastructure | CREATE_COMPLETE | 2022-04-06 17:16:02 UTC-0400 | Service-Workbench-on-AWS 1.0.0 cnh-swb cnh-test Infrastructure



Regards,
Krupesh

**Comment by maghirardelli** [comment]
Hi @krupeshd1,

You are many major versions behind mainline of SWB at this point. If possible, doing a fresh install would be ideal. If that is not possible, the changes, including breaking change are outlined in the [CHANGELOG](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/CHANGELOG.md). If you read through the changes, there should be instructions on how to upgrade between major versions. I would recommend doing it major version by major version. I will admit, we haven't heard of anyone upgrading from v1.0.0 to >v5.0.0. We recommend keeping up with these updates in the future so you don't get so behind feature development.

Let us know if you have any questions!

**Comment by krupeshd1** [comment]
Hello - one more question - if we decide to go with a new install of the latest service workbench - are there any known issues reusing the same SWB management account? Of course the names will differ for the stacks - 

 - Org Master Account (Payer)
        - SWB Management account
              -  SWB Member account 1
              -  SWB Member account 2



Regards,
Krupesh

**Comment by FernandoAranda** [comment]
Hi @krupeshd1 ,
Deploying another instance of SWB using the same account should work as long as you change the stage name, that will make sure stacks have different names.
In case you find any problems doing that don't hesitate to open a new Github issue

Regards
-Fernando
