### ISSUE TITLE
Broken Navigation Link

### ISSUE THREAD

**Issue by mahbuburrahman** [awslabs/service-workbench-on-aws#1118]
Most navigation links in the user guide are not functioning, such as the link for 'Configuring an IDP' from https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/docs/user_guide/sidebar/admin/auth/introduction.md which leads to a non-existent page. Is this a non-existent page or broken link?

**Comment by FernandoAranda** [comment]
Hi @mahbuburrahman thank you for bringing this issue to our attention, we will take a look at this and get back to you once we have updates , in the meantime you can see our documentation [here](https://awslabs.github.io/service-workbench-on-aws-cn) and access that specific link [here](https://awslabs.github.io/service-workbench-on-aws-cn/deployment/configuration/auth/configuring_idp/)

Thanks
-Fernando

**Comment by mahbuburrahman** [comment]
Thanks @FernandoAranda
