### ISSUE TITLE
[Bug] Study data not mounted in sagemaker

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1125]
**Describe the bug**
According to the documentation, "The selected sutdies will show up as mounted directories in the Jupyter notebook running on the workplace (SageMaker). These study directories will contain files uploaded to the corresponding study". However, I cannot see the uploaded files for both local and organization studies.

**To Reproduce**
1. Create a 'My Study" or "Organization" study 
2. Upload some files
3. Verify the files exists in the S3 bucket
4. Select study, next, create a workplace for SageMarker

**Expected behavior**
The `studies/study-name` should contain the uploaded files, but these directories are empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/9889312/217709402-29716727-dcd0-4f8f-a243-d0e297975817.png)

![image](https://user-images.githubusercontent.com/9889312/217709372-7d6d4fb7-4e84-4a79-9054-b1d425b07e4c.png)

![image](https://user-images.githubusercontent.com/9889312/217709433-4bc7fc8d-4761-44ea-bd7c-b10b4e0caf06.png)

**Versions (please complete the following information):**
 - Release Version installed : 5.2.5
 - Is the deployment from a forked version of the repository? No

** Other notes

* I also tried to use an open data study and the data does not show up.
* It would be helpful if we can check the logs for error messages. Right now we are totally at loss when things are not working as expected.

**Comment by aws-tyler** [comment]
Can you verify that you're using the latest Sagemaker instance type by going to the workspace types page and seeing if you have a new Sagemaker workspace type to import?

**Comment by BoPeng** [comment]
I started an ec2 instance and can see the study data, so the problem must have been with sagemaker.

However, when I go to the workspace types page, I can only see the ones that came with the initial installation (version 5.2.5). I do not see the version of the sagemaker type I have and do not see any update. How can I update my version of SWB, especially workspace types?

**Comment by BoPeng** [comment]
ok, I am on the aws service catalog page and can see the product IDs, and here is the version of sagemaker notebook that we have

![image](https://user-images.githubusercontent.com/9889312/217929019-e40e26f8-e422-4f7f-94c0-ba9c08211ee1.png)

Update: Poking around this problem might be related to https://github.com/awslabs/service-workbench-on-aws/pull/1079 so updating the sagemaker service catelog may fix the problem. Trying to figure out how to do that now.

**Comment by BoPeng** [comment]
@aws-tyler Could you point me to the documentation on how to add/update Service Catelog from AWS or update my installation of Service Workbench to the master branch of the repository? I used cloudformation to install SWB but the original EC2 instance is nowhere to be found. Thanks.

**Comment by aws-tyler** [comment]
I think the docs you might be looking for would be under the ["Import Service Catalog Products" section of the Post Deployment docs.](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/Service_Workbench_Post_Deployment_Guide.pdf) That should give you the instructions you need to deploy the latest sagemaker environment.

Let me know if that works. Thanks!

**Comment by BoPeng** [comment]
Thanks. The biggest trouble I had was the inability to find the EC2 instance for the installation. Once I re-vistited cloud9, I realized that I can restart the EC2 instance from cloud9.
