### ISSUE TITLE
[Bug] Unable to start workspace: incorrect launch contraint specified

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1131]
**Describe the bug**
When I start a RStudio workplace, I got an error message "The portfolio port-nvfd7zqe2losg has incorrect launch constraint specified. Make sure a local role name is specified as launch constraint for the portfolio."

**To Reproduce**
1. Subscribe to RStudio
2. Add Rstudio to service portfolio 
3. Create a constraint for EC2-Rstudio-Server using the default `dev-va-sw-LaunchConstraint`
4. Import workspace type,  create a configuration
5. create a workspace

**Expected behavior**
The workspace should be created

**Screenshots**
<img width="2174" alt="image" src="https://user-images.githubusercontent.com/9889312/220207307-85933839-a4a8-4214-82c1-b0e10a33aaaf.png">

<img width="1843" alt="image" src="https://user-images.githubusercontent.com/9889312/220207272-1f7d48ea-9aa8-4838-9c2a-212d37162d62.png">

**Versions (please complete the following information):**
 - Release Version installed : beta (5.2.7)
 - Is the deployment from a forked version of the repository? no

**Additional context**
1. I created another role following the instruction [here](https://docs.aws.amazon.com/servicecatalog/latest/adminguide/getstarted-deploy.html) but the problem persisted.
2. I am not sure what is a "local role". However, the description of the constraints for other products are "Launch as local role ....", but is "Lauch as arn::" for Rstudio (see the screenshot above). There is however no option to choose a "locel" role during the creation of the constraint.
3. The "SubnetID", "SecurityGroup" and "Architectures" might be incorrect for the Rstudio configuration.

**Comment by paolosach** [comment]
What worked for me was selecting "enter role name" when creating the constraint and writing the name of the role

**Comment by BoPeng** [comment]
This is beyond weird but the error message disappears after I remove and reenter the constraint by tying its name! 

Now I am getting another error:

![image](https://user-images.githubusercontent.com/9889312/220631623-350a9514-4515-4078-883c-6207cb0155a3.png)

It looks like my configuration is problematic but the error message is not helpful in telling me which field was entered incorrectly. I did have all fields filled so none of the fields should be `undefined`.

**Comment by aws-tyler** [comment]
@BoPeng hey, sorry you're having issues with this. Do you have more information about your configuration that you could share with us so we can try to reproduce?

**Comment by BoPeng** [comment]
Thanks @aws-tyler , here is my configuration:

![image](https://user-images.githubusercontent.com/9889312/222332126-98ed4e76-ca1d-484f-b865-a82bb9b79ca9.png)
![image](https://user-images.githubusercontent.com/9889312/222332145-2ec0d7e9-63cc-4c6c-881a-40b7f2173e5d.png)

I do not know what subnet id I should specify,

![image](https://user-images.githubusercontent.com/9889312/222332437-b8e3a659-0296-4d8c-998e-845c193f494a.png)

so I used the one for initial-stack

![image](https://user-images.githubusercontent.com/9889312/222332582-87f84eda-03ee-4991-bd79-6cc07e6c7547.png)

I saw a number of security groups associated with `vpc-00a6f1abaaf2f3684` and do not know which one to supply either.

Anyway, the error message does not point to which part of the configuration is wrong, or if it is a problem with the configuration.

**Comment by BoPeng** [comment]
Close because the original issue has been fixed.
