### ISSUE TITLE
[Bug] Deployment shows Successful but actually fails

### ISSUE THREAD

**Issue by spensireli** [awslabs/service-workbench-on-aws#1135]
**Describe the bug**
Installation succeeds but does not deploy. 

`.../share/pnpm/store/v3/tmp/dlx-24976    | Progress: resolved 1, reused 1, downloaded 0, added 1, done

Deployed website UI successfully

----- ENVIRONMENT DEPLOYED SUCCESSFULLY 🎉 -----

.../share/pnpm/store/v3/tmp/dlx-25003    | Progress: resolved 1, reused 0, downloaded 0, added 0
.../share/pnpm/store/v3/tmp/dlx-25003    |   +1 +
.../share/pnpm/store/v3/tmp/dlx-25003    | Progress: resolved 1, reused 1, downloaded 0, added 1, done`

**To Reproduce**
1. Follow the instructions for the Service Workbench Cloud 9 deployment. 
2. Deploy the solution, see results. 

**Expected behavior**
Past experience shows service workbench deploys a set of CloudFormation stacks and takes some time to complete deploy. The latest mainline branch does not. It just says "deploy successful" and doesn't actually deploy anything. 

**Additional context**
Deploying using the instruction guide in this readme as well as the linked instruction guide. Using Cloud 9 with administrator access. Can confirm access of AWS account is successful.

**Comment by SanketD92** [comment]
Please provide the versions of the following:

- pnpm
- node
- serverless

Also, could you confirm if a CloudFormation stack for the UI was created after you ran this command?

**Comment by BoPeng** [comment]
I had the same problem. You need to downgrade node to version 14 and pnpm to version 5. These were mentioned in the previous pdf-version of the documentation for installation through cloud9, but not mentioned in the current HTML version of the documentation.

**Comment by maghirardelli** [comment]
Thanks @BoPeng for your response!

You can run the following command to check your pnpm version: `pnpm --version`.

Workaround: Uninstall pnpm and reinstall the latest pnpm v5
```
npm uninstall -g pnpm
npm install -g pnpm@latest-5
pnpm --version
```

Thanks,
Marianna

**Comment by maghirardelli** [comment]
Added closing soon if no response since I believe the above should fix the problem. Let us know if you have further trouble!

**Comment by spensireli** [comment]
My issue was a little different surprisingly. I opened - https://github.com/awslabs/service-workbench-on-aws/pull/1151 to update the documentation. 

If you try to deploy the solution using Cloud9 and have it in a VPC / private subnet you will get this error. The reason being AWS managed temporary credentials aren't supported in private subnets per - https://docs.aws.amazon.com/cloud9/latest/user-guide/security-iam.html#auth-and-access-control-temporary-managed-credentials

**Comment by maghirardelli** [comment]
Oh nice find! I'm glad you found a solution. Thanks for opening the PR to improve the documentation!

**Comment by chriswood-cruk** [comment]
I don't think this can be closed when the fix it to install an old version of something, particularly now that there is a high severity vulnerability in that version:
```
[ec2-user@ip-172-31-7-149 infrastructure]$ npm install -g pnpm@latest-5

added 1 package, and audited 2 packages in 1s

1 package is looking for funding
  run `npm fund` for details

1 high severity vulnerability
```
