### ISSUE TITLE
[Bug] Only certificate from us-east-1 is allowed

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1142]
**Describe the bug**
When deploying service workbench in `us-east-2` and a certificate from `us-east-2`, the installer complains that the certificate is not from `us-east-1`.

**To Reproduce**
1. regular installation process, with region set to `us-east-2` and a certificate from `us-east-2`

**Expected behavior**
The certificate should be accepted, however, it now only works with another certificate created from `us-esst-1`, despite the fact that the cloud formation stack is created on `us-east-2`.

**Screenshots**

<img width="2065" alt="image" src="https://user-images.githubusercontent.com/9889312/224079764-1ca061e7-123d-4321-82ea-aa955b96bfc3.png">

**Versions (please complete the following information):**
 - Release Version installed: 5.2.7
 - Is the deployment from a forked version of the repository? no

**Comment by maghirardelli** [comment]
Hi @BoPeng! Thanks for the report!

Where are you specifying that you are deploying to `us-east-2`? I see that the full error link is in `us-east-2`, but can you check that the `awsRegion` and the `certificateArn` in your stage file (`prod.yaml`) specify `us-east-2`? 

I also see that you are using the "default" AWS profile--is there a region specified in that profile in the `.aws/config` file?

Thanks,
Marianna

**Comment by manics** [comment]
Is this because CloudFront _always_ requires a certificate in us-east-1?

**Comment by maghirardelli** [comment]
Oh @manics that seems right! Thanks for the input! According to this [AWS Documentation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-requirements.html#https-requirements-aws-region), the cert must be created or imported to `us-east-1`. Here's some [information](https://aws.amazon.com/premiumsupport/knowledge-center/migrate-ssl-cert-us-east/) on how to do that with your cert in `us-east-2`!

Thank you @manics! I'll mark a room for improvement for our documentation to mention this!

-Marianna
