### ISSUE TITLE
[Bug] Fail to start rstudio workplace due to empty description in version

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1143]
This is recreated from the [original report](https://github.com/awslabs/service-workbench-on-aws/issues/1131#issuecomment-1440011239)

**Describe the bug**
When start a Rstudio workspace, an error message "cannot read properties of undefined (reading substring)"

**To Reproduce**
1. subscribe to RStudio, add Rstudio to a portfolio
2. Import RStudio workspace type, create a config
3. start workspace

**Expected behavior**
Rstudio could be started

**Screenshots**

<img width="2163" alt="image" src="https://user-images.githubusercontent.com/9889312/224826418-70863087-c62a-4c28-8f6f-dd9ba85867f1.png">

![image](https://user-images.githubusercontent.com/9889312/225028395-6d36fdae-65a3-4628-8224-ece9c7df2d12.png)

![image](https://user-images.githubusercontent.com/9889312/225028472-8929eaad-d21e-4209-85fd-a0bddb198b2f.png)

**Versions (please complete the following information):**
 - Release Version installed: latest master
 - Is the deployment from a forked version of the repository? no

**Additional context**

Noticing the missing description, I created a new version using the same template of `pa-u3cqy3r4dqovi` and added a description,

![image](https://user-images.githubusercontent.com/9889312/225028888-d1c1599c-f2cf-458e-9bac-bd575f32d3ba.png)

and the error message disappears (although another error #1146  happens).

**Comment by BoPeng** [comment]
The process stopped before any stack is created in CloudFormation.

**Comment by BoPeng** [comment]
Update: One thing that does not look right is that when EC2-RStudio in Service Catalog does not have any description before it is imported.

![image](https://user-images.githubusercontent.com/9889312/225018876-4a54e8c4-fabc-4de9-b77e-435646f97bea.png)

**Comment by SanketD92** [comment]
So are you noticing the provisioning artifact with name `1.17` works but the one named `1.4.1717` erroring out?

Could you provide any error logs from the `workflowLoopRunner` CloudWatch log group from when you ran into this issue?

**Comment by BoPeng** [comment]
I am sorry but the original log messages have expired and I have switched to a newer version of RStudio Server (compiled by packer). To reproduce this error, I suppose you can create a new version of any product with the same template but empty description, or trace the source code and check how product description is handled.

**Comment by maghirardelli** [comment]
It seems like you have a workaround! We are going to close this ticket. Templates _should_ have descriptions when you import them to be compatible with SWB!

Thanks,
Marianna
