### ISSUE TITLE
[Bug] Failed to start windows workspace

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1144]
**Describe the bug**
When starting a windows workspace, an error message shows EC2 fail to create

**To Reproduce**
1. import windows 
2. create a configuration with 

<img width="1989" alt="image" src="https://user-images.githubusercontent.com/9889312/224836587-8228fcaa-fcca-4296-bc2e-74bafb473177.png">
<img width="2020" alt="image" src="https://user-images.githubusercontent.com/9889312/224836645-583212f3-e4e4-4e7c-a34f-fb60c5e24c73.png">
<img width="2084" alt="image" src="https://user-images.githubusercontent.com/9889312/224836671-0a2ed653-25a4-4594-9b9d-2cc9ba0cf9d8.png">

The AimId is selected from us-est-2 region.

**Expected behavior**
workspace starts correctly

**Screenshots**
<img width="2191" alt="image" src="https://user-images.githubusercontent.com/9889312/224836803-c22db02d-6fc2-4fe5-bf02-1bc6cc9f483b.png">

**Versions (please complete the following information):**
 - Release Version installed: latest master
 - Is the deployment from a forked version of the repository? no

**Comment by BoPeng** [comment]
I tried again and the following is the status of the EC2 instance before it was terminated. It is unclear why the instance was terminated.

**Comment by SanketD92** [comment]
Warning: @BoPeng please redact account ID and other sensitive information (like EC2 public DNS) from screenshots posted publicly.

**Comment by SanketD92** [comment]
Hi @BoPeng, could you check if the RaidDataVolumeSize entered is correct? The value you've entered could be larger than needed, since the resulting Raid Volume size is 8 times the size you mention in the config. Could you try with a smaller value for that config parameter (eg. 10, so this would result in actual size 10*8 = 80)?

**Comment by BoPeng** [comment]
I changed the volume size to 10 and the same error appears.

My parameters are (region: us-east-2):

DownloadIntervl: 600
RecurringDownloads: true
RaidDataVolumeSize: 10
RootVolumeSize: 30
StopRecurringDownloadsAfter: 240
InstanceType: t2.large
amiId: ami-0dc21fb273a648e34

<img width="2176" alt="image" src="https://user-images.githubusercontent.com/9889312/227319127-82c8cfe5-2323-410e-a6ac-a0de16778a2d.png">

**Comment by FernandoAranda** [comment]
Hi @BoPeng  
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.

**Comment by maghirardelli** [comment]
Closing due to no response
