### ISSUE TITLE
[Bug] TRE when deploying the TRE solution with devops profile and shared ami parameters the deployment fails

### ISSUE THREAD

**Issue by eldar557** [awslabs/service-workbench-on-aws#1156]
**Describe the bug**
TRE when deploying the TRE solution with devops profile and enableAmiSharing parameters the deployment fails

The Reason: 
The TRE deployment creates 2 IAM roles that are required for iam sharing over the devops account, this roles are created after running the enableAmiSharing and it fails as the IAM roles are missing.

Possible Resolution:
Create IAM Roles workflowLoopRunnerRole & apiHandlerRole before running the main/solution/prepare-devops-account

Workaround:
Deploy TRE environment without parameters devops profile and enableAmiSharing
After successful deployment, change the parameters evops profile and enableAmiSharing = true  in the <stage.yml> and run deploy again .
**To Reproduce**
Deploy environment from scratch :
Create  new environment <stage.yml> set enableAmiSharing = true with devops profile 
Run ./scripts/environment-deploy <stage>

**Expected behavior**
The deployment creates prepare devops account as part of the deployment

**Versions (please complete the following information):**
 - Release Version installed [5.2.7]

**Comment by kpark277** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.
