### ISSUE TITLE
[Feature Request] Clean Rooms as part of TRE?

### ISSUE THREAD

**Issue by nckbnv** [awslabs/service-workbench-on-aws#1158]
**Clearn Rooms**

The newly announced Clean Rooms service looks like a good fit for the this project..
https://aws.amazon.com/clean-rooms/features/

Are there any plans to add it as part of the project roadmap?

**Comment by kpark277** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.
