### ISSUE TITLE
[Misc] Need help debug a "No hosted zone found with ID" error message.

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1160]
**What's on your mind?**
When I tried to start a workspace [RStudio-Server](https://github.com/RLOpenCatalyst/Service_Workbench_Templates), I got an error message:

<img width="2150" alt="image" src="https://user-images.githubusercontent.com/9889312/227570086-18d5f8c3-f17e-4df9-a759-3236e0fdabe6.png">

This must be related to a hosted zone that we originally used to install SWB, but later replaced by a new hosted zone. Everything works all right until somehow this workspace, which creates an ALB, and tries to use this invalid hosted zone. I suppose this stops the process of adding a proper record in the right hosted zone.

I have checked
1. cloud formation does not show any error. Two stacks "Service-Workbench-on-AWS EC2-RStudio-RL" and "Service-Workbench-on-AWS ALB for RStudio IDE" show "CREATE_COMPLETE".
2. The load balancer, target group are there
3. The RStudio EC2 instance is running but I cannot connect to it with its public IPv4 address. The instance has an Elastic network interface.
4. The load balancer is created with no instance ID
5. The target group is not configured to receive traffic from the load balancer

So it looks like the link between target group and load balancer is not set up due to the use of a wrong hosted ID. Can anyone help me debug this problem further? I have checked dynamoDB but could not find any table containing any field with the hosted zone ID.

**Versions (please complete the following information):**
 - Release Version installed : latest master

**Comment by BoPeng** [comment]
Relevant code appears to be here after tracing `MetaConnection1Type` etc.

https://github.com/awslabs/service-workbench-on-aws/blob/f1486097a82ef3cb542fa49c5ea18d3c8d1bc8a7/addons/addon-base-raas/packages/base-raas-services/lib/plugins/env-provisioning-plugin.js#L233-L260

**Comment by BoPeng** [comment]
It appears that the problem was caused by a manual merge of hosted zones `example.com` and `workbench.example.com`,  with the latter created by SWB during installation and its zone ID recorded. After merging the records from `workbench.example.com` to `example.com`, the original zone ID is no longer valid, causing all the problems.

To fix this, either go into s3 bucket to update all the relevant files (not sure what they are), or remove all s3 buckets and re-install.

**Comment by SanketD92** [comment]
Only one hosted zone is required, that contains the appropriate custom domain records. The forwarding record for the respective workspaces are then listed in this hosted zone, as and when those workspaces get created.

It sounds like you're unblocked, or otherwise have a workaround to this issue. Is this correct?

**Comment by BoPeng** [comment]
Yes, I eventually figured out what was the problem but I had to do a fresh re-installation. 

The problem was that SWB creates hosted zone `workbench.example.com` and recorded its ID for later use. I however merged and removed this hosted zone with `example.com` so SWB failed to update the hosted zone when needed.
