### ISSUE TITLE
Cost Explorer for Cost Data

### ISSUE THREAD

**Issue by krupeshd1** [awslabs/service-workbench-on-aws#1167]
Hello SWB Team,

Is Cost Explorer enablement a requirement for SWB compute accounts - for the cost data to be available withing SWB UI? What happens if we are resellers and AWS does not allow enabling that due to various other reasons?

Regards,
Krupesh

**Comment by SanketD92** [comment]
Hello @krupeshd1, 

Cost Explorer enablement is a requirement for SWB hosting accounts. Please read through the instructions [here](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/docs/installation_guide/installation/pre-installation/tool-req.md) for the same.

If Cost Explorer cannot be enabled then the SWB dashboard and workspace-cost related information would not be accessible by the application.

**Comment by krupeshd1** [comment]
Thank you -
