### ISSUE TITLE
[Bug] Windows study not syncing on restart

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#1170]
**Describe the bug**
Windows does not sync study data on device restart. The syncing utility is not set as a task or service, and only started on initial EC2 launch.

**To Reproduce**
1. Associate a study to a windows EC2 and launch.
2. Connect and confirm syncing works in Windows.
3. Stop and then start device.
4. Confirm syncing does not work.

**Expected behavior**
S3 synchronizer for Windows should be running every time Windows is started.

**Versions (please complete the following information):**
 - Version 5.2.7, https://github.com/awslabs/service-workbench-on-aws/blob/mainline/addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/ec2-windows-instance.cfn.yml#L360-L365

**Comment by aws-tyler** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our
team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new
updates. If you require immediate assistance, please reach out to your AWS account team. Please note that
security issues should be reported directly to AWS Security at aws-security@amazon.com
