### ISSUE TITLE
[Misc] Are the old workspace templates in `base-raas-cfn-templates/src/templates` still required?

### ISSUE THREAD

**Issue by manics** [awslabs/service-workbench-on-aws#1175]
**What's on your mind?**
This repo contains duplicate workspaces templates under `addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/` and `addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/`

### [`addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/`](https://github.com/awslabs/service-workbench-on-aws/tree/develop/addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates):
- `ec2-linux-instance.cfn.yml`
- `ec2-windows-instance.cfn.yml`
- `sagemaker-notebook-instance.cfn.yml`

### [`addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/`](https://github.com/awslabs/service-workbench-on-aws/tree/develop/addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog):
- `ec2-linux-instance.cfn.yml`
- `ec2-windows-instance.cfn.yml`
- `sagemaker-notebook-instance.cfn.yml`

Is there still a use for the non-service-catalog templates? If not could they be removed to avoid confusion?

**Versions (please complete the following information):**
 - `develop` branch 8fb2320a4b2d583586591351db757d0a080a5280

**Comment by FernandoAranda** [comment]
Hi @manics ,thank you for reaching out. The templates in `addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/ ` are outdated and should not be used.
Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.

**Comment by maghirardelli** [comment]
We are closing this issue due to no response!
