### ISSUE TITLE
Stack failed to deploy

### ISSUE THREAD

**Issue by rkowtha** [awslabs/service-workbench-on-aws#1184]
Hello,

Today we were trying to create a new stack and the stack creation failed with the below error. 

This issue could be because of the new security changes made by Amazon S3 for new buckets created starting APRIL 2023, S3 Block Public Access will be enabled, and S3 access control lists (ACLs) will be disabled.

Can this issue be fixed ASAP. 

Here is the error that we received -
------------------------------

Stack dev-va-sw-infrastructure failed to deploy (13s)
Environment: linux, node 16.20.0, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: LoggingBucket (AWS::S3::Bucket)
**Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting** (Service: Amazon S3; Status Code: 400; Error Code: **InvalidBucketAclWithObjectOwnership**; Request ID: XXXXXXXXX; S3 Extended Request ID: XXXXxXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=; Proxy: null)

thanks

**Comment by maghirardelli** [comment]
Hi @rkowtha ! We are aware of this issue and working on it. I'll get back to you when we have a patch!

**Comment by maghirardelli** [comment]
Version 5.2.10 is released which fixes this issue. Please pull https://github.com/awslabs/service-workbench-on-aws/releases/tag/v5.2.10 and redeploy. If you had a failed stack (it would be in rollback-complete), please delete that stack. Fresh deployment should work again!
