### ISSUE TITLE
[Bug] Unable to SSH to a Linux system created from Service Workbench. Getting error Permission denied (publickey,gssapi-keyex,gssapi-with-mic). Not sure how to resolve it.

### ISSUE THREAD

**Issue by rkowtha** [awslabs/service-workbench-on-aws#1190]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]
 - Is the deployment from a forked version of the repository?

**Additional context**

**Comment by kpark277** [comment]
Hi @rkowtha, can you fill out the template on what steps you took? We have confirmed that ssh access to EC2 Linux is currently working, so we need details on how to attempt to reproduce the error you are seeing.

**Comment by rkowtha** [comment]
Not sure what template that I need to fill out. I still have the same error.

**Comment by kpark277** [comment]
Please provide details under each section in your original post. It should explain what steps you took to reproduce the bug and what version of SWB was used:

```
Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

    Go to '...'
    Click on '....'
    Scroll down to '....'
    See error

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Versions (please complete the following information):

    Release Version installed [e.g. v1.0.3]
    Is the deployment from a forked version of the repository?

Additional context
Add any other context about the problem here.
```

**Comment by janeyuaws** [comment]
close the issue since we don't receive further response
