### ISSUE TITLE
[Bug] insert summary deployment to Cape Town

### ISSUE THREAD

**Issue by ebrahim989** [awslabs/service-workbench-on-aws#1193]
Good Day,

I tried deploying this via the Cape Town Region. I then get this error:

cannot resolve serverless.yml: Variables resolution errored with:

    Cannot resolve variable at "custom.settings.awsRegionShortName": Value not found at "self" source,
    Cannot resolve variable at "custom.settings.awsRegionShortName": Value not found at "self" source

i edit the .default.yml file and add the af-south-1 region. tried deploying again and get the following error:

"Access denied for operation 'AWS::CloudFront::Distribution: You don't have permission to access the S3 bucket for CloudFront logs: -dev-cpt-sw-logging.s3.amazonaws.com If you're using IAM, you need s3:GetBucketAcl and s3:PutBucketAcl permissions to create a distribution or to update log settings for an existing distribution. In addition, the S3 ACL for the bucket must grant you FULL_CONTROL. (Service: CloudFront, Status Code: 403, Request ID: 561c3bbe-15b6-42fe-bfea-b66aadba1a00)'." (RequestToken: , HandlerErrorCode: AccessDenied)

Please advise how i can resolve ?

The solutions works perfect from the Ireland Region. I believe Cape Town is supported.

**Comment by aws-tyler** [comment]
Regions should be set in your custom yaml. Please refer to the [deployment guide](https://docs.aws.amazon.com/solutions/latest/service-workbench-on-aws/deploy-the-solution.html) for how you can customize the region for your deployment.

**Comment by ebrahim989** [comment]
Hi There,

I updated the region in the yaml file but still getting the same error
message.

The EC2 instance I have running in the cape Town region as well, and run
the scripts from there.

Are you perhaps able to test your side using the cape Town region?

**Comment by aws-tyler** [comment]
If you are able to, I would recommend using another region to deploy.

**Comment by aws-tyler** [comment]
Thank you for reaching out. Your request to check on the Cape Town region has been added to our backlog for research computing solutions. Our
team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new
updates. If you require immediate assistance, please reach out to your AWS account team. Please note that
security issues should be reported directly to AWS Security at aws-security@amazon.com

**Comment by ebrahim989** [comment]
I deployed the EC2 in Ireland region and set the yaml to Cape Town, but same errors popping up.

Would appreciate your support on this. We are needing to deploy for a University in SA.
