### ISSUE TITLE
[Bug] Query

### ISSUE THREAD

**Issue by ebrahim989** [awslabs/service-workbench-on-aws#1194]
Hello There,

Can one integrate Azure AD or any other SAML auth into AWS Service Workbench ?

Kind regards

**Comment by aws-tyler** [comment]
Please see [the documentation located here](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/docs/configuration_guide/activedirectory.md) for Azure AD integration.

**Comment by ebrahim989** [comment]
Thank you for your response.

Enjoy your weekend
