### ISSUE TITLE
Query on Workspace Types

### ISSUE THREAD

**Issue by mohamed-overdrive** [awslabs/service-workbench-on-aws#1195]
Good Day,

Is there any way i could create a custom Workspace environment type and import it into AWS Service Workbench ?
For example, using other services on AWS for a study other than the one provided.

Thank you

**Comment by SanketD92** [comment]
Hello,

If you mean creating a new environment type that is not one of the out-of-the-box ones (SageMaker, EC2 Linux, EC2 Windows, EMR, RStudio), then you'll need to follow the steps mentioned [here](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/docs/deployment/post_deployment/import_service_catalog_products.md). 

However you might need to add custom logic to support the new environment type-specific AWS SDK calls for operations like environment launch/start/stop/terminate. Take a look at the service code in this folder for reference: `addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog`

**Comment by SanketD92** [comment]
This issue has had no new correspondence in the past few weeks. Closing this now.
