### ISSUE TITLE
[Misc] Failed to SSH to EC2 instance through AppStream

### ISSUE THREAD

**Issue by t-young31** [awslabs/service-workbench-on-aws#1202]
Hi,

I'm getting the below error when trying to ssh to my ec2 instance after connecting through a workspace and wondered if you could provide some guidance?

<img width="694" alt="Screenshot 2023-06-26 at 08 59 16" src="https://github.com/awslabs/service-workbench-on-aws/assets/39765193/3916e490-a08e-4719-956f-39d7315ee709">

I have created a key pair in `/key-pair-management` and pasted the private key in (from a mac..).
I can SSH if I create an instance from the AMI and give it a public IP so not entirely sure what's going on. Any help would be much appreciated – thanks!

**Versions:**
 - Release Version installed: 6.0.0
 - PuTTY: 0.78
 - AppStream image: Microsoft Windows Server 2019 Base
 - Amazon linux version: 4.14.314-238.539.amzn2.x86_64

**Comment by t-young31** [comment]
After a pointer from @manics it seems like the time to get an appstream session and save the private key was >60 seconds and refreshing (clicking `Use this SSH key` again) fixed it. I think the time limit should be upped to at least 120s

**Comment by aws-tyler** [comment]
Hi @t-young31! Best practice for security is to keep the time as short as reasonably possible. We will be keeping it at 60 seconds. Thank you for your suggestion!

**Comment by t-young31** [comment]
I'm not sure 60 seconds is "reasonably possible" as in all my attempts (before getting the pointer) I clearly got timed out. Have you tried to (1) click connect, (2) wait for an app stream session (using on demand), (3) copy paste the pem data in, (4) save it to downloads, (5) load in into putty, (6) save it as a ppk, (7) paste in the host IP, (8) navigate to the auth section in putty (8) load in the ppk, (9) type ec2-user and hit connect within 60 seconds? I don't think it's possible.

Is the security risk more than opening up 22 for that time? (sorry for not digging into the code and finding out what happens!)

**Comment by t-young31** [comment]
I've dug in and it seems like it's set because the underlying [ec2-instance-connect](https://docs.aws.amazon.com/cli/latest/reference/ec2-instance-connect/index.html#cli-aws-ec2-instance-connect) sdk only supports it existing for 60 seconds.  It's probably worthwhile adding something to the connection help?
