### ISSUE TITLE
[Misc] Under what condition can workspace be shared?

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1204]
**What's on your mind?**
We have multiple workspaces with sagemaker, rstudio etc. I can access some of them but not others (a "forbidden" message appeared). I checked the documentation and could not find any information on how workspaces can be shared among users. Can anyone point me to documentation on sharing workspaces among users? More specifically, under which conditions that I can access to workspaces created by other users?

**Versions (please complete the following information):**
 - Release Version installed [e.g. v5.2.7]

**Comment by janeyuaws** [comment]
Here is the [User Guide](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/Service_Workbench_User_Guide.pdf). The workspace is accessible within the project boundary.

**Comment by BoPeng** [comment]
@janeyuaws I already read the documentation but it is not clear on the permission issue. Maybe I have missed something obvious?

On page 12:

> You can connect to workspaces that you have access to. 

This does not say the conditions on which I have access to a workspace. Also, how do I know if I have access to a workspace? Why do not the system only list the workspaces that I have access to? Right now, the only way to tell is to try to connect.

> If the `restrict AdminWorkspaceConnect flag' is enabled, ... they are assigned to.

Where is this flag? I did not see such a flag when I create a workspace. 

> The workspace is accessible within the project boundary.

Do you mean that anyone who is associated with a project will be able to access any workspace associated with the project? This is clearly not the case during testing. As a matter of fact, we have two admin users associated with the same project, and one could access a workspace and another one could not, and we cannot find any obvious reason for the difference.

**Comment by SanketD92** [comment]
@BoPeng The workspaces you can have access to depends on workspace ownership (i.e. workspaces that you created) and your user role in the application. 

Being an IT admin of the application allows you to access all workspaces, including those that you did not create. (Connection is allowed given your IP access has been permitted by the CIDR range entered for the workspace)

Researchers can only access workspaces that they created. Currently there isn't a way to "share" workspaces among researchers in SWB.

The `restrictAdminWorkspaceConnection` flag is set to `false` by default in the `main/config/settings/.defaults.yml` file. You can override this setting with your chosen value in your `main/config/settings/<stage>.yml` file, and redeploying the application.

**Comment by bioworkflows** [comment]
Thanks for the clarification, so by default `researchers` cannot see others' workspaces. This is a huge problem and we may have to make most researchers the admin.

We have also had problems on admins failing to connect to workspaces. Let me see if IP address is the culprit. Note that CIDR settings are unavailable for some workspace types.

**Comment by BoPeng** [comment]
Thanks for the clarification, so by default `researchers` cannot see others' workspaces. This is a huge problem and we may have to make most researchers the admin.

We have also had problems on admins failing to connect to workspaces. Let me see if IP address is the culprit. Note that CIDR settings are unavailable for some workspace types.

**Comment by kpark277** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our
team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new
updates. If you require immediate assistance, please reach out to your AWS account team. Please note that
security issues should be reported directly to AWS Security at aws-security@amazon.com.
