### ISSUE TITLE
[Misc] AppStream Elastic Fleet to run Stata workspace

### ISSUE THREAD

**Issue by paolosach** [awslabs/service-workbench-on-aws#1208]
We are trying to create a workspace that runs Stata with its gui.
My first question is: has anyone evere done this? And if so, how?

Since it doesn't have a server version such as RStudio, we thought of AppStream to run it as a single app and we chose the Elastic type for the fleet as it allows to run Session Scripts that we can use to mount the study bucket, similarly as the ec2 workspace does.

One of the issues we've come across so far is Elastic fleets require two subnets, but SWB only deploys one when TRE is not enabled. 
Is there any way to change this before or better after SWB deployment? Where would I need to look?

Stata is a pretty common tool for researchers, so this might have space for a Feat request at a later time.

Thanks for any advice anyone might have.

**Versions (please complete the following information):**
 - Release Version installed 5.2.11

**Comment by maghirardelli** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our
team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new
updates. If you require immediate assistance, please reach out to your AWS account team. Please note that
security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:aws-security@amazon.com).
