### ISSUE TITLE
[Bug] Abrupt logout from gui with active user

### ISSUE THREAD

**Issue by paolosach** [awslabs/service-workbench-on-aws#1213]
**Describe the bug**
The application forcefully logs user out when reaching timeout, even if the user is not idle.

**To Reproduce**
1. Perform login
2. Create new workspaces configurations
3. Do so until time expires
4. Get logged out with no warning

**Expected behavior**
I would expect one of these three:
1. While the user is not idle, timeout does not expire
2. If the timeout must expire, there is a way to extend it
3. If there is no way to extend it, at least a warning saying that seesion will expire would be nice to save what the user was doing

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed 5.2.11
 - Is the deployment from a forked version of the repository? No

**Additional context**

**Comment by maghirardelli** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our
team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new
updates. If you require immediate assistance, please reach out to your AWS account team. Please note that
security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:aws-security@amazon.com).
