### ISSUE TITLE
[Misc] Node 18 support?

### ISSUE THREAD

**Issue by amdixit** [awslabs/service-workbench-on-aws#1216]
**What's on your mind?**
GIven node 14 and 16  are scheduled to be deprecated by the end of year. When is the plan for this project to use node 18 for lambda deployments.
**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]

**Comment by SanketD92** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our
team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new
updates. If you require immediate assistance, please reach out to your AWS account team. Please note that
security issues should be reported directly to AWS Security at aws-security@amazon.com

**Comment by tdmalone** [comment]
Hi @SanketD92, are you able to confirm that upgraded functions will be part of a new release before 27th November, given the current version of SWB will not be able to be installed past that time?

> As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting November 27, 2023, Lambda will no longer apply security patches and other updates to the Node.js 14 runtime used by Lambda functions, and functions using Node.js 14 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 14 runtime. Starting January 25, 2024, you will no longer be able to update existing functions using the Node.js 14 runtime.
We recommend that you upgrade your existing Node.js 14 functions to Node.js 18 before November 27, 2023.

**Comment by amdixit** [comment]
@SanketD92 any update here?

**Comment by maghirardelli** [comment]
We just release [v6.2.0](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v6.2.0) which upgraded Lambda Node runtimes!
