### ISSUE TITLE
Remove hosting account

### ISSUE THREAD

**Issue by krupeshd1** [awslabs/service-workbench-on-aws#1220]
Hello SWB Team,

I can seem to find any documentation to remove a hosting account from service workbench - can you please provide steps or documentation? I see the sections for onboarding accounts but not removing them - 

Regards,
Krupesh

**Comment by maghirardelli** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our
team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new
updates. If you require immediate assistance, please reach out to your AWS account team. Please note that
security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:aws-security@amazon.com).

**Comment by krupeshd1** [comment]
Hey Marianna, 
So is the ask not possible today?




Regards,




Krupesh Derashri 

Cell: 908-208-6473





 

    On Friday, August 18, 2023 at 10:45:52 AM EDT, Marianna Ghirardelli ***@***.***> wrote:  
 
 


Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our
team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new
updates. If you require immediate assistance, please reach out to your AWS account team. Please note that
security issues should be reported directly to AWS Security at ***@***.***

**Comment by maghirardelli** [comment]
We currently do not have any documentation related to removing the account that I could easily share with you. The request for it has been added to our backlog.

**Comment by tdmalone** [comment]
@krupeshd1 This isn't possible by default in SWB but you could do it manually by:
1. removing all CloudFormation stacks created in the **hosting account** by Service Workbench, including the `initial-stack` created by an administrator at onboarding
2. manually removing the row for the hosting account in the `AwsAccounts` table in DynamoDB (in the **management account**) - taking care to not accidentally edit or remove any rows for other accounts you still wish to use!
