### ISSUE TITLE
[Feature Request] Real-time Collaborative Jupyter notebooks

### ISSUE THREAD

**Issue by annalu12** [awslabs/service-workbench-on-aws#1221]
**Is your feature request related to a problem? Please describe.**
Our team wants real time collaboration to share Jupyter notebooks with people who are both internal and external to SWB.

**Describe the solution you'd like**
Do you have any other recommendations to enable Jupyter notebook sharing or collaborative sessions without having to log in to AWS console?

**Describe alternatives you've considered**
- We tested this Jupyter extension https://jupyterlab-realtime-collaboration.readthedocs.io/en/latest/
with two users on SWB with IP whitelisted in admin settings however the sharable link redirects to the AWS console login.
- We also considered asynchronous sharing through GitHub repositories however would like to also protect the data (e.g. disable pushes to public repositories, disabled Jupyter file downloads to local machines).
- When will the latest version of JupyterLab 4 be on the roadmap for SWB?

**Comment by SanketD92** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our
team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new
updates. If you require immediate assistance, please reach out to your AWS account team. Please note that
security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:aws-security@amazon.com).
