### ISSUE TITLE
[Bug] Logging in with root@example.com does not give root priveleges

### ISSUE THREAD

**Issue by Wisdawg** [awslabs/service-workbench-on-aws#1226]
We have a root user confirmed in the Cognito user pool utilized by our Service Workbench instance but when we try to log in with that root user we're not granted root access instead we get a response to wait for the admin to approve. I'm following along straight from the SWB docs so it's not apparent to me what the issue is. Any help debugging would be greatly appreciated!

<img width="438" alt="Screen Shot 2023-10-10 at 12 47 51 PM" src="https://github.com/awslabs/service-workbench-on-aws/assets/13368228/635e21c2-245c-43cd-925c-6acf6e89ab76">

<img width="889" alt="Screen Shot 2023-10-10 at 12 46 25 PM" src="https://github.com/awslabs/service-workbench-on-aws/assets/13368228/65ec8431-a9fd-46f8-aff4-2c5777efd959">

**Comment by maghirardelli** [comment]
Hi! After deploying SWB, you should see a "Temporary Native Pool Password" output from the deployment script. Use this password and the email specified in the stage configuration file as `rootUserEmail` to log into SWB for the first time. This should prompt you to reset the password from the value that was provided as the "Temporary Native Pool Password".

After this, you can add users from within the SWB UI Users page by clicking "Add Federated User" and providing an email there. The user can navigate to the login page where they must specify "Sign up" and provide their desired values. If you do not add the federated user from within the SWB UI, the user will see the message that their application has been received and will require someone to use the "Add Federated User" workflow to have them gain access to the SWB deployment.

Thanks,
Marianna

**Comment by Wisdawg** [comment]
We tried up another instance and got it to work by setting the root email as a different address than the one we first tried and it seems to have worked. You can close this issue. Thanks!
