### ISSUE TITLE
cfn template "emr-cluster.cfn.yml" and related resource should be modified.

### ISSUE THREAD

**Issue by ghost** [awslabs/service-workbench-on-aws#123]
deployment region - ap-northeast-2

~~1. In the template, Service Role for EMR does not have KMS policy. Thus SecurityConfiguration makes below problem.~~

~~The EMR Service Role must have the kms:GenerateDataKey* and kms:ReEncrypt* permission for the KMS key configuration when you enabled EBS encryption by default. You can retrieve that KMS key's ID by using the ec2:GetEbsDefaultKmsKeyId API.~~

~~KMS policy should be added to the Service Role.~~
_Identified as my member account setting problem_

2. Fail to bootstrap "us-east-1.elasticmapreduce/bootstrap-actions/run-if" on non us-east-1 region.
EMRFS could not download bootstrap file on other region. Thus it makes below problem.

Master instance failed attempting to download bootstrap action 1 file from S3

run-if script should be copied to the same region bucket and cfn template should be modified.

~~3. Additionally, cross account role also should have KMS policy.~~
_Identified as my member account setting problem_

**Comment by rsmayda** [comment]
Hey are you still facing any issues I see that 1 & 3 seem to be account setting issues. Is 2 still applicable?

**Comment by inhwan-aws** [comment]
Could you please make EMR cluster on the other region except us-east-1?

**Comment by rsmayda** [comment]
Thanks for confirming issue 2 is still present -- we will keep this issue up to date with our progress

**Comment by SanketD92** [comment]
@inhwan-aws Thanks for bringing this up. We have identified the potential root cause for this bug. The bootstrap action script path and IAM policy resource reference the us-east-1 region in the emr templates (built-in, service-catalog and external), which would need the following changes:

```
From
s3://us-east-1.elasticmapreduce/bootstrap-actions/run-if
to
!Sub s3://${AWS::Region}.elasticmapreduce/bootstrap-actions/run-if
```

```
From
'arn:aws:s3:::us-east-1.elasticmapreduce/bootstrap-actions/run-if'
to
!Sub 'arn:aws:s3:::${AWS::Region}.elasticmapreduce/bootstrap-actions/run-if'
```

We will be making and testing these changes soon. Stay tuned.

**Comment by inhwan-aws** [comment]
Thank you, Sanket!

**Comment by virgo81net** [comment]
@SanketD92 

In the process of combining the two accounts, the existing account (@inhwan-aws) was deleted, 
so please understand that previous posts and comments appear as ghost :)

I tried what you suggest but a bucket "elasticmapreduce" must be unique globally, so it doesn't exist in other regions.
Thus, this solution is not work for me. (my region is ap-northeast-2)

```
From
s3://us-east-1.elasticmapreduce/bootstrap-actions/run-if
to
!Sub s3://${AWS::Region}.elasticmapreduce/bootstrap-actions/run-if
```
```
From
'arn:aws:s3:::us-east-1.elasticmapreduce/bootstrap-actions/run-if'
to
!Sub 'arn:aws:s3:::${AWS::Region}.elasticmapreduce/bootstrap-actions/run-if'
```

Thanks and regards,
Inhwan

**Comment by jn1119** [comment]
Hi @virgo81net 

The patch that was recommended here worked for me and has been merged now. Did you import the latest updated Service Catalog product for EMR that would have reflected the latest template?

Thanks

**Comment by jn1119** [comment]
Fixed in PR https://github.com/awslabs/service-workbench-on-aws/pull/394
