### ISSUE TITLE
[Bug] Deploy using EC2 instance - nodejs 14 deploys but no CloudFormation stacks

### ISSUE THREAD

**Issue by dcloud9** [awslabs/service-workbench-on-aws#1234]
**Describe the bug**
Our use cases are as follows:
1. EC2 AMI: `amzn2-ami-kernel-5.10-hvm-*-x86_64-gp2`
2. Upgrade SWB from `v5.2.10` to `v6.1.0`
3. Fresh install/deploy SWB `v6.1.0`

Both cases deployed successfully using the steps as per SWB implementation [guide](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/service-workbench-on-aws-implementation-guide.pdf), but not with documented tools version. The tools version combination that deploys successfully and failed are as follows:

| Tools | OK | Failed | OK2 |
|--------|--------|--------|--------|
| golang | v1.17.2 | v1.17.2  | v1.17.2  |
| nvm-sh | v0.35.3 |  v0.35.3  | v0.35.3  |
| nodejs | v12.22.12 | 14.x, 16.x, 18.x | 14.x, 16.x |
| pnpm | v5.4.2 | 6.x, 7.x , 8.x | v5.x (latest) |
| serverless | v3.35.2 | v3.35.2 | v3.35.2 |
| hygen | 6.2.11 | 6.2.11 |  6.2.11 |

**To Reproduce**
1. Launch EC2 with supported/documented AMI as above.
2. Follow the Tools table above with the column OK version (successful with Cloudformation stacks)
3. Terminate the EC2 instance.
4. Launch EC2 with supported/documented AMI as above.
5. Follow the Tools table above with the column FAILED versions (successful but without CloudFormation stacks)
6. Terminate the EC2 instance.
4. Repeat 4 until all FAILED versions completed.

**Expected behavior**
1. We expect the ones with FAILED versions to be **successful and with CloudFormation stacks**
2. It'll be helpful if there's a matrix of versions tested somewhere in the `README` or `Implementation Guide`.

**Screenshots**
* For **OK** versions, we're getting the usual and proper Successful 
```
Deployed website UI successfully
----- ENVIRONMENT DEPLOYED SUCCESSFULLY 🎉 -----
-------------------------------------------------------------------------
Summary:
-------------------------------------------------------------------------
Env Name                           : dev3
Solution                           : swb-dop
Website URL                        : https://devops-dev3.trei.iavi.org
API Endpoint                       : https://<redacted>.execute-api.eu-west-2.amazonaws.com/dev3
Temporary Native Pool Password     : execute aws ssm get-parameters --names /dev3/swb-dop/user/native/admin/password --output text --region eu-west-2 --with-decryption --query Parameters[0].Value
```

* For **FAILED** versions, we're only getting Successful without the Summary
```
Deployed website UI successfully
----- ENVIRONMENT DEPLOYED SUCCESSFULLY 🎉 -----
```

**Versions (please complete the following information):**
 - Release Version installed: `v6.1.0`
 - Is the deployment from a forked version of the repository?: `NO`

**Additional context**
Reference matrix for nodejs and pnpm versions [here](https://pnpm.io/installation#compatibility)

**Comment by rangfeli** [comment]
Hi @dcloud9, for Service Workbench, pnpm v5 is supported, however newer versions of pnpm greater than v5 are not supported and result in the improper Success message. We recommend using the latest version of pnpm v5 for a successful deployment.

As well, regarding the Node version, Node 16 and 14 are supported for Service Workbench.

The versions of the other tools mentioned should work as expected.

**Comment by dcloud9** [comment]
> Hi @dcloud9, for Service Workbench, pnpm v5 is supported, however newer versions of pnpm greater than v5 are not supported and result in the improper Success message. We recommend using the latest version of pnpm v5 for a successful deployment.
> 
> As well, regarding the Node version, Node 16 and 14 are supported for Service Workbench.
> 
> The versions of the other tools mentioned should work as expected.

Updated the table with **OK2** column, tested both on install and upgrade use cases.
| Tools | OK | Failed | OK2 |
|--------|--------|--------|--------|
| golang | v1.17.2 | v1.17.2  | v1.17.2  |
| nvm-sh | v0.35.3 |  v0.35.3  | v0.35.3  |
| nodejs | v12.22.12 | 14.x, 16.x, 18.x | 14.x, 16.x |
| pnpm | v5.4.2 | 6.x, 7.x , 8.x | v5.x (latest) |
| serverless | v3.35.2 | v3.35.2 | v3.35.2 |
| hygen | 6.2.11 | 6.2.11 |  6.2.11 |

**Comment by rangfeli** [comment]
Thank you for making us aware of this and we're glad to see you are having successful deployments for Service Workbench using the supported versions of the tools.

If you face any other issues regarding your deployments, be sure to let us know!
