### ISSUE TITLE
if domainname is not configured, could not make and use RStudio workspaces.

### ISSUE THREAD

**Issue by ghost** [awslabs/service-workbench-on-aws#124]
This is just a suggestion for a feature you would like to make it.

In case of  no domainname configured, should provide alternative way to create and use RStudio workspaces.

Proposed solution

* nginx.conf should allow 80 connection like below example if cert.pem and cert.key are not provided.

```
  server {
    listen 80;

    add_header Referrer-Policy same-origin always;
    add_header X-Frame-Options DENY always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
    add_header Content-Security-Policy "default-src 'none'; connect-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self';" always;

    proxy_http_version 1.1;
    proxy_read_timeout 20d;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
      proxy_pass http://localhost:8787;
    }
  }

```

* in the service-workbench-on-aws console should provide 
  * endpoint url for RStudio login
  * username and password were set during bootstrapping (like ec2 windows)

* domainname should not be checked, to prevent failure of step function although cfn jobs is complete.

**Comment by rsmayda** [comment]
+1 thanks for the suggestion. We need to dive deeper here on implications of such a feature, specifically around security!

**Comment by SanketD92** [comment]
@inhwan-aws Thanks for bringing this up. We have created an issue in our backlog to investigate its security implications. 
Have you already tried these changes out on your environment?

**Comment by jol-ster** [comment]
I am closing this particular issue as there has not been response in some time.  I understand that the added work of configuring a domain adds a barrier to entry for using RStudio, and appreciate the idea, but the security implications of providing access would need significant developer collaboration with security, and this is not on our roadmap.
