### ISSUE TITLE
[Misc] Service Workbench Future?

### ISSUE THREAD

**Issue by spensireli** [awslabs/service-workbench-on-aws#1245]
**What's on your mind?**
Is service workbench going to be continued to be developed or will this be replaced by RES?

https://github.com/aws/res

**Comment by janeyuaws** [comment]
Hi spensireli, thanks for reaching out. Yes, Service Workbench on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. If you or your customers are new to this solution, we advise you to explore using [Research and Engineering Studio on AWS](https://aws.amazon.com/hpc/res/).

**Comment by janeyuaws** [comment]
Hi spensireli, Thank you for reaching out. Our team curates customer requests for fit with our solutions vision on a regular basis. Please watch this space for new
updates. If you require immediate assistance, please reach out to your AWS account team. Please note that
security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:aws-security@amazon.com).
