### ISSUE TITLE
Subnet Addition

### ISSUE THREAD

**Issue by krupeshd1** [awslabs/service-workbench-on-aws#1249]
Hello SWB Team,

We onboarded a compute account to SWB a while back and the initial-stack template deploys only one vpc/subnet - we need to create a bunch of our own standard products outside of SWB which we typically do on Service Catalog and then import into SWB. Some instances are not available in the AZ that the initial subnet was deployed. 

What is the right process to add additional subnets to that compute account so that we can provide the subnetid parameter a value to deploy to another AZ? Do we just update the intial-template that was provided during onboarding? Do it manually?

SWB Version: 5.2.7

Regards,
Krupesh

**Comment by rangfeli** [comment]
SWB by default does not give the flexibility to add additional subnets to the compute account without making code changes in the product's business logic. We have moved to maintenance mode and our support during maintenance is in the [Maintenance Notice](https://github.com/awslabs/service-workbench-on-aws?tab=readme-ov-file#maintenance-notice).

**Comment by krupeshd1** [comment]
Hey when did this move to maintenance mode? And was there any notification sent? 

Regards,
Krupesh
