### ISSUE TITLE
[Bug] typo in package name

### ISSUE THREAD

**Issue by nplse** [awslabs/service-workbench-on-aws#1252]
I think

addons/addon-base-workflow/packages/base-worklfow-steps

should be named

addons/addon-base-workflow/packages/base-workflow-steps

**Comment by SanketD92** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our
team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new
updates. If you require immediate assistance, please reach out to your AWS account team. Please note that
security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:aws-security@amazon.com).
