### ISSUE TITLE
[Feature Request] migrate AWS SDK for JavaScript v2 APIs to v3

### ISSUE THREAD

**Issue by trivikr** [awslabs/service-workbench-on-aws#1254]
**Is your feature request related to a problem? Please describe.**

AWS SDK for JavaScript v2 will enter maintenance mode on September 8, 2024 and reach end-of-support on September 8, 2025. For more information, check blog post at https://a.co/cUPnyil

The service-workbench-on-aws makes calls using AWS SDK for JavaScript v2 at many places
https://github.com/search?q=repo%3Aawslabs%2Fservice-workbench-on-aws+%22%27aws-sdk%27%22&type=code

**Describe the solution you'd like**
Migrate AWS SDK for JavaScript v2 APIs to v3.

**Comment by htztomic** [comment]
Hi, we are currently not accepting any feature request. For more details please refer to this message located here: https://github.com/awslabs/service-workbench-on-aws?tab=readme-ov-file#maintenance-notice.
