### ISSUE TITLE
Federation setup fails silently when Cognito domain can't be created

### ISSUE THREAD

**Issue by senorkrabs** [awslabs/service-workbench-on-aws#152]
Currently, the authentication handler creates a domain for the Cognito user pool using the format `[stagename]-[solutionname]` . Cognito domains are unique, so if the domain isn't available, the call fails silently and no Cognito domain is set. 

https://github.com/awslabs/service-workbench-on-aws/blob/670a3aa58c6108a19415f24c45b5c49ff453aaf1/addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provisioner-service.js#L421-L428

As a workaround, you can manually create the Cognito domain and then replace the domain in the `userPoolDomai`n, `signInUri` , and `signOutUri` values in record associated with the user pool that is located in the DynamoDB table `DbAuthenticationProviderConfigs`

**Comment by rsmayda** [comment]
Thanks for the callout @senorkrabs. What is your use-case of having multiple `[stagename]-[solutionname]` Cognito User Pools? Or perhaps a better question is how did you get into this error state?

**Comment by senorkrabs** [comment]
We encountered this error state when using fairly generic strings for the stage and solution names (i.e. 'dev' and 'galileo'). If another AWS customer is already using a Cognito domain with the same name, the creation will fail. You can manually reproduce this issue by creating a User Pool in the console and trying to use a domain that has already been taken in that region:

![image](https://user-images.githubusercontent.com/46199514/92533019-97906a80-f1ff-11ea-854a-538020cde705.png)

Here are some ideas on how to avoid this and/or enhance:
- Generate a random string and append it to the end of the domain name to avoid conflicts
- Allow user to specify the userPoolDomain in the stage config file and fail if it can't be created
- Expose userPoolDomain as a modifiable setting in the "Auth" are of the Service Workbench UI

**Comment by hatimkhan** [comment]
A possible solution is to add the account id as part of the cognito user pool domain.  We do something similar to the artifact bucket name. Tagging @dpandya for further input.

**Comment by rsmayda** [comment]
@senorkrabs Thanks for the information and possible solutions. We will prioritize this into our backlog and will keep you updated. In the meantime if you want to take a stab at this please feel free to add a PR 👍 .... Also awesome username: 🦀

**Comment by dpandya** [comment]
One possible solution would be to use `globalNamespace` setting that includes account id already as @hatimkhan  suggested. The `globalNamespace` is intended for naming resources that require globally unique names (such as S3 buckets, Cognito User Pool Domain etc).

Modify `configureUserPoolDomain` method of `addons/addon-base-rest-api/packages/services/lib/authentication-providers/built-in-providers/cogito-user-pool/provisioner-service.js`
```
    const globalNamespace = this.settings.get(settingKeys.globalNamespace);
    const userPoolDomain = providerConfig.userPoolDomain || globalNamespace;
    const params = {
      Domain: userPoolDomain,
      UserPoolId: userPoolId,
    };
```

Make sure to pass the setting to the post-deployment Lambda in `main/solution/post-deployment/config/infra/functions.yml`
```
 APP_GLOBAL_NAMESPACE: ${self:custom.settings.globalNamespace}
```

**Comment by senorkrabs** [comment]
Because the domain is used in the Cognito URL that end users go to and is publicly accessible, I think using  something other than the account ID would be ideal. I suspect customers would prefer a not to publicly expose their AWS account numbers to keep the account non-identifiable to outsiders.

**Comment by hatimkhan** [comment]
A possible solution is to take the global namespace as described by @dpandya  and just hash it and use the hashed value as the cognito user pool domain.

**Comment by SanketD92** [comment]
@hatimkhan @dpandya UserPoolDomain.Domain has a [limit](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooldomain.html) of 63 chars, so appending the globalNamespace or it's hash wouldn't work. Probably would need to be the account ID or a random string.

**Comment by dpandya** [comment]
Another option would be to just let the domain be passed via settings, this way customer can choose the name. Since this name is going to be publicly visible, it makes sense to explicitly choose it instead of deriving it based on some convention and making sure it stays globally unique. The code can throw exception if this setting is missing when configuring the Cognito AuthN Provider.

Something like this in the `addon-base-post-deployment/packages/base-post-deployment/lib/steps/add-auth-providers.js`
```
    const cognitoAuthProviderConfig = {
      title: this.settings.get(settingKeys.cognitoAuthNProviderTitle),
      userPoolName,
      clientName: `${envName}-${solutionName}-client`,
      userPoolDomain: this.settings.get(settingKeys.cognitoUserPoolDomainName),
      enableNativeUserPoolUsers,
      federatedIdentityProviders,
    };
```

**Comment by senorkrabs** [comment]
Thinking about this some more, would it be better to require that the Cognito User pool already exist and be configured to support federated identities, so that service workbench doesn't need to provision the Cognito user pool at all?  I'd prefer to specify an existing pool be supplied by the Service Workbench administrator, configurable via the service work bench frontend. Because federation setup is typically a one-time or infrequent process, good documentation and/or a CloudFormation template to help with the user pool/SAML setup could supplement this, and service workbench would no longer have to deal with it.

**Comment by SanketD92** [comment]
@senorkrabs The current intent is to have one user pool per customer deployment. As for your comment to use one Cognito user pool and share it across customer deployments, that approach would need to be investigated in the future to evaluate pros/cons against the current approach. (One immediate con would be the customer loses the automated creation of the user pool.)

For now, we will make the cognitoUserPoolDomainName configurable in the <stage>.yml file as @dpandya suggested to prevent running into this bug.

**Comment by Bingjiling** [comment]
BugFix ticket is created for sizing this week, will update here once we have it sized and planned.
