### ISSUE TITLE
Multi-Account Multi-Bucket Case Studies

### ISSUE THREAD

**Issue by spensireli** [awslabs/service-workbench-on-aws#154]
Currently all case studies are tied to a bucket in the account that Galileo was deployed. To take it to the next level for production grade studies should support multi-account/multi-bucket configurations. 

It would be desirable that when creating a new study it would create a new S3 bucket in the desired project account instead of the usage of subdirectories in the account Galileo is deployed. 

I think the functionality of "my study" and "organization study" is great and works as intended but just lacks the ability to be used in different accounts / buckets. I would also add in the ability to select if you want versioning enabled / disabled if this route is executed upon. 

A Few Reasons for this:
- More segregation from a security perspective. 
- Categorization of projects / data owners from an account level. 
- Cost calculation is able to be executed on a per-bucket basis. 
- Aligns with AWS best practices.

**Comment by rsmayda** [comment]
Thanks for the feedback, we are actively discussing the 'Bring your own bucket' (BYOB) 🍺 feature! Stay tuned

**Comment by rsmayda** [comment]
With the release of [v2.1.0](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v2.1.0) BYOB this can now be closed :tada:
