### ISSUE TITLE
Sagemaker Notebooks are accessible from any IP

### ISSUE THREAD

**Issue by Ludo171** [awslabs/service-workbench-on-aws#181]
#### Version of Service Workbench :
I figured this bug on a version of Service Workbench associated to commit 81c60ef537cb45b55dc701b7d0a0dfbfbb26c81c
I used the Sagemaker Notebook workspace type coming out-of-the-box from Service Workbench.

#### Description :
Even after specifying a CIDR block for a new Sagemaker notebook, the resulting Security Group has no inbound rule, and the sagemaker notebook is accessible from any IP.

#### Reproduce the bug :
- Go on the 'Workspace' tab and create a Sagemaker Notebook workspaces. Specify `<IP adress>/32` as CIDR block
- Launch the workspaces
--> Once it is deployed, assess that you can access it even when using a VPN (Use Duckduck Go web browser to change your IP for example)
--> On the AWS console, assess that the Security Group associated with the Sagemaker Notebook instance has no inbound rule

**Comment by nguyen102** [comment]
Thanks for letting us know about this Ludo. I was able to reproduce the bug. I'll write up a ticket for it, and will discuss with the team about prioritizing this ticket.

**Comment by rsmayda** [comment]
**NOTE:** With this new commit existing users will need to re-import the newest version for SageMaker workspace type to get the added CIDR benefit.
