### ISSUE TITLE
Stopped workspaces should appear in the 'Available' tab

### ISSUE THREAD

**Issue by Ludo171** [awslabs/service-workbench-on-aws#182]
#### [Suggestion - UI]

Now with the version of Service Workbench 81c60ef537cb45b55dc701b7d0a0dfbfbb26c81c , we are capable of stopping the workspaces.

Workspaces with status "STOPPED" are not handled by the filter available on top of the Workspaces List. They are only visible under the filter 'All'. Which becomes tough when we have many workspaces that have been terminated.

Could we make the Stopped workspaces appear in the filter 'Available' as well ?

**Comment by Bingjiling** [comment]
Hi Ludo, Thanks for the suggestion! This is a great call out. 

I'm wondering which would be more convenient for users, adding another filter for "STOPPED" workspaces or including "STOPPED" workspaces in the filter "Available"? Both should be a pretty quick update.

**Comment by mhebrard** [comment]
Run into this issue, 
I noticed that the "stopped" status is currently displayed in orange, 
That would make the "stopped" workspace fall into "pending" filter...
That would be quite convenient there.

**Comment by jol-ster** [comment]
Wanted to note that the Stopped status is now available as an additional filter option in the Workspaces screen as of this merge : https://github.com/awslabs/service-workbench-on-aws/pull/485

Thank you for the feedback.  Closing this issue.
