### ISSUE TITLE
Projects Tab - specifying project admins has no effect 

### ISSUE THREAD

**Issue by Ludo171** [awslabs/service-workbench-on-aws#183]
#### Description:
The specification of project administrators in the Projects tab does not seem to have any actual effect.
When I change the admins in a project's details. There is no effective change of permissions and the users details are unchanged.

#### Reproduce the bug :  
- On the 'Users' tab, make sure you have one user (UserX) that has no permissions to launch workspaces for any project.
- Go to the 'Accounts/Projects' tab.
- For one of the projects (ProjectA), edit the details of the project and add UserX as admin of this project. Save.
--> Go back to the users' tab and assess that UserX's permissions have not been updated.
--> Login as UserX, go to the 'Workspaces' tab and assess that you cannot create workspaces for ProjectA.

**Comment by SanketD92** [comment]
That is correct. Currently, Project Admins is related to built-in workspaces only.
