### ISSUE TITLE
Federated users registered in advance cannot login

### ISSUE THREAD

**Issue by Ludo171** [awslabs/service-workbench-on-aws#184]
#### Description:
I figured that there is a NEW bug with Auth0, since I updated our version of Service Workbench. If I want to onboard new users on the application I have to wait for them to apply for getting access otherwise they are stuck in connection bugs. That is not practical.

If I register a new federated user in advance, then he/she gets 401 (Unauthorized) responses from Service Workbench API when they try to login.

#### Reproduce the bug : 
- Make sure your personal Google credentials available
- Make sure that there is no user already registered on Service Workbench with these credentials, otherwise delete it and we will recreate it for reproducing the bug.

- Connect as root user, or as another admin user and create a new federated user with your gmail adress.
![image](https://user-images.githubusercontent.com/33128425/96016864-8f080100-0e49-11eb-9bd3-54050aa80038.png)
- Make sure it has been created and that you activated the user right away
![image](https://user-images.githubusercontent.com/33128425/96016919-9f1fe080-0e49-11eb-8cdf-cad6479e5d79.png)
- Logout, and open a new private window on your browser. Try to login with your gmail credentials.
--> Assess that you get the following error.
![96017167-f1610180-0e49-11eb-81f1-19b7374724da](https://user-images.githubusercontent.com/33128425/104323420-6fcf4d00-54e6-11eb-8836-20b8d9e454f6.png)

To make the user access work again:
- You must delete the user whose connection is buggy. (From another admin user or from the root user)
- Then use his/her gmail credentials to apply for access to the platform. 
- Accept the application with another admin user or the root user
--> Assess that you are now able to connect with the new federated user.

**Comment by nguyen102** [comment]
Hi Ludo, we're currently trying to prioritize this issue in relationship to the other tasks/issues for SWB. To help us prioritize, can you give us a rough idea of how many users are affected by this workflow? 

In your typical workflow, do you normally register federated users or do user normally request for access to the platform first?

**Comment by Ludo171** [comment]
As Service Workbench is not well know (yet) internally, the most frequent scenario is :
- We evoke Service Workbench during a meeting. Say that it can be relevant for providing computing environments.
- Then

**Comment by nguyen102** [comment]
Thanks for your response Ludo. In that case we will prioritize the other issues first. I'll make a note of this issue in our backlog though.

**Comment by servicetest** [comment]
@Ludo171 - In your logout screenshot above have you accidently exposed your API key?  (far bottom right eyJra...)

**Comment by rsmayda** [comment]
@servicetest - It appears that is it just a partial access_token, not a full. Also access_token's typically have a time to live, where they expire!

But Ludo feel free to confirm

**Comment by Ludo171** [comment]
> @Ludo171 - In your logout screenshot above have you accidently exposed your API key? (far bottom right eyJra...)

Hi, @servicetest @rsmayda
Thanks for mentioning it !
As I was using a temporary test version of Service Workbench (authentication included), I did not take care of erasing it.  (+ it expires 1 hour afterwards). 
But I must admit it is not a good practice, so I corrected the picture.

Thanks.

**Comment by simranmakwana** [comment]
This has been corrected in SWB 5.0.0
