### ISSUE TITLE
Enable admins to change CIDR block of a workspace

### ISSUE THREAD

**Issue by Ludo171** [awslabs/service-workbench-on-aws#187]
#### [Feature Suggestion]

Yesterday we felt in a situation that would have been solved by this suggested feature. 
Some user was working on a workspace. After the workspace had been stopped, he left it alone for several days. One of our admins wanted to check the content of the workspace before terminating it, but the CIDR block only pointed to the original creator's IP. The admin had no way of accessing the workspace.

It would benefit multiple use-cases :
- Handle IP change for one user (changing internet provider, moving into a new house)
- Share access with additional users, by updating the IP.

As a work-around to those missing use-cases, we specify the CIDR block of our VPN. But for sharing with external users, it is enough.

(We would place this feature as a medium-priority feature)

**Comment by nguyen102** [comment]
Thanks for the suggestion Ludo. I've created a back log ticket for this. As we prioritize items, we will keep this request in mind.

**Comment by nguyen102** [comment]
I added a PR to fix this bug.

**Comment by nguyen102** [comment]
Changes have been merged

**Comment by nguyen102** [comment]
Sorry the PR linked here is incorrect. Please ignore that.

**Comment by carvantes** [comment]
This was fixed as part of https://github.com/awslabs/service-workbench-on-aws/pull/269
