### ISSUE TITLE
Old API Keys do not work after upgrade to v1.2.0

### ISSUE THREAD

**Issue by dpandya** [awslabs/service-workbench-on-aws#196]
**[Auth Bug]**

**Version of Service Workbench :** v1.2.0 (8744169e1eb6085e5af62900714452694fb10c6d)

**Description:** The API Keys generated prior to version v1.2.0 do not work post v1.2.0

**Workaround:** Revoke old API Key and generate new API Key. API Keys issued after updating to v1.2.0 work fine.

**Comment by rsmayda** [comment]
Resolving, fix is to manually update Service Workbench -- if you have a similar issue please let us know
