### ISSUE TITLE
Enable researchers to be assigned project-admin permission

### ISSUE THREAD

**Issue by Ludo171** [awslabs/service-workbench-on-aws#221]
**[Feature Suggestion - User Permission ProjectAdmin]**
---
So far, on the app of Service Workbench, a workspace is only visible by the user who deployed it and by the administrators.
The user rights rely on the user statuses (`userRoles`) :
- If a user is `admin` he can see all the workspaces, else he can only see his/her own workspaces
- If a user has been assigned to `projects` (in the users tab), he/she can deploy new workspaces on the associated AWS account
There is no way for other people than full-admins to manage workspaces for a specific project.

**Feature Description :**
We propose to reintegrate the `Project-admin` permission that will allow administrators to delegate management rights to team leaders in a project-restricted scope (without having to set them as full admins). We propose the following behavior :
--> If a user is assigned a `Project-admin` permission (in the Accounts tab), he/she can see and manage all workspaces belonging to this project.
--> This feature was implemented in a previous prototype of SWB (Pufferfish) and consists of integrating the `ProjectAdmins` attribute in the logic of the application. The attribute ProjectAdmins attribute is already saved in the `Projects` table and is modifiable from the Accounts tab of the application. But it has no effect yet.

**Benefits :**
This feature aims to make SWB manageable with multiple projects, and multiple AWS accounts by allowing admins to delegate management permissions to team leaders without granting full-admin rights.

**Comment by rsmayda** [comment]
Hey Ludo, thanks for bringing this up -- we can add this to our future back-log. If anyone from our community would like to take this task on please let us know, we can provide guidance and PR support 🚀

**Comment by kpark277** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.

**Comment by tdmalone** [comment]
Hi @kpark277, given you've added the closing-soon-if-no-response tag do we need to respond to this message on the issues you've posted it on to keep the feature request alive? Thanks.
