### ISSUE TITLE
[Feature Request] Project Admins

### ISSUE THREAD

**Issue by Ludo171** [awslabs/service-workbench-on-aws#222]
**[Feature Suggestion - User Permission Workspace Contributor]**
---
So far, on the app of Service Workbench, a workspace is only accessible by its creator and by admins. (provided that IPs are allowed by the security configuration)
Our research group faces many use-cases that would require multiple users to have access to a workspace :
- [Teaching] : teaching assistants need to access the workspaces of their students
- [Research] : research projects often involve multiple investigators that would benefit from sharing access to collaborative workspaces.

**Feature Description :**
We propose to enable workspace owners (and project administrators ?) to specify a list of users who can access their workspace from the 'Details' tab.

**Benefits :**
This feature aims to make the workspaces of Service Workbench meet the need for collaboration in academic projects.

**Comment by rsmayda** [comment]
Hey Ludo, thanks for bringing this up -- we can add this to our future back-log. If anyone from our community would like to take this task on please let us know, we can provide guidance and PR support 🚀

**Comment by tdmalone** [comment]
Relates to https://github.com/awslabs/service-workbench-on-aws/issues/733

**Comment by kpark277** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.

**Comment by tdmalone** [comment]
Adding response so this doesn't get closed
