### ISSUE TITLE
Enable researchers to change CIDR block of their workspace

### ISSUE THREAD

**Issue by avillach** [awslabs/service-workbench-on-aws#223]
Hi, related to issue #187 we need also to enable researchers to change CIDR block of their workspace and not just admins
https://github.com/awslabs/service-workbench-on-aws/issues/187
Because Public IP address changes when someone restarts it's modem connection and won't be able to connect anymore to his work

**Comment by rsmayda** [comment]
Thanks for calling this out Paul! As of right now we do not have that functionality in the UI but a workaround is you can change the CIDR manually in the AWS Account. We will add this additional context to our backlog

**Comment by carvantes** [comment]
This feature was added as part of https://github.com/awslabs/service-workbench-on-aws/pull/269
