### ISSUE TITLE
Study data should be stored in the AWS sub account of their project

### ISSUE THREAD

**Issue by avillach** [awslabs/service-workbench-on-aws#224]
if all study data is stored on Main account it defeats the all purpose of having subaccounts for billing, compliance, etc...

**Comment by rsmayda** [comment]
Maybe to unpack this a little bit. You are requesting study data to **always** be stored in the AWS sub account of their project? Or the ability to put the study data in sub accounts?

Study data and Projects are currently independent in service workbench. If study data is put in a sub account, then it’ll only be accessible from projects within that sub account. Changing the current functionality that there is only organizational study data.

**Comment by avillach** [comment]
Hi, it would depends on the type of users
For most users YES I would like to enforce that the study data MUST stay in the same sub account as the project
For some advance users then I would be ok to leave them the choice. 
In biomedical research when we handle patient data we must control where data is stored.   Today all data is stored in Master account and that's not ok. I know that you are working right now on enabeling to bring your own bucket. how will this work?
Thanks!

**Comment by SanketD92** [comment]
Hi Paul, for bring you own bucket, the admin would be able to add any AWS account (aka. data source account) which contains the study files/folders in S3 bucket(s). A CfN template would be generated for the data source account owner to create a Cloudformation stack with (this allows SWB to access buckets and studies in that account). Once the stack creation is completed, the data source account and studies would be displayed with their reachability status.

For a quick first glimpse, please take a look at the screenshots in this [PR](https://github.com/awslabs/service-workbench-on-aws/pull/246) description.

**Comment by rsmayda** [comment]
Hey Paul, would the bring you own bucket feature resolve your concern?

**Comment by avillach** [comment]
I hope! Let's see when it's released! March 8th, right? Thanks

**Comment by rsmayda** [comment]
With the release 🚀 of BYOB [v2.1.0](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v2.1.0) this can now be resolved
