### ISSUE TITLE
README.md has dead link to aws-accounts-readme.md

### ISSUE THREAD

**Issue by ericweinberg** [awslabs/service-workbench-on-aws#225]
Looks like there's a dead link in the readme. It's trying to go to main/documentation/aws-accounts-readme.md which has been removed.

**Comment by rsmayda** [comment]
Thanks for calling this out looking into it now

**Comment by rsmayda** [comment]
Looks like it was removed a long time ago: https://github.com/awslabs/service-workbench-on-aws/commit/1f0c095f78f765a05f29a4a9554603dcdf842b66#diff-0d6e4079e36703ebd37c00722f5891d28b0e2811dc114b129215123adcce3605
