### ISSUE TITLE
Cannot connect to freshly deployed RStudio workspaces

### ISSUE THREAD

**Issue by Ludo171** [awslabs/service-workbench-on-aws#239]
#### Description:
NON SYSTEMATIC BUG... probably a matter of timing ?
For some RStudio workspaces (using the same AMI and configuration), when we try to connect to a freshly deployed RStudio workspace, we get a red card saying 'Something went wrong'.
From CloudWatch ApiHandler logs :
```
'Parameter not found' error is raised at line 206 of
addons\addon-base-raas\packages\base-raas-services\lib\environment\service-catalog\environment-sc-connection-service.js
```

#### Outcomes of my investigation:
As suggested by the error logs, a ssm parameter is missing in the store : `/rstudio/publickey/sc-environments/ec2-instance/${instanceId}` should be created at every boot thanks to 
**the crontab line 38 in [main\solution\machine-images\config\infra\provisioners\provision-rstudio.sh](main\solution\machine-images\config\infra\provisioners\provision-rstudio.sh)**
But it does not seem to be executed (or fails) at the first boot of the workspace, thereby entails a connection error.
Another hint pointing toward this bug is that Stopping a buggy workspace and restarting it by hand (by clicking on the buttons on the Service Workbench app) solves the connection issue.

**Comment by SanketD92** [comment]
Thanks for bringing this issue (and the workaround) to our notice, Ludo! 

I've opened a ticket in our backlog to implement and test a fix. Since the `set-password` script is responsible for creating and storing the SSM parameter and rerunning the script is completely harmless, I believe the fix could mean adding this script in the UserData script of the RStudio CfN template.

**Comment by SanketD92** [comment]
Hello @Ludo171, it's been a while since we worked on the fix. I just wanted to make sure that the bug no longer exists for you.
