### ISSUE TITLE
Support for OpenID authorization

### ISSUE THREAD

**Issue by zaro0508** [awslabs/service-workbench-on-aws#295]
Is there a way to setup login access to the SC workbench with an OpenID (OIDC) provider?  If so are there instructions for setting that up?

**Comment by carvantes** [comment]
Hi, at this moment only the SAML protocol is supported. OIDC is not supported right now.

Some IDPs support multiple protocols, so maybe you find the SAML docs useful. The instructions and an example oh how to set up SAML for Auth0 can be found here: https://github.com/awslabs/service-workbench-on-aws/blob/master/docs/docs/deployment/configuration/auth/configuring_auth0.md

Please follow the instructions on https://github.com/awslabs/service-workbench-on-aws/tree/master/docs to render the docs.
