### ISSUE TITLE
cannot start local development, local web page fails to load

### ISSUE THREAD

**Issue by zaro0508** [awslabs/service-workbench-on-aws#297]
I have deployed the SC workbench and everything seems to be working as expected.  I can access the website, login and navigate around without problems.  When I tried to setup local development as instructed by the docs it doesn't seem to work.  The website at `localhost:300` and `<local IP address>:3000` fails to load.  I keep getting a spinner that says [just one second](https://pasteboard.co/JNAQKKZ.png)
 
➜ node --version
v15.5.1

➜ pnpm --version
5.17.1

➜ go version
go version go1.12.9 darwin/amd64

<details>
<summary>pnpx sls offline -s dev</summary>
➜  backend git:(1977d2c) ✗ pnpx sls offline -s dev

Serverless: Bundling with Webpack...
Time: 1596ms
Built at: 02/09/2021 9:32:16 AM
                                                  Asset      Size                                            Chunks                   Chunk Names
                     src/lambdas/api-handler/handler.js  24.6 KiB                   src/lambdas/api-handler/handler  [emitted]        src/lambdas/api-handler/handler
                 src/lambdas/api-handler/handler.js.map  6.12 KiB                   src/lambdas/api-handler/handler  [emitted] [dev]  src/lambdas/api-handler/handler
    src/lambdas/authentication-layer-handler/handler.js  18.2 KiB  src/lambdas/authentication-layer-handler/handler  [emitted]        src/lambdas/authentication-layer-handler/handler
src/lambdas/authentication-layer-handler/handler.js.map   7.5 KiB  src/lambdas/authentication-layer-handler/handler  [emitted] [dev]  src/lambdas/authentication-layer-handler/handler
         src/lambdas/env-status-poll-handler/handler.js  15.7 KiB       src/lambdas/env-status-poll-handler/handler  [emitted]        src/lambdas/env-status-poll-handler/handler
     src/lambdas/env-status-poll-handler/handler.js.map  4.39 KiB       src/lambdas/env-status-poll-handler/handler  [emitted] [dev]  src/lambdas/env-status-poll-handler/handler
        src/lambdas/open-data-scrape-handler/handler.js  23.9 KiB      src/lambdas/open-data-scrape-handler/handler  [emitted]        src/lambdas/open-data-scrape-handler/handler
    src/lambdas/open-data-scrape-handler/handler.js.map  11.1 KiB      src/lambdas/open-data-scrape-handler/handler  [emitted] [dev]  src/lambdas/open-data-scrape-handler/handler
            src/lambdas/workflow-loop-runner/handler.js  19.8 KiB          src/lambdas/workflow-loop-runner/handler  [emitted]        src/lambdas/workflow-loop-runner/handler
        src/lambdas/workflow-loop-runner/handler.js.map  5.17 KiB          src/lambdas/workflow-loop-runner/handler  [emitted] [dev]  src/lambdas/workflow-loop-runner/handler
Entrypoint src/lambdas/authentication-layer-handler/handler = src/lambdas/authentication-layer-handler/handler.js src/lambdas/authentication-layer-handler/handler.js.map
Entrypoint src/lambdas/open-data-scrape-handler/handler = src/lambdas/open-data-scrape-handler/handler.js src/lambdas/open-data-scrape-handler/handler.js.map
Entrypoint src/lambdas/env-status-poll-handler/handler = src/lambdas/env-status-poll-handler/handler.js src/lambdas/env-status-poll-handler/handler.js.map
Entrypoint src/lambdas/api-handler/handler = src/lambdas/api-handler/handler.js src/lambdas/api-handler/handler.js.map
Entrypoint src/lambdas/workflow-loop-runner/handler = src/lambdas/workflow-loop-runner/handler.js src/lambdas/workflow-loop-runner/handler.js.map
[./src/lambdas/api-handler/handler.js] 2.28 KiB {src/lambdas/api-handler/handler} [built]
[./src/lambdas/api-handler/plugins/plugin-registry.js] 4.29 KiB {src/lambdas/api-handler/handler} [built]
[./src/lambdas/authentication-layer-handler/handler-impl.js] 2.47 KiB {src/lambdas/authentication-layer-handler/handler} [built]
[./src/lambdas/authentication-layer-handler/handler.js] 1.53 KiB {src/lambdas/authentication-layer-handler/handler} [built]
[./src/lambdas/authentication-layer-handler/plugins/plugin-registry.js] 1.67 KiB {src/lambdas/authentication-layer-handler/handler} [built]
[./src/lambdas/env-status-poll-handler/handler.js] 1.04 KiB {src/lambdas/env-status-poll-handler/handler} [built]
[./src/lambdas/env-status-poll-handler/plugins/plugin-registry.js] 3.01 KiB {src/lambdas/env-status-poll-handler/handler} [built]
[./src/lambdas/open-data-scrape-handler/handler-impl.js] 6.59 KiB {src/lambdas/open-data-scrape-handler/handler} [built]
[./src/lambdas/open-data-scrape-handler/handler.js] 1.5 KiB {src/lambdas/open-data-scrape-handler/handler} [built]
[./src/lambdas/open-data-scrape-handler/plugins/plugin-registry.js] 2.9 KiB {src/lambdas/open-data-scrape-handler/handler} [built]
[./src/lambdas/workflow-loop-runner/handler.js] 1.24 KiB {src/lambdas/workflow-loop-runner/handler} [built]
[./src/lambdas/workflow-loop-runner/plugins/plugin-registry.js] 4.03 KiB {src/lambdas/workflow-loop-runner/handler} [built]
[@aws-ee/base-api-handler-factory] external "@aws-ee/base-api-handler-factory" 42 bytes {src/lambdas/api-handler/handler} [built]
[@aws-ee/base-api-handler/lib/routes-registration-util] external "@aws-ee/base-api-handler/lib/routes-registration-util" 42 bytes {src/lambdas/api-handler/handler} [built]
[@aws-ee/base-services-container/lib/services-container] external "@aws-ee/base-services-container/lib/services-container" 42 bytes {src/lambdas/authentication-layer-handler/handler} {src/lambdas/open-data-scrape-handler/handler} {src/lambdas/env-status-poll-handler/handler} [built]
    + 34 hidden modules
Serverless: Watching for changes...
[backend-tools] "provider environment:
{
  APP_ENV_TYPE: 'dev',
  APP_ENV_NAME: 'dev',
  APP_AWS_REGION: 'us-east-1',
  APP_SOLUTION_NAME: 'sw',
  APP_DB_PREFIX: 'dev-va-sw',
  APP_AWS_PROFILE: '',
  APP_USE_AWS_PROFILE: '',
  IS_OFFLINE: 'true',
  APP_LOCAL_ROLE_AUTO_ADJUST_TRUST: 'true'
}

[backend-tools] "authenticationLayerHandler" Lambda environment:
{
  APP_ENV_TYPE: 'dev',
  APP_ENV_NAME: 'dev',
  APP_AWS_REGION: 'us-east-1',
  APP_SOLUTION_NAME: 'sw',
  APP_DB_PREFIX: 'dev-va-sw',
  APP_AWS_PROFILE: '',
  APP_USE_AWS_PROFILE: '',
  IS_OFFLINE: 'true',
  APP_LOCAL_ROLE_AUTO_ADJUST_TRUST: 'true',
  APP_PARAM_STORE_JWT_SECRET: '/dev/sw/jwt/secret',
  APP_JWT_OPTIONS: '{"algorithm":"HS256","expiresIn":"2 days"}',
  APP_LOCAL_ROLE_ARN: 'arn:aws:iam::XXXXXXXXX0123:role/dev-va-sw-backend-RoleAuthenticationLayerHandler-1LJRZ49EUOMF5'
}

[backend-tools] "apiHandler" Lambda environment:
{
  APP_ENV_TYPE: 'dev',
  APP_ENV_NAME: 'dev',
  APP_AWS_REGION: 'us-east-1',
  APP_SOLUTION_NAME: 'sw',
  APP_DB_PREFIX: 'dev-va-sw',
  APP_AWS_PROFILE: '',
  APP_USE_AWS_PROFILE: '',
  IS_OFFLINE: 'true',
  APP_LOCAL_ROLE_AUTO_ADJUST_TRUST: 'true',
  APP_HOSTED_ZONE_ID: 'NotSetAsCustomDomainDisabled',
  APP_DOMAIN_NAME: '',
  APP_WEBSITE_URL: 'https://xxxxxxxxx1abc.cloudfront.net',
  APP_CORS_ALLOW_LIST: '["https://xxxxxxxxx1abc.cloudfront.net"]',
  APP_CORS_ALLOW_LIST_LOCAL: '["http://localhost:3000"]',
  APP_PARAM_STORE_JWT_SECRET: '/dev/sw/jwt/secret',
  APP_JWT_OPTIONS: '{"algorithm":"HS256","expiresIn":"2 days"}',
  APP_SM_WORKFLOW: 'arn:aws:states:us-east-1:XXXXXXXXX0123:stateMachine:dev-va-sw-workflow',
  APP_PARAM_STORE_ROOT: 'dev/sw',
  APP_EC2_RSTUDIO_AMI_PREFIX: 'dev-va-sw-EC2-RSTUDIO-AMI',
  APP_EC2_LINUX_AMI_PREFIX: 'dev-va-sw-EC2-LINUX-AMI',
  APP_EC2_WINDOWS_AMI_PREFIX: 'dev-va-sw-EC2-WINDOWS-AMI',
  APP_EMR_AMI_PREFIX: 'dev-va-sw-EMR-AMI',
  APP_DB_STUDIES_CATEGORY_INDEX: 'CategoryIndex',
  APP_STUDY_DATA_BUCKET_NAME: 'XXXXXXXXX0123-dev-va-sw-studydata',
  APP_WORKFLOW_ROLE_ARN: 'arn:aws:iam::XXXXXXXXX0123:role/dev-va-sw-WorkflowLoopRunner',
  APP_API_HANDLER_ARN: 'arn:aws:iam::XXXXXXXXX0123:role/dev-va-sw-ApiHandler',
  APP_EXTERNAL_CFN_TEMPLATES_BUCKET_NAME: 'XXXXXXXXX0123-dev-va-sw-external-templates',
  APP_ENVIRONMENT_INSTANCE_FILES: 's3://XXXXXXXXX0123-dev-va-sw-environments-bootstrap-scripts/environment-files',
  APP_STUDY_DATA_KMS_KEY_ALIAS: 'XXXXXXXXX0123-dev-va-sw/s3/studydata',
  APP_STUDY_DATA_KMS_KEY_ARN: 'arn:aws:kms:us-east-1:XXXXXXXXX0123:alias/XXXXXXXXX0123-dev-va-sw/s3/studydata',
  APP_STUDY_DATA_KMS_POLICY_WORKSPACE_SID: 'Allow workspace environments to retrieve S3 objects',
  APP_ENV_MGMT_ROLE_ARN: 'arn:aws:iam::XXXXXXXXX0123:role/dev-va-sw-EnvMgmt',
  APP_LAUNCH_CONSTRAINT_ROLE_PREFIX: 'dev-va-sw-*',
  APP_LAUNCH_CONSTRAINT_POLICY_PREFIX: '*',
  APP_ENV_TYPE_CONFIGS_BUCKET_NAME: 'XXXXXXXXX0123-dev-va-sw-env-type-configs',
  APP_LOCAL_ROLE_ARN: 'arn:aws:iam::XXXXXXXXX0123:role/dev-va-sw-ApiHandler'
}

[backend-tools] "workflowLoopRunner" Lambda environment:
{
  APP_ENV_TYPE: 'dev',
  APP_ENV_NAME: 'dev',
  APP_AWS_REGION: 'us-east-1',
  APP_SOLUTION_NAME: 'sw',
  APP_DB_PREFIX: 'dev-va-sw',
  APP_AWS_PROFILE: '',
  APP_USE_AWS_PROFILE: '',
  IS_OFFLINE: 'true',
  APP_LOCAL_ROLE_AUTO_ADJUST_TRUST: 'true',
  APP_SM_WORKFLOW: 'arn:aws:states:us-east-1:XXXXXXXXX0123:stateMachine:dev-va-sw-workflow',
  APP_PARAM_STORE_ROOT: 'dev/sw',
  APP_PARAM_STORE_JWT_SECRET: '/dev/sw/jwt/secret',
  APP_JWT_OPTIONS: '{"algorithm":"HS256","expiresIn":"2 days"}',
  APP_DB_STUDIES_CATEGORY_INDEX: 'CategoryIndex',
  APP_STUDY_DATA_BUCKET_NAME: 'XXXXXXXXX0123-dev-va-sw-studydata',
  APP_ARTIFACTS_BUCKET_NAME: 'XXXXXXXXX0123-dev-va-sw-artifacts',
  APP_ENVIRONMENT_INSTANCE_FILES: 's3://XXXXXXXXX0123-dev-va-sw-environments-bootstrap-scripts/environment-files',
  APP_STUDY_DATA_KMS_KEY_ALIAS: 'XXXXXXXXX0123-dev-va-sw/s3/studydata',
  APP_STUDY_DATA_KMS_KEY_ARN: {
    'Fn::Sub': 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/XXXXXXXXX0123-dev-va-sw/s3/studydata'
  },
  APP_STUDY_DATA_KMS_POLICY_WORKSPACE_SID: 'Allow workspace environments to retrieve S3 objects',
  APP_ENV_MGMT_ROLE_ARN: 'arn:aws:iam::XXXXXXXXX0123:role/dev-va-sw-EnvMgmt',
  APP_LAUNCH_CONSTRAINT_ROLE_PREFIX: 'dev-va-sw-*',
  APP_LAUNCH_CONSTRAINT_POLICY_PREFIX: '*',
  APP_ENV_TYPE_CONFIGS_BUCKET_NAME: 'XXXXXXXXX0123-dev-va-sw-env-type-configs',
  APP_HOSTED_ZONE_ID: 'NotSetAsCustomDomainDisabled',
  APP_DOMAIN_NAME: '',
  APP_LOCAL_ROLE_ARN: 'arn:aws:iam::XXXXXXXXX0123:role/dev-va-sw-WorkflowLoopRunner'
}

[backend-tools] "openDataScrapeHandler" Lambda environment:
{
  APP_ENV_TYPE: 'dev',
  APP_ENV_NAME: 'dev',
  APP_AWS_REGION: 'us-east-1',
  APP_SOLUTION_NAME: 'sw',
  APP_DB_PREFIX: 'dev-va-sw',
  APP_AWS_PROFILE: '',
  APP_USE_AWS_PROFILE: '',
  IS_OFFLINE: 'true',
  APP_LOCAL_ROLE_AUTO_ADJUST_TRUST: 'true',
  APP_DB_STUDIES_CATEGORY_INDEX: 'CategoryIndex',
  APP_STUDY_DATA_BUCKET_NAME: 'XXXXXXXXX0123-dev-va-sw-studydata',
  APP_LOCAL_ROLE_ARN: 'arn:aws:iam::XXXXXXXXX0123:role/dev-va-sw-backend-RoleOpenDataScrapeHandler-1QU0O6MBMDKKS'
}

[backend-tools] "envStatusPollHandler" Lambda environment:
{
  APP_ENV_TYPE: 'dev',
  APP_ENV_NAME: 'dev',
  APP_AWS_REGION: 'us-east-1',
  APP_SOLUTION_NAME: 'sw',
  APP_DB_PREFIX: 'dev-va-sw',
  APP_AWS_PROFILE: '',
  APP_USE_AWS_PROFILE: '',
  IS_OFFLINE: 'true',
  APP_LOCAL_ROLE_AUTO_ADJUST_TRUST: 'true',
  APP_LOCAL_ROLE_ARN: 'arn:aws:iam::XXXXXXXXX0123:role/dev-va-sw-backend-RoleEnvStatusPollHandler-P8LOQG1JGDA'
}

Serverless: Starting Offline: dev/us-east-1.

Serverless: Routes for authenticationLayerHandler:
Serverless: POST /{apiVersion}/functions/va-sw-backend-dev-authenticationLayerHandler/invocations

Serverless: Routes for openDataScrapeHandler:
Serverless: POST /{apiVersion}/functions/va-sw-backend-dev-openDataScrapeHandler/invocations

Serverless: Routes for envStatusPollHandler:
Serverless: POST /{apiVersion}/functions/va-sw-backend-dev-envStatusPollHandler/invocations

Serverless: Routes for apiHandler:
Serverless: GET /api/authentication/public/provider/configs
Serverless: POST /api/authentication/id-tokens
Serverless: GET /api
Serverless: Configuring Authorization: /api authenticationLayerHandler
Serverless: GET /api/{proxy*}
Serverless: Configuring Authorization: /api/{proxy+} authenticationLayerHandler
Serverless: POST /api
Serverless: Configuring Authorization: /api authenticationLayerHandler
Serverless: POST /api/{proxy*}
Serverless: Configuring Authorization: /api/{proxy+} authenticationLayerHandler
Serverless: PUT /api
Serverless: Configuring Authorization: /api authenticationLayerHandler
Serverless: PUT /api/{proxy*}
Serverless: Configuring Authorization: /api/{proxy+} authenticationLayerHandler
Serverless: DELETE /api
Serverless: Configuring Authorization: /api authenticationLayerHandler
Serverless: DELETE /api/{proxy*}
Serverless: Configuring Authorization: /api/{proxy+} authenticationLayerHandler
Serverless: POST /{apiVersion}/functions/va-sw-backend-dev-apiHandler/invocations

Serverless: Routes for workflowLoopRunner:
Serverless: POST /{apiVersion}/functions/va-sw-backend-dev-workflowLoopRunner/invocations

Serverless: Offline [HTTP] listening on http://localhost:4000
Serverless: Enter "rp" to replay the last request
</details>

<details>
<summary>pnpx sls start-ui -s dev</summary>
➜  ui git:(1977d2c) ✗ pnpx sls start-ui -s dev

[serverless-ui-tools] Running "pnpm start"...
[serverless-ui-tools] >> pnpm run start

> @aws-ee/ui@0.1.0 start /Users/zaro0508/work-github/service-workbench-on-aws/main/solution/ui
> react-scripts start

ℹ ｢wds｣: Project is running at http://10.42.1.65/

ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /Users/zaro0508/work-github/service-workbench-on-aws/main/solution/ui/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...

Compiled successfully!

You can now view @aws-ee/ui in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://10.42.1.65:3000

Note that the development build is not optimized.
To create a production build, use npm run build.
</details>

**Comment by carvantes** [comment]
Hi, 
The commands you ran are correct and should be sufficient to run Service Workbench locally. To help narrow down the root cause please try the following:

1. Double check that `dev` matches the stage name that you already deployed.
1. Could you use the devtools in your browser to check if there are any errors on the javascript console or failed network requests?
1. After you open the page in your browser, do you see any errors on the terminal where you ran `pnpx sls offline -s dev`? That terminal logs api calls and can help debug

**Comment by zaro0508** [comment]
> 1. Double check that `dev` matches the stage name that you already deployed.

I'm not sure how to do that.  I did add the sls logs to this issue.  Is that info evident in one of the env vars in those logs? 

> 2. Could you use the devtools in your browser to check if there are any errors on the javascript console or failed network requests?

I don't see any obvious errors,  https://filebin.net/ogpwns6szi4j2xp4

> 3. After you open the page in your browser, do you see any errors on the terminal where you ran `pnpx sls offline -s dev`? That terminal logs api calls and can help debug

I've posted my terminal logs in the issue description.  I don't see any errors in the terminal logs either.

**Comment by carvantes** [comment]
From the screenshots, it looks like the `/configs` request is stuck in pending.

try running `curl 'http://localhost:4000/api/authentication/public/provider/configs`. If that works, then there may be something else specific to your browser that is preventing it from reaching localhost:4000
