### ISSUE TITLE
Enabling built-in workspaces support in v2

### ISSUE THREAD

**Issue by ian-mcqueen-ons** [awslabs/service-workbench-on-aws#300]
Having upgraded from 1.4.6 to 2.0.1 the built-in workspaces appear not to work.
In the .defaults.yml file it mentions that setting enableBuiltInWorkspaces = true won't be enough to get the built-in workspace support and to open an issue. We were using built-in workspaces and now get the error "Cannot GET /api/workspaces/built-in" to the Workspaces section.

**Comment by HennerD** [comment]
We have switched Service Workbench entirely to Service Catalog support for the enhanced capabilities and flexibility of Service Catalog. We were not aware of the current use of the built-in workspaces in your environment. While we will focus on the Service Catalog support going forward, we can provide guidance on how to reverse the change that removed the built-in support from the code base. In the future we recommend using service catalog support instead but we would also like to understand more the current use of the built-in functionality to evaluate its continued value. Do you mind helping me understand the use case that you are covering with the built-in workspaces? Thank you
