### ISSUE TITLE
account structure doc references non-existentt file

### ISSUE THREAD

**Issue by zaro0508** [awslabs/service-workbench-on-aws#311]
the account structure doc (at http://localhost:3000/deployment/post_deployment/account_structure after running yarn start)  contains reference to `main/documentation/aws-accounts-readme.md` however i don't see that doc anywhere?

**Comment by nguyen102** [comment]
I'm sorry about that. It looks like that file doesn't exist. I added a PR to remove this broken link. PR 318

**Comment by nguyen102** [comment]
PR merged
https://github.com/awslabs/service-workbench-on-aws/pull/318
