### ISSUE TITLE
how to remove accounts?

### ISSUE THREAD

**Issue by zaro0508** [awslabs/service-workbench-on-aws#321]
I have installed a fresh SC workbench (from master branch). I can login and browse around. I can add an existing AWS account, setup an index, setup a project, associate it with an index and assign a project admin user to it.  I've realized I've configured some things for the account incorrectly or want to re-setup the account, index and project however I don't see a way to delete the account that I've setup.  Is there a way to remove existing AWS accounts from the workbench?

➜ node --version
v15.5.1
➜ pnpm --version
5.17.1

**Comment by nguyen102** [comment]
There is currently no way to delete an AWS account through the SWB UI. You could manually delete the account in DDB, but that would require traversing through many tables to delete all the dependencies and is error prone. 

Let me know if you would still like to delete the account, and I can look into it and provide further instructions.

**Comment by zaro0508** [comment]
@nguyen102 issue #302 made me realize that i have to redo the account setup.  Looks like there is also no way to edit the configurations for an added account either?  Assuming I want to use that (incorrectly) configured account, Is my only recourse to completely uninstall the SC workbench and start over?

**Comment by nguyen102** [comment]
If you're just looking to edit some config value for the account, for example, the role arn, you can edit the value in DDB. Go to `DDB` and then look for the table `<stage>-<region>-<solution-name>-Accounts`. Look for the account you would like to edit and make the changes there.

```
{
  "accountArn": "arn:aws:organizations::<main-account-number>:account/<member-account-number>",
  "accountName": "abc",
  "cfnInfo": {
    "crossAccountEnvMgmtRoleArn": "arn:aws:iam::<member-account-number>:role/initial-stack-1602533842782-xacc-env-mgmt",
    "crossAccountExecutionRoleArn": "arn:aws:iam::<member-account-number>:role/initial-stack-1602533842782-cross-account-role",
    "encryptionKeyArn": "arn:aws:kms:us-east-2:<member-account-number>:key/abc",
    "stackId": "arn:aws:cloudformation:us-east-2:<member-account-number>:stack/initial-stack-1602533842782/abc",
    "subnetId": "subnet-abc",
    "vpcId": "vpc-abc"
  },
  "createdAt": "2020-10-12T20:12:21.876Z",
  "createdBy": "abc",
  "email": "abc@xyz.com",
  "id": "xyz",
  "rev": 0,
  "stackId": "arn:aws:cloudformation:us-east-2:<account-number>:stack/initial-stack-1602533842782/abc",
  "status": "COMPLETED",
  "updatedAt": "2020-10-12T20:19:47.758Z",
  "updatedBy": "abc"
}
```
