### ISSUE TITLE
Adding more than 4 studies to a Windows Sever 2019 VM produces an error

### ISSUE THREAD

**Issue by servicetest** [awslabs/service-workbench-on-aws#374]
Adding more than 4 studies to a Windows Server 2019 virtual machine produces an error

When adding 5+ studies I get the following

"1 validation error detected: Value at 'provisingParameters.7.member.value' failed to satisfy constraint: Member must have length less than or equal to 4096."

Is this a simple fix?

**Comment by nguyen102** [comment]
Hi,

I'm thinking this error might be a result of the selected studies causing the IAM Policy document to exceed the maximum 4096 character limit. 

In my testing I was able to launch a Windows workspace with these 5 Open Studies

Medical Segmentation Decathlon
Human PanGenomics Project
Nanopore Reference Human Genome
COVID-19 Molecular Structure and Therapeutics Hub
MIMIC-III (‘Medical Information Mart for Intensive Care’)

Can you try launching a Windows workspace with these 5 studies?

Also to confirm, that this isn't a Window specific issue, can you try launch a Sagemaker workspace with more than 4 studies?

**Comment by servicetest** [comment]
Thank you @nguyen102,

After working the problem I have discovered this is actually a problem with our fork.

Spinning up 8 studies in a Windows VM in the main code version appears to spin up without-error.
