### ISSUE TITLE
Module not found:  '@aws-ee/base-raas-cfn-templates/dist/plugins/cfn-templates-plugin'

### ISSUE THREAD

**Issue by ashaman25** [awslabs/service-workbench-on-aws#429]
ERROR in ./src/lambdas/open-data-scrape-handler/plugins/plugin-registry.js
Module not found: Error: Can't resolve '@aws-ee/base-raas-cfn-templates/dist/plugins/cfn-templates-plugin' in 'service-workbench-on-aws/main/solution/backend/src/lambdas/open-data-scrape-handler/plugins'
 @ ./src/lambdas/open-data-scrape-handler/plugins/plugin-registry.js 27:35-111
 @ ./src/lambdas/open-data-scrape-handler/handler.js

I have pulled the latest files but i am struggling to deploy the environment.

scripts/environment-deploy.sh

I have created a new template file with project specific variables, but when it gets to bundling with WebPack, the script stops with the error above. 

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.16.0
     Framework Version:         1.67.3
     Plugin Version:            3.6.6
     SDK Version:               2.3.0
     Components Version:        2.29.0

**Comment by angelosnm** [comment]
Has the issue been resolved? and how?

**Comment by tdmalone** [comment]
ditto ^ @ashaman25 Did you resolve this issue? I'm getting the exact same error with a fresh deployment of v5.0.0.

**Comment by tdmalone** [comment]
Actually - found the fix, in my case at least - I was running as `root`. Unsure why that means the dependency couldn't be found, but... 🤷 

found via https://github.com/awslabs/service-workbench-on-aws/issues/565#issuecomment-877999044
