### ISSUE TITLE
Edit Workspace Type - error on submit

### ISSUE THREAD

**Issue by digitalrager** [awslabs/service-workbench-on-aws#439]
I just released the v2.1.5 tag to our staging environment and am unable to create or save updates to existing Workspace Types.  I receive a generic error:

We have a problem!
Input has validation errors

The update I attempted, from an existing Workspace Type which has apparently passed validation before, was to change a word in the description, which I wouldn't expect to create a new validation error.  So something else appears to be out of sync. 

I am also unclear where to find the log with a more specific error, but am happy to retrieve it with more direction.

Currently the simplest way to reproduce the bug is to select Edit for an existing Workspace Type and then submit Save Workspace Type, however creating a new type also trips the error. 

Thanks for the attention.

**Comment by dpandya** [comment]
One such validation issue happens when Workspace Type Config Name has spaces.

**Comment by digitalrager** [comment]
Yes - I was able to confirm the Workspace Type Config Name passes if spaces are removed.  

Apparently a second issue is that I cannot use variables in the Tag values in workspace configurations.  We pass the ${indexId} through as a cost allocation tag, and for new configurations I can no longer add this, and existing configurations will not update unless I remove the tag.  Looks like it is the brackets tripping validation errors.

**Comment by Bingjiling** [comment]
Hi, thanks for reaching out! We're looking into the fix of this data validation issue, will update here once we have a PR out for the fix.

**Comment by nguyen102** [comment]
PR for this issue has been merged. Closing this ticket.
