### ISSUE TITLE
Missing tags for releases

### ISSUE THREAD

**Issue by bollig** [awslabs/service-workbench-on-aws#447]
Please add tags for releases to the git repo.

**Comment by bollig** [comment]
I see. 2.2.0 is actually tagged, but its inconsistent with scheme used for previous tags (e.g., "v2.1.5")

**Comment by Bingjiling** [comment]
Thanks for the call out @bollig, we'll update the tag to follow the same schema.

**Comment by Bingjiling** [comment]
Hi @bollig, the tag is updated to v2.2.0, you should be able to get the update with `git pull --prune --tags`. Thanks for the call out!
