### ISSUE TITLE
Create Stack should target /stacks/create/review

### ISSUE THREAD

**Issue by bollig** [awslabs/service-workbench-on-aws#448]
https://github.com/awslabs/service-workbench-on-aws/blob/4b5928ebbbd837d2e20781a213c2fcb630fbdd95/addons/addon-base-raas-ui/packages/base-raas-ui/src/parts/data-sources/parts/AccountCfnPanel.js#L181

When launching Create Stack, switch the link to "/stacks/create/review" as opposed to "/stacks/new". E.g., 
```
https://$REGION.console.aws.amazon.com/cloudformation/home?region=$REGION#/stacks/create/review?stackName=studyName&templateURL=https://s3.amazonaws.com/solutions-reference/solution.template 
```
. This will reduce required click-through traffic to register a study by two or more clicks and page refreshes.

**Comment by bollig** [comment]
see: https://github.com/awslabs/service-workbench-on-aws/blob/4b5928ebbbd837d2e20781a213c2fcb630fbdd95/addons/addon-base-raas/packages/base-raas-services/lib/data-source/data-source-registration-service.js#L34

**Comment by hatimkhan** [comment]
A quick note here.  ~~If you use `/stacks/create/review`, the user must visit the cloudFormation console first before clicking on the link.  For example, if you logout from all the AWS console sessions, and then log in to the AWS console (but don't go to the Cloudformation console), and try to use the /stacks/create/review link, the operation will fail when you go the last step~~

If we do `/stacks/create/review`, the admin loses the ability to specify tags, notification options and termination protections.  Some organizations might need the ability to add tags when creating the cloudFormation stack.

![cfn](https://user-images.githubusercontent.com/589501/115295313-9b865280-a127-11eb-8fb5-aca88397a196.png)

**Comment by nguyen102** [comment]
After discussing this with the dev team, we've decided to keep the original CloudFormation URL. Even though this means the user will have to click through more screens to create the stack, we believe this is in the best interest of the customer. From a customer awareness and security perspective it allows the user to more carefully examine the resources that the CF stack is creating. It also allows the user to customize settings on the CF stack.

Thanks for bringing this idea to our attention though. We really appreciate your initiative to help.
