### ISSUE TITLE
Deployment flow clarification

### ISSUE THREAD

**Issue by mhebrard** [awslabs/service-workbench-on-aws#455]
Hi.

I am deploying the SWB v3.0.0. I follow the [README](https://github.com/awslabs/service-workbench-on-aws#linking-an-existing-aws-account): clone the repo, create a new config file, run environment-deploy.sh, run master-account-deploy.sh...

At that stage I am able to log into SWB with root user and create a new admin user.
Next step would be to add an AWS account. 
Here some info are missing. 

* Account Name: I choose a name
* AWS Account ID: my account ID
* Role ARN: found in the output of master-account-deploy.sh
* AWS Service Catalog Role ARN: found in the output of master-account-deploy.sh
* External ID: `workspace` I presume
* Desciption: I put a description
* VPC ID: **??**
* Subnet  ID: **??**
* KMS Encryption Key ARN: **??**

On a previous installation, I had to manually create a CloudFormation stack using `onboard-account.cfn.yml` that provided me with the info about the VPN, Subnet and Encryption Key, but I do not see any mention of that step in the current readme. Is there a better way to gather the info ? like another `scripts/...-deploy.sh` to run ?

**Comment by nguyen102** [comment]
Hi, 

You can follow the instructions here for adding you account. The instructions here should be more detailed. And yep, you're right, you'll still need to deploy a CF template in the account you want to add.

https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/docs/deployment/post_deployment/aws_accounts.md

**Comment by mhebrard** [comment]
That was very usefull.

If I understand well, following the step "Add AWS Account" is tailored to add the account on which SWB is deployed as a billing account. The current process is a bit involving with the need to run a script + manually launch a cloudFormation + gather the outputs to finally enter the info in SWB. I wonder if the process could be integrated in the initial deployment of SWB as it is directly link to the deployment account.
> make the onboarding stack part of the auto-deployment and the usefull outputs part of the prompt at the end of deployment

Also in that process it is not needed to run `scripts/master-account-deploy.sh <stage>` I wonder if the repo README could be clarify.

**Comment by nguyen102** [comment]
Hi Maxime,

The "Add AWS Account" is to allow you to add a preexisting AWS account to SWB. This new account called a Member account will be connected with your Main Account  so that you can deploy Workspaces on the member account.

More information about different account types here.
https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/docs/deployment/post_deployment/account_structure.md

Yep, you're right this process can be simplified. We currently have a backlog item to simplify this process, and will try to get to it soon.

Thanks for your feedback Maxime.

**Comment by carvantes** [comment]
I'm closing this now. Feel free to reopen if there are additional questions
