### ISSUE TITLE
EnvTypeCandidateService can fail to obtain any candidates if a SC product has no active versions

### ISSUE THREAD

**Issue by nathanroys** [awslabs/service-workbench-on-aws#461]
**File:** service-workbench-on-aws/addons/addon-environment-sc-api/packages/environment-type-mgmt-services/lib/environment-type/env-type-candidate-service.js
**Line:** 208

**Steps to reproduce:**

1. Create a service catalog product in your portfolio with a single, active version
2. Verify the version is shown as a candidate for import on the workspaces section
3. Make the product version inactive
4. Go back and refresh the workspaces page

**What should happen:**
The product version in question should be omitted, whilst all others are still shown.

**What actually happens:**
An error is thrown and no workspaces appear for import.

----

Before we index the array we should ensure that the array has at least one item.

**Comment by carvantes** [comment]
Hi, 

Thanks for the detailed bug report. I was able to reproduce the bug and I'll be fixing it shortly

**Comment by carvantes** [comment]
The fix has been merged: https://github.com/awslabs/service-workbench-on-aws/commit/3c561f4850faffe3ccc6fd0ffcc5b7065f53f3c6.

Please deploy the latest changes from `mainline` to get the fix
