### ISSUE TITLE
EMR - Hail - Access to studies

### ISSUE THREAD

**Issue by mhebrard** [awslabs/service-workbench-on-aws#462]
Hi, 

I deployed SWB v3.0.0
I am testing the workspace EMR shipped by default with SWB.
I am able to launch the EMR with "Genome Aggregation Database (gnomAD)" study linked to the workspace.
I am able to connect to the jupyter notebook, launch Hail, load and view the examples data

I am **not able to** load data from a study into hail
I can see the directories in jupyter (on the left side bar)
I can browse into the directories using shell (cd, ls...)
But when I try to read files into hail, I got errors:

```
ht = hl.read_table('studies/broad-gnomad/release/3.1.1/ht/genomes/gnomad.genomes.v3.1.1.sites.ht/')
```
> Error summary: HailException: MatrixTable and Table files are directories; path 'studies/broad-gnomad/release/3.1.1/ht/genomes/gnomad.genomes.v3.1.1.sites.ht/' is not a directory

```
mt = hl.import_vcf('studies/broad-gnomad/release/3.1.1/vcf/genomes/gnomad.genomes.v3.1.1.sites.chr21.vcf.bgz', reference_genome='GRCh38')
```
> Hail: WARN: 'studies/broad-gnomad/release/3.1.1/vcf/genomes/gnomad.genomes.v3.1.1.sites.chr21.vcf.bgz' refers to no files

Also, when I load example data from hail, that works but I do not see the data in my jupyter notebook. i.e. I do not know where the data are loaded.

```
hl.utils.get_1kg('data/')
mt = hl.read_matrix_table('data/1kg.mt/')
```

**Comment by carvantes** [comment]
Hi,

try using the full path to the files:
```py
ht = hl.read_table('file:///home/hadoop/studies/broad-gnomad/release/3.1.1/ht/genomes/gnomad.genomes.v3.1.1.sites.ht/')
mt = hl.import_vcf('file:///home/hadoop/studies/broad-gnomad/release/3.1.1/vcf/genomes/gnomad.genomes.v3.1.1.sites.chr21.vcf.bgz', reference_genome='GRCh38')
```
note that `studies` is a symlink to `/home/hadoop/studies`

```bash
[hadoop@ip-10-0-15-103 notebook]$ pwd
/opt/hail-on-AWS-spot-instances/notebook
[hadoop@ip-10-0-15-103 notebook]$ ls -l
total 160
-rwxrwxrwx 1 hadoop hadoop 25982 Apr 29 16:13 GWAS_tutorial_with_HMS_additions.ipynb
-rw-r--r-- 1 hadoop hadoop 91672 Apr 29 21:02 hail-20210429-2043-0.2.53-8140f17d9262.log
-rwxrwxrwx 1 hadoop hadoop 35807 Apr 29 16:13 plotting.py
lrwxrwxrwx 1 root   root      20 Apr 29 20:41 studies -> /home/hadoop/studies
```

Unfortunately, your `read_table` command may fail (depending on how recently you build your EMR image) with:
```
Error summary: HailException: incompatible file format when reading: file:///home/hadoop/studies/broad-gnomad/release/3.1.1/ht/genomes/gnomad.genomes.v3.1.1.sites.ht/
  supported version: 1.4.0, found 1.5.0
```

Older gnomAD releases such as `3.0` work fine:
```py
ht = hl.read_table('file:///home/hadoop/studies/broad-gnomad/release/3.0/ht/genomes/gnomad.genomes.r3.0.sites.ht/')
```

**Comment by carvantes** [comment]
Closing this issue now. Feel free to reopen if you have further questions
