### ISSUE TITLE
Validation Errors on Add Configuration give no details an all data entered is lost.

### ISSUE THREAD

**Issue by primerano** [awslabs/service-workbench-on-aws#472]
As you go through the 4 tabs of Add Configuration no validation is done until the last tab.  At that point it just says there was an error and there is no way to go back and fix anything.  You are forced to start over and hope you fix the error.

Looking at the network traffic in the browser debugger I found that the error was with my cost estimate!  I would think this would be optional and free form.

Apparently "<$1/day" is not valid.

**Comment by jn1119** [comment]
Thanks for reporting the issue. We will be looking into it this week.

**Comment by SanketD92** [comment]
Fix has been merged. Closing this thread.
