### ISSUE TITLE
[Feature Request] Charging different user account bills to different credit cards

### ISSUE THREAD

**Issue by cx1111** [awslabs/service-workbench-on-aws#537]
**Is your feature request related to a problem? Please describe.**

I am working with a university department with one instance of service-workbench, which is supposed to support multiple individual labs/users. With the current billing model, all charges do directly to a single Amazon root account, and it is up to the single owner to collect funds from the downstream users. This can be dangerous and unreliable, and the single account owner can get stuck will huge bills that may or may not be paid back.

**Describe the solution you'd like**

There should be the ability to charge the computing costs of individual accounts to specified credit cards so that individual labs/users pay directly for their own compute.

**Describe alternatives you've considered**

I would actually like some suggestions too. I have considered collecting the credit cards of the individual labs in a separate application, and periodically charging them. But this separate application will always be flaky and inferior to an integrated AWS solution.

Service workbench aside, what is the general recommended practice for creating a platform built on top of AWS, and charging individual customers for their compute? Thank you.

**Comment by SanketD92** [comment]
Hello @cx1111, thank you for opening this issue.

Did you **create** a new member (aka hosting) account via Service Workbench? If so, then the Organization management (aka master) account, linked to the respective member account is responsible for their billing.

However if you **add** an existing AWS account as a member account in Service Workbench, then that member account is responsible for its own billing.

For more information, take a look at this [document](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/docs/deployment/post_deployment/aws_accounts.md).

Hope this helps.
