### ISSUE TITLE
[Bug] Clarify Node.js and Go versions

### ISSUE THREAD

**Issue by cx1111** [awslabs/service-workbench-on-aws#538]
**Describe the bug**

It is not clear which Node.js and Go versions are suitable for running this project. 

- The main [README](https://github.com/awslabs/service-workbench-on-aws/tree/v3.2.0#installing-service-workbench) specifies Node.js 12.x, but the [prereq page from the docs site](https://github.com/awslabs/service-workbench-on-aws/blob/v3.2.0/docs/docs/deployment/pre_deployment/prereq_commands.md) specifies 10.15.x.
- There is no mention of any Go version anywhere.

In addition, it's not clear which operating systems/architectures this is supposed to work on (aside from amd64 linux). How about macos with Intel or ARM?

**To Reproduce**

**Expected behavior**
There should be at least one example of a working node.js version in a `package.json`. There should also be at least one documented version of Go that results in a successful installation.

**Versions (please complete the following information):**

v3.2.0

**Comment by cx1111** [comment]
If it helps, I managed to run the full installation using:
- M1 Macbook, macOS Big Sur v11.0
- Node.js 12.22.1
- Go 1.16.5

**Comment by carvantes** [comment]
Hi,

Sorry to hear that you found issues with the docs. 
- The recommended Node.js version is 12.x
- The recommended Go version is 1.13.7+ [from the s3-synchronizer README](https://github.com/awslabs/service-workbench-on-aws/tree/mainline/addons/addon-raas-s3-copy/packages/s3-synchronizer#tools)

We'll update the docs to make those versions consistent across the different pages
