### ISSUE TITLE
[Feature Request] Embed Videos in Study Descriptions

### ISSUE THREAD

**Issue by nkitmitto** [awslabs/service-workbench-on-aws#554]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to an existing problem.

**Describe the solution you'd like**
I would like to be able to embed (in HTML or MD) a video source into the description of a study.  This would allow us to give our users a deeper look into what is in each study.

**Describe alternatives you've considered**
We've considered linked directly to a Youtube video we put out there.  But the user experience from this implementation idea is very poor.

**Comment by SanketD92** [comment]
Hello @nkitmitto, thank you for opening this issue.

We'll open a ticket in our backlog and we'll prioritize it into upcoming sprints based on the volume of similar requests.

To gain some more context, the video you're describing would only show a "glimpse" of the files and folders contained in that study, right? Currently users can view the study contents for which they have access. Does this not suffice for your use-case?

**Comment by nkitmitto** [comment]
Sorry, this is a video of basically a lead researcher describing the study itself or going more in-depth on their research with that data.

**Comment by nkitmitto** [comment]
Hello, I haven't heard anything about this since 6/28.  Is there an ETA for this feature?

Thanks

**Comment by rsmayda** [comment]
This is a low-priority feature and has not been scheduled. We would be happy to support a community contribution!

**Comment by kpark277** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.
