### ISSUE TITLE
[Feature Request] Ability to change EC2 instance type to scale up/down vertically for already launched workspaces.

### ISSUE THREAD

**Issue by irshadc** [awslabs/service-workbench-on-aws#557]
**Is your feature request related to a problem? Please describe.**
Currently Researcher can easily create machine with defined studies, but it can select from sizes only at the time of workspace creation. For researcher, when they are developing vs running on the same machine. They want to switch between different machine size during the day to save on cost.

**Describe the solution you'd like**
Similar to Feature added as Edit CIDR we should give option of changing Machine size. Which will first warn Researcher about machine being stopped first and then upgrade would happen. It will stop the machine change the Machine configuration and start it again.

**Describe alternatives you've considered**
Currently it can be done from back-end EC2 instance console, but that require either knowledge of AWS EC2 Console to researcher or relying on AWS SysOps Engineer.

**Additional context**
Same feature can be later extended to SageMaker type of workspaces as well.

**Comment by rsmayda** [comment]
Hey @irshadc thanks for bringing this request up! Just to make sure to set the scope correctly this is explicitly scaling of EC2s?

**Comment by irshadc** [comment]
Yes @rsmayda, thanks for correcting it.
