### ISSUE TITLE
plugin-registry.js error during deployment

### ISSUE THREAD

**Issue by angelosnm** [awslabs/service-workbench-on-aws#565]
The below error message is appearing when trying to deploy the app with environment-deploy.sh script.

`ERROR in ./src/lambdas/open-data-scrape-handler/plugins/plugin-registry.js
Module not found: Error: Can't resolve '@aws-ee/base-raas-cfn-templates/dist/plugins/cfn-templates-plugin' in '/home/ec2-user/service-workbench-on-aws-3.1.0/main/solution/backend/src/lambdas/open-data-scrape-handler/plugins'
 @ ./src/lambdas/open-data-scrape-handler/plugins/plugin-registry.js 27:35-111
 @ ./src/lambdas/open-data-scrape-handler/handler.js
`

**Comment by Bingjiling** [comment]
HI @agelosnm, thanks for reaching out! Could you please share more information about the issue you ran into? We have a bug report template [here](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/.github/ISSUE_TEMPLATE/bug_report.md) and it would be awesome if you could follow it.

**Comment by angelosnm** [comment]
> HI @agelosnm, thanks for reaching out! Could you please share more information about the issue you ran into? We have a bug report template [here](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/.github/ISSUE_TEMPLATE/bug_report.md) and it would be awesome if you could follow it.

Hi @Bingjiling !

The issue is happening when running environment-deploy.sh script. e.g: `./scripts/environment-deploy.sh ${STAGE_NAME}`

![error-1](https://user-images.githubusercontent.com/28690845/124939088-82e45500-e011-11eb-9430-29193d9a8180.PNG)
![error-2](https://user-images.githubusercontent.com/28690845/124939036-7b24b080-e011-11eb-9c92-fb3d56b7fc70.PNG)
![error-3](https://user-images.githubusercontent.com/28690845/124939085-824bbe80-e011-11eb-85cd-7c99803903e4.PNG)

Note that it has been reproduced by using all 3.x versions.

**Comment by angelosnm** [comment]
Hello!

Note that we have ran the deployment steps on a clean new EC2 instance and the issue appeared too as well

**Comment by Bingjiling** [comment]
Hi @agelosnm, 

Thanks for sharing the detail! There're a few things you could try to resolve this problem: 

* Confirm dependencies are installed correctly (Node, pnpm, Go)
* Remove everything in `node_modules` and run script `./scripts/install.sh` to reinstall all node dependencies
* Run script `./scripts/environment-deploy.sh ${STAGE_NAME}` again

Please let me know if it works for you. 

Thanks,
Yanyu

**Comment by angelosnm** [comment]
Hi @Bingjiling!

Please note that I was running the installation commands as a "root" user and not as a default "ec2-user" hence the issue.
Upon installing as "ec2-user" operation completed successfully.

**Comment by Bingjiling** [comment]
HI @agelosnm , thanks for sharing this with us! We'll add it to our troubleshooting notes. I'll close this issue, and please don't hesitate to reach out if you have any other questions.

**Comment by tdmalone** [comment]
hi @Bingjiling, I've hit this problem today (with v5.0.0), and it seems others have also (eg. https://github.com/awslabs/service-workbench-on-aws/issues/429)

Can I suggest a check in `environment-deploy.sh` that errors early if you're using `root`? (or alternatively, an update to the documentation to state not to run as `root`).
