### ISSUE TITLE
[Bug] Auto stop feature not working anymore

### ISSUE THREAD

**Issue by avillach** [awslabs/service-workbench-on-aws#577]
**Describe the bug**
in our PROD environment 
SageMaker Notebook-v2
configuration: Auto-stop idle-time : 60min

**To Reproduce**
just launch sagemaker, non of them will stop

**Expected behavior**
it should stop after 60mn
**Screenshots**
![image001](https://user-images.githubusercontent.com/4821297/125705577-7c79a5ee-cf8f-44d3-89e8-8972b41a56a6.png)

**Versions (please complete the following information):**
 - Release Version installed 3.1.0

**Additional context**

**Comment by nguyen102** [comment]
Thanks for filing this bug Paul. Version 3.2 of SWB has a [fix](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v3.2.0) for AutoStop not working. I would recommend upgrading SWB to atleast version 3.2 to get this fix.

**Comment by avillach** [comment]
Hi, I updated SWB to v3.3.0
SageMaker notebooks still don't stop automaticly after 60mn.

Do I need to IMPORT and APPROVE the latest workspace "SageMaker Notebook-v3" to see this bug corrected?  If so,  this wasn't described in bug report https://github.com/awslabs/service-workbench-on-aws/pull/515  neither in release v3.2.0 that we ALSO had to IMPORT and APPROVE the latest workspace

**Comment by avillach** [comment]
After updating to Sagemaker v3 the note book now stops automaticly BUT I can't see the status change in SWB UI. 
It still shows as AVAILABLE but login in AWS console I can see that it STOPTED. 
Thanks
Paul

Screenshot showing the SAME notebook from SWB UI and AWS Console

**Comment by jol-ster** [comment]
This is likely linked to a status update bug that we have in our backlog.  The polling of the status and the resulting update to the DDB table has a possible disconnect.  The item is open, and I'll update as we are able to address it.  Thank you for the examples.

**Comment by avillach** [comment]
FYI: since I updated to 3.3.1 I don't see this issue anymore. Stoped SageMaker are now being displayed as STOPED  in SWB UI
