### ISSUE TITLE
[Bug] SWB upgraded to v3.3.0 but showing Version 3.2.0 in admin UI

### ISSUE THREAD

**Issue by avillach** [awslabs/service-workbench-on-aws#586]
**Describe the bug**
![Screen Shot 2021-07-20 at 3 26 22 PM](https://user-images.githubusercontent.com/4821297/126384188-cc73ac97-4d4d-4f97-b388-5c2f52b928ac.png)
**To Reproduce**
v3.3.0 deployed https://github.com/hms-dbmi/service-workbench-on-aws/tree/hms-prod 
but admin UI not showing correct number

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
v3.3.0 deployed https://github.com/hms-dbmi/service-workbench-on-aws/tree/hms-prod 

**Additional context**

**Comment by nguyen102** [comment]
Ah, I'm sorry. Looks like that is an error on our part. You can fix that by updating this [line](https://github.com/hms-dbmi/service-workbench-on-aws/blob/hms-prod/main/config/settings/.defaults.yml#L175) to have the text `3.3.0`.

**Comment by avillach** [comment]
issue resolved! thanks!
