### ISSUE TITLE
[Feature Request] Importing previous configuration when upgrading a workspace

### ISSUE THREAD

**Issue by avillach** [awslabs/service-workbench-on-aws#588]
**Is your feature request related to a problem? Please describe.**
Everytime I update a workspace type
eg Sagemaker from v1 to v2 and now to v3 I need to copy paste all configuration. and this takes a LOT of time
**Describe the solution you'd like**

**Describe alternatives you've considered**
Pre filling previous configuration from the SAME workspace type would be very apreciated!
Thanks

**Additional context**

**Comment by tdmalone** [comment]
@avillach As a workaround - the configuration is stored in S3 (in the `...-env-type-configs` bucket, named for the associated Service Catalog product IDs, and in JSON format), so you could download and re-upload that configuration to manually export and import the settings.
