### ISSUE TITLE
[Bug] Upgrading AWS solution installation - S3 access denied

### ISSUE THREAD

**Issue by dcloud9** [awslabs/service-workbench-on-aws#603]
**Describe the bug**
I used [CFN](https://docs.aws.amazon.com/solutions/latest/service-workbench-on-aws/automated-deployment.html) to build SWB successfully.
Now following the [Upgrading AWS solution](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/docs/installation_guide/upgrading/solutions.md), after bumping the version to latest as of today is `v3.3.1`, it errored on `aws s3 cp...`.
I also tested using my `aws cli` tool and failed as well.
Seems the version is stucked at `v1.4.7` and stopped being updated from `v2.0.0`

**To Reproduce**
1. Follow the [Upgrading AWS solution](http://localhost:3000/installation_guide/upgrading/solutions) doc
2. Edit the value of `OBJECT_KEY_NAME` and set it to service-workbench-on-aws/v3.3.1
3. Failed message. See error
```
14 | [Container] 2021/07/27 10:03:48 Entering phase INSTALL
15 | [Container] 2021/07/27 10:03:48 Running command aws s3 cp s3://$GLOBAL_BUCKET_NAME-$REGION_NAME/$OBJECT_KEY_NAME/ServiceWorkbenchOnAWS.zip ServiceWorkbenchOnAWS.zip
16 | fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
17 |  
18 | [Container] 2021/07/27 10:03:55 Command did not exit successfully aws s3 cp s3://$GLOBAL_BUCKET_NAME-$REGION_NAME/$OBJECT_KEY_NAME/ServiceWorkbenchOnAWS.zip ServiceWorkbenchOnAWS.zip exit status 1
19 | [Container] 2021/07/27 10:03:55 Phase complete: INSTALL State: FAILED
20 | [Container] 2021/07/27 10:03:55 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: aws s3 cp s3://$GLOBAL_BUCKET_NAME-$REGION_NAME/$OBJECT_KEY_NAME/ServiceWorkbenchOnAWS.zip ServiceWorkbenchOnAWS.zip. Reason: exit status 1


```
4. Verified using `awscli`
```
aws s3 cp s3://solutions-eu-west-2/service-workbench-on-aws/v1.4.7/ServiceWorkbenchOnAWS.zip .
download: s3://solutions-eu-west-2/service-workbench-on-aws/v1.4.7/ServiceWorkbenchOnAWS.zip to ./ServiceWorkbenchOnAWS.zip

aws s3 cp s3://solutions-eu-west-2/service-workbench-on-aws/v3.3.1/ServiceWorkbenchOnAWS.zip .
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

aws s3 cp s3://solutions-eu-west-2/service-workbench-on-aws/v2.0.0/ServiceWorkbenchOnAWS.zip .
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

```

**Expected behavior**
Upgrade using CodeBuild as per doc is successful/green.
Better yet feed the `version` as CFN stack parameters (feature/improvement)

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed `v1.4.7`

**Additional context**

**Comment by SanketD92** [comment]
Hi @dcloud9, you mentioned you've installed the Solutions version of SWB initially and are now trying to update that installation using the latest GitHub repository. 

Both mechanisms of SWB installation (Solutions vs GitHub) are using different repositories as source code, which are currently out of sync. We therefore recommend to stay consistent with the installation mechanism for upgrades.

However, the error you've shared suggests your configured AWS profile on the installation machine is not permitted to perform S3 operations.

Hope this helps.

**Comment by dcloud9** [comment]
I only used the CloudFormation way, install and upgrade. Thanks for confirming the CFN way is lagging. I won't use that ever, might as well remove that from the docs. I'm now using the EC2 with instance profile attached way for install and upgrade.

**Comment by SanketD92** [comment]
Also, I think the reason your S3:HeadObject command failed is because there isn't any Solutions template corresponding to v3.3.1 on that S3 bucket.

**Comment by dcloud9** [comment]
Agreed. Do not use CloudFormation way at all.
