### ISSUE TITLE
Docusaurus installation issue

### ISSUE THREAD

**Issue by angelosnm** [awslabs/service-workbench-on-aws#613]
I tried to install Docusaurus  with the steps described.

"yarn" command comes with the below error:

![1](https://user-images.githubusercontent.com/28690845/127626300-7aefb9f1-bfd9-409e-88d1-244d23c6f375.png)

The issue overcomed by installing using " yarn install --ignore-engines"

![2](https://user-images.githubusercontent.com/28690845/127626301-759ffa2d-9ab5-4a86-be58-dc1ff3c46a12.png)

Although, when starting yarn, the below error comes up:

![3](https://user-images.githubusercontent.com/28690845/127626319-dfa46b04-6b94-4cd1-818b-96d97fb57b81.png)

**Comment by carvantes** [comment]
Hi,
Looks like you are using Node.js 8.1.0.  Node.js 8.x reached End-of-Life on 2019-12-31 and is not supported.

Node.js v12.x or later is required by service-workbench-on-aws ([software-requirements](https://github.com/awslabs/service-workbench-on-aws#software-requirements))

Please upgrade your Node.js version and retry the installation. 

Feel free to reopen this issue if the above doesn't fix your problem.

**Comment by angelosnm** [comment]
Hello! I overcomed this issue by updating Node.js version.
Although now, when I'm running "yarn start" app is running on port 3000 but it is not accessible from outside. Firewall restrictions have been checked and the needed traffic is allowed. I suppose somewhere in the a "localhost" attribute must be changed to "0.0.0.0" in order application to operate normally.

Also, on yarn build, the below issue comes up:

![image](https://user-images.githubusercontent.com/28690845/128330608-2228f839-451d-4d67-80a1-0e0cb0d99c3d.png)
