### ISSUE TITLE
"null is not an object" while trying to connect to Sagemaker notebook.

### ISSUE THREAD

**Issue by tom-christie** [awslabs/service-workbench-on-aws#620]
**Describe the bug**
Occasionally after starting a Sagemaker workspace, clicking 'Connect' gives an error in the bottom right-hand corner of the screen:

> We have a problem!
> null is not an object (evaluating 'l.location=s') 

in a little red box on the bottom-right of the screen. The notebook window is not opened after clicking on 'Connect'.

**To Reproduce**
The error is intermittent. I *think* it may happen after the SW window has been open a while, because I noticed that the SW window automatically logged me out shortly after seeing this error.

1. Click 'Start' for Sagemaker workspace and wait for the status to change to 'Available'. 
2. Click 'Connections', then 'Connect'
3. See error

When I logged out and back into Service Workbench, and was able to connect to the workspace successfully. 

**Expected behavior**
A new window should open with a Jupyter/Sagemaker notebook in a new window. 

**Versions (please complete the following information):**
 - 3.2.0

**Comment by SanketD92** [comment]
Hi @tom-christie, we believe the issue mentioned is due to access token getting expired. Please feel free to use the latest version with the fix ([v3.3.1](https://github.com/awslabs/service-workbench-on-aws/releases/tag/v3.3.1)).

**Comment by saxman** [comment]
We're seeing this issue on 4.1.1 as well. However, it appears to be persistent (i.e. it happens every time we connect to a SageMaker workspace). So far, we've only tested a single workspace config, but the error consistently shows up when we try to connect to different workspace instances using the same config. The workspace instances are new and running, at least as shown in the SWB UI. We haven't verified if the instances are available in the SageMaker console, however.

**Comment by crabba** [comment]
Is it possible this is related to a popup blocker as reported in GALI-1224? It creates a similar error message.
https://sim.amazon.com/issues/CHAMDOC-17

**Comment by nguyen102** [comment]
Yeah, I've seen the error happen because popups are disabled for the SWB domain. Once you enable popup for the SWB domain, it should allow you to connect to Sagemaker. Feel free to reopen this ticket if enabling popups didn't resolve your issue.
