### ISSUE TITLE
[Bug] Documentation says to use AWS-generated cost allocation tags but image shows User-defined 

### ISSUE THREAD

**Issue by primerano** [awslabs/service-workbench-on-aws#625]
**Describe the bug**

In the documentation at http://swb-documentation.s3-website-us-east-1.amazonaws.com/installation_guide/installation/pre-installation/tool-req 

Step 3 says to use AWS-generated cost allocation tags
_Under AWS-generated cost allocation tags, choose the createdBy, Env, and Proj tags._

The image shows User-defined.  

Which one is right?  User-defined or AWS-generated?

Please fix the text or the image.  
- https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/docs/installation_guide/installation/pre-installation/tool-req.md
- https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/static/img/deployment/installation/cost_atags2.png

**To Reproduce**
Documentation error.  See document

**Expected behavior**
clear documentation ;-)

**Screenshots**
See above

**Versions (please complete the following information):**
 - master branch

**Additional context**
none

**Comment by SanketD92** [comment]
Thank you for pointing this out, @primerano. We will fix the documentation text soon.

**Comment by primerano** [comment]
@SanketD92 in the meantime can you tell me which one is right? User-defined or AWS-generated? :-)

**Comment by SanketD92** [comment]
The image is right, it's User-defined. :)

**Comment by SanketD92** [comment]
Fixed: https://github.com/awslabs/service-workbench-on-aws/pull/628
