### ISSUE TITLE
[Misc] is golang a requirement?

### ISSUE THREAD

**Issue by primerano** [awslabs/service-workbench-on-aws#630]
**What's on your mind?**
scripts/environment-deploy.sh works for me but I noticed errors in the log regarding go.

![image](https://user-images.githubusercontent.com/148409/128239317-28269a4e-bb89-436a-8405-53eb0e3dd3a4.png)

Can these be ignored or should I install go and redeploy?

**Versions (please complete the following information):**
 - Release Version installed 
 - mainline

**Comment by SanketD92** [comment]
Hi @primerano, golang is a requirement since it is used for the multipart S3 downloader tool EC2 Windows based research environments. Although it is recommended to have it installed, you can safely ignore the error if you don't expect to use EC2-Windows workspaces.

**Comment by SanketD92** [comment]
Also, the fix for this bug is in [progress](https://github.com/awslabs/service-workbench-on-aws/pull/641). Feel free to install from the latest release after this has been merged.

**Comment by Bingjiling** [comment]
The [fix](https://github.com/awslabs/service-workbench-on-aws/pull/641) for this issue has been merged. Closing this issue now.
