### ISSUE TITLE
[Bug] infrastructure deploy creates hosted zone on each run

### ISSUE THREAD

**Issue by primerano** [awslabs/service-workbench-on-aws#644]
**Describe the bug**
After a few failed attempts to re-deploy infrastructure I noticed I had redundant hosted zones

**To Reproduce**

1. Go to main/solution/infrastructure
2. run `pnpx sls deploy -s <a stage name with domainName set>`
3. run it again
4. go to hosted zones in console and you'll see you have 2 or more identical zones now.

Note: I'm not sure if this makes a difference but my deploys failed due to certificateArn issues

**Expected behavior**
* If a zone already exists don't create another one.  
* if a deploy fails and a zone was created it should probably be rolled back

**Screenshots**

**Versions (please complete the following information):**
 - mainline (this also happens in earlier releases)

**Additional context**
none

**Comment by SanketD92** [comment]
Hi @primerano, thanks for reporting this. We're currently aware of this issue and we'll be working on it during upcoming sprints according to business priorities. And although we've noticed redundant hosted zones to be created, this should not cause certificateArn issues. Could you give us some details as to what kind of issues you're seeing?

**Comment by primerano** [comment]
@SanketD92 - no issues other than the clutter on the hosted zone page.

**Comment by rikkibar** [comment]
@SanketD92 I have an update for the source code which resolves this issue if I can pass it on? Within the current repo, it doesn't factor in existing hosted zones. Based on the SWB deployment there are 3 possible setups:
1 - There is no custom domain or hosted zone
2 - There is a custom domain but no hosted zone
3 - There is a custom domain with an existing hosted zone

I have added in additional conditions and an additional resource for the R53 record depending if there is an existing hosted zone

[cloudformation.zip](https://github.com/awslabs/service-workbench-on-aws/files/7466553/cloudformation.zip)

**Comment by nguyen102** [comment]
PR was in merged in for preventing duplicated hosting zones
https://github.com/awslabs/service-workbench-on-aws/pull/789
