### ISSUE TITLE
[Feature Request] Delete Data Source from DDB & SWB UI

### ISSUE THREAD

**Issue by primerano** [awslabs/service-workbench-on-aws#666]
**What's on your mind?**
I see that I can remove the CloudFormation stack for a data source

http://swb-documentation.s3-website-us-east-1.amazonaws.com/user_guide/sidebar/common/studies/data_sources/

How can I remove it from the application?  Is there a row I can delete in dynamo db to remove a failed data source?

**Versions (please complete the following information):**
 - Release Version installed: mainline

**Comment by rsmayda** [comment]
Hey @primerano! A quick answer is that there isn't a recommended way at this time. Let me convert this issue into a feature request and we can get this prioritized.
