### ISSUE TITLE
[Misc] How to increase the sagemaker notebook HD size to a different default value of 5GB?

### ISSUE THREAD

**Issue by avillach** [awslabs/service-workbench-on-aws#668]
How to increase to 100GB for example
 - Release Version installed 3.3.1

Thanks

Paul

**Comment by nguyen102** [comment]
You can update the Sagemaker CFN template [here](https://github.com/awslabs/service-workbench-on-aws/blob/b9c1a721e90702825a4ca0ec8b2b7adb52d63a99/addons/addon-base-raas/packages/base-raas-cfn-templates/src/templates/service-catalog/sagemaker-notebook-instance.cfn.yml#L220) to increase the volume size.

The attribute you would change is [VolumeSizeInGB](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstance.html#cfn-sagemaker-notebookinstance-volumesizeingb).

Note making this change will result in a new Sagemaker workspace version. You will need to import this into SWB.
