### ISSUE TITLE
[Feature] Support EMR workspace type auto-stop functionality

### ISSUE THREAD

**Issue by aGutierrezSacristan** [awslabs/service-workbench-on-aws#700]
**Describe the bug**
When creating a EMR workspace, if not stopping it manually, it is not auto-stop.

**To Reproduce**
1. Go to 'workspaces'
2. Click on 'create research workspace'
3. Select 'EMR-v1'
4. Select any configuration
5. Start the workspace

The workspace will not be stopped automatically, needs to be stopped manually.

**Expected behavior**
That as in the SageMaker workspaces types, the EMR auto-stop idle-time.

**Versions (please complete the following information):**
- Release Version installed: 3.3.1

**Comment by jol-ster** [comment]
Thank you for the feedback - the Auto Stop function currently only applies to the Sagemaker and RStudio workspace types 

**For Sagemaker:**  
When the workspace type is configured, there is an "AutoStopIdleTimeInMinutes" setting that the administrator can set that drives the Auto Stop interval

**For RStudio:** 
The RStudio Auto Stop setting is baked into the AMI. By default it is set to 1 hour, if the user wants to change this they can do so in the main/solution/machine-images/config/infra/files/rstudio/check-idle file and recreate their RStudio AMI. More info [here](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/main/solution/machine-images/README.md)

To introduce Auto Stop for EMR would be a new feature - and I'm very interested to hear your anticipated use case (type of workload, frequency).  I'd also appreciate your input around what you would want to drive the Auto Stop functionality (inactivity, time passed, or some combination).  I'm changing this label from a bug to a feature request.

**Comment by aGutierrezSacristan** [comment]
Got it. Thank you so much for the information. 
For the EMR workspace, the AutoStop functionality based on X time of inactivity would be really useful. I am not sure about the time passed one, I do not have a use case in mind yet for this.
