### ISSUE TITLE
[Bug] workspace with status as available but error when clicking on connections, stop and terminate

### ISSUE THREAD

**Issue by aGutierrezSacristan** [awslabs/service-workbench-on-aws#707]
**Describe the bug**
Some workspaces, with the status as "Available", but that cannot be started clicking on connections. Stop and terminate don't work either. 

**To Reproduce**
1. Create a SageMaker Notebook-v3 workspace
2. Status available
3. Work with the workspace
4. Autostop did not work, stay as available but
5. Try to click on Connections --> A problem was encountered
6. Try to stop it manually --> "we have a problem! something went wrong"
7. Try to terminate it manually -->  "we have a problem! something went wrong"

**Expected behavior**
That if the status of the workspace is available the user can:
- start
- stop 
- terminate 

**Screenshots**
Error when trying to connect:
![Screen Shot 2021-09-11 at 9 27 01 AM](https://user-images.githubusercontent.com/19646530/132950619-a21bcb33-41e3-44bd-9d38-4e6a4230fbe6.png)

Error when trying to stop or terminate:
![Screen Shot 2021-09-11 at 9 27 16 AM](https://user-images.githubusercontent.com/19646530/132950634-b6bdeb59-e278-4c83-b9bf-88e3c2835fce.png)

Errors in the chrome dev console when clicking on the "connections", "stop" and "terminate"
![Screen Shot 2021-09-11 at 10 11 02 AM](https://user-images.githubusercontent.com/19646530/132950741-cf31627f-fbaf-4420-86f1-53261197ad78.png)

**Versions (please complete the following information):**
Release Version installed: 3.3.1

**Comment by nguyen102** [comment]
I think there's a good chance this instance was autostopped, but that information was not propagated to DDB correctly.

Can you log onto the hosting account for that Sagemaker instance and check if it's currently in the Stopped state. If yes, the latest code fixes that issue.
8cb199b

**Comment by aGutierrezSacristan** [comment]
Hi @nguyen102 same for these cases, even if appear as "Available" in SWB, when log in onto the hosting account, I can confirm that the Sagemaker instances are in the Stopped sate. So then, the latest code that you mention should fix this issue too.

**Comment by nguyen102** [comment]
yep, thats correct.
