### ISSUE TITLE
[Bug] SageMaker Notebook-v3 Workspace changed to "Unknown" status and cannot connect anymore

### ISSUE THREAD

**Issue by aGutierrezSacristan** [awslabs/service-workbench-on-aws#708]
**Describe the bug**
A SageMaker Notebook-v3 workspace that was working fine on Friday today appears with the status as "Unknown". 
When clicking on connect the new window pop up but is empty, and when going back to the SWB page, we see the message, "We have a problem! Something went wrong"

**To Reproduce**
1. Go to 'Workspaces'
2. Look for the workspace that was expected to be "Stoped"
2. Click on 'connect'

**Expected behavior**
That the workspace was "Stopped" and when clicking on Connect we can access to the workspace. 

**Screenshots**
![Screen Shot 2021-09-13 at 1 27 57 PM](https://user-images.githubusercontent.com/19646530/133129766-85139082-e6e7-4fe1-8624-dedebf573ea5.png)

**Versions (please complete the following information):**
Release Version installed: 3.3.1

**Additional context**
The workspace was working fine all previous week, autostop and connect without any issue. Unknown status found today.

**Comment by nguyen102** [comment]
I think there's a good chance this instance was autostopped, but that information was not propagated to DDB correctly.

Can you log onto the hosting account for that Sagemaker instance and check if it's currently in the `Stopped` state. If yes, the latest code fixes that issue.
https://github.com/awslabs/service-workbench-on-aws/commit/8cb199b8093f5e799d2d87c228930a4929ebebb7

**Comment by aGutierrezSacristan** [comment]
Hi @nguyen102 yes, I can confirm that the Sagemaker instance is  in the Stopped sate. So then, the latest code that you mention should fix the issue.
