### ISSUE TITLE
[Bug] Workspace with Rstudio not loading

### ISSUE THREAD

**Issue by aGutierrezSacristan** [awslabs/service-workbench-on-aws#719]
**Describe the bug**
When we create a workspace with Rstudio, once the workspace is available, we click on connect, and a new window is opened, but Rstudio is not loaded. When going back to the SWB workspaces we can see on the bottom right the message: "something went wrong". We tested it in Safari and Chrome, and the error is the same. 
 
**To Reproduce**
1. Go to 'workspaces'
2. Click on 'create research workspace'
3. Select EC2 RStudio-v2, R version 3.4.3 (2017-11-30)
4. Select RStudio_v2-Small (Small-Sized RStudio Server; Instance Type : r5.xlarge; vCpus : 4
Memory : 32GiB;  Auto-stop idle-time : 60min)
5. When the workspace appears as "Available" click on "connect"
6. Then a new window is open but nothing loads and in the workspace page the error "something went wrong appears"

**Expected behavior**
A new window with Rstudio should be opened. 

**Screenshots**
How the research workspace looks like:
![Screen Shot 2021-09-22 at 3 23 45 PM](https://user-images.githubusercontent.com/19646530/134408884-abec91fe-7b9d-4420-9864-963f83c3e399.png)

The error when clicking on "connect":
![Screen Shot 2021-09-22 at 3 23 22 PM](https://user-images.githubusercontent.com/19646530/134408938-a36927fb-1364-4e8a-b8fa-3910beb0714b.png)

**Versions (please complete the following information):**
 - Release Version installed: v3.4.0

**Comment by SanketD92** [comment]
Hello @aGutierrezSacristan, thank you for opening this bug.

1. Does stopping and starting the instance via SWB help in connecting to the instance?
2. The RStudio instance is backed by an EC2 instance on the hosting (a.k.a member) account. Could you connect to the EC2 instance via AWS Management Console and verify the following:
  a. Run the commands `systemctl restart nginx` and `systemctl status nginx`
  b. Run the commands `systemctl restart rstudio-server` and `systemctl status rstudio-server`

The steps above would tell us whether this is related to: 
(1) the public key not getting stored in SSM for RStudio instances,
or if
(2) the RStudio-server is not getting installed correctly, for which we currently have a related bug in our backlog.

Thank you.

**Comment by nguyen102** [comment]
This [PR](https://github.com/awslabs/service-workbench-on-aws/pull/726) should fix the issue that you're experiencing. You can get those changes by deploying the latest SWB code on [mainline](https://github.com/awslabs/service-workbench-on-aws/commits/mainline)
