### ISSUE TITLE
[Feature Request] Allow project based, customizable workspace types that only assigned projects can access. 

### ISSUE THREAD

**Issue by digitalrager** [awslabs/service-workbench-on-aws#733]
**Is your feature request related to a problem? Please describe.**
We are serving a very diverse set of projects and often find that we could leverage the service workbench better if we had ways to build customized workspaces that only specific projects could access.  For instance, we might build and AMI for a project and allow their team to launch the AMI, or define a custom security group configuration that would be applied on launch, that allows specific exceptions that a project team may want to support.  These types of customizations wouldn't apply to other projects so limiting the view of the customized workspaces to specific project teams to use would be very helpful.  

**Describe the solution you'd like**
The ability to share either a workspace type with a project team via configuration by an administrator role. 

Display only the non-project specific workspaces types and project assigned workspace types to users based on project membership of the end users. 

**Describe alternatives you've considered**
We saw that workspace configurations might be limited to certain roles but there is no method to create new roles so do not believe this is supported.  We are considering naming conventions for customized workspaces but that does increase the amount of noise in the workspace listing and doesn't limit the access to just the teams needing to use the configuration. 

**Additional context**
Some of the customization affects security of the environment, so we may be blocked from starting down this path without some idea how we can limit access to specific workspaces to specific projects.

**Comment by Bingjiling** [comment]
Hi @digitalrager, 

Thanks for reaching out! 

Using project to set permissions for resources has been a familiar topic to us. And we've got other customers asking for this feature as well. Right now it is on our future roadmap but we don't have estimate on if/when it'll be delivered. 

Thanks,
Yanyu

**Comment by tdmalone** [comment]
Relates to https://github.com/awslabs/service-workbench-on-aws/issues/222
