### ISSUE TITLE
[Bug] Workspaces with Rstudio not loading

### ISSUE THREAD

**Issue by aGutierrezSacristan** [awslabs/service-workbench-on-aws#758]
**Describe the bug**
When we create a workspace with Rstudio, once the workspace is available, we click on connect and a error message pop up on the bottom right on the screen: “something went wrong”. 

**To Reproduce**
1. Go to ‘workspaces’
2. Click on ‘create research workspace’
3. Select EC2 RStudio-v2, R version 3.4.3 (2017-11-30)
4. Select RStudio_v2-Small (Small-Sized RStudio Server; Instance Type : r5.xlarge; vCpus : 4 Memory : 32GiB; Auto-stop idle-time : 60min)
5. When the workspace appears as “Available” click on “connect”
6. Then on the workspace page the error "something when wrong" appears.

**Expected behavior**
A new window with Rstudio should be opened.

**Screenshots**
How the research workspace looks like: 
![Screen Shot 2021-10-17 at 7 35 31 PM](https://user-images.githubusercontent.com/19646530/137649055-72574425-3936-4cc2-8d9c-3027e9792f15.png)

The error when clicking on "connect":
![image](https://user-images.githubusercontent.com/19646530/137649120-86493856-e2f7-4df7-afa0-93c8652f1be1.png)

**Versions (please complete the following information):**
 - Release Version installed v4.0.1

**Comment by jn1119** [comment]
Are you facing the issue with an old RStudio Service Catalog Product Version? If yes, have you tried importing the latest product version and using that instead?

**Comment by aGutierrezSacristan** [comment]
Hi @jn1119 thanks for the quick answer. The issue is solved after importing the latest version. Thanks!
