### ISSUE TITLE
[Feature Request] Bring Your Own Bucket UI usage

### ISSUE THREAD

**Issue by spensireli** [awslabs/service-workbench-on-aws#768]
**Is your feature request related to a problem? Please describe.**
I am ecstatic that bring your own bucket is now supported in galileo, however I would prefer if this was something that could be done through the UI.  Right now from what I can tell the functionality only exists from the CLI.

**Describe the solution you'd like**
 I would like to be able to provision buckets from the UI in galileo for other AWS accounts. The target audience is not technical heavy and I fear that the usage of CLI instructions will result in more confusion than gain. When using BYOB I can see the objects, but the same functionality in the UI doesn't exist as if the bucket was owned by the hosting account. 

**Describe alternatives you've considered**
Using the CLI for BYOB.

**Comment by maghirardelli** [comment]
Hello @spensireli,

Thanks for your comment! Currently, the aim of BYOB is for customers to use data from preexisting buckets in the workspaces. If a customer wants to store new data, they can create a new study and attach it to their workspace. Granted, this will be a subfolder in a preexisting bucket, instead of a new bucket. It does accomplish the same thing though functionally. Buckets cannot be created from within SWB yet, but I will add an item to our backlog to look into implementing that functionality.

Thanks,
Marianna

**Comment by spensireli** [comment]
Is there any plans to be able to integrate in N+1 accounts S3 buckets to allow upload/download from the UI? Right now from what I see it is limited to the main account's S3 data bucket. Even when associating a different bucket users can't add files to it.

**Comment by jn1119** [comment]
If I am understanding it correctly - you would like to upload/download for BYOB buckets from the UI, is that correct? We haven't considered that feature. Currently, read/write access is only supported via workspaces that have the BYOB study attached.

**Comment by spensireli** [comment]
@jn1119 exactly this :) ! This would provide capabilities for researchers to grant access and share data to different buckets and projects directly from service work bench. In our use case users won't necessarily be technical heavy but have a need to be able to share data and use that data with the tools in service work bench.

**Comment by kpark277** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.
