### ISSUE TITLE
Creating an AWS account with AppStream enabled 

### ISSUE THREAD

**Issue by liamcoatman** [awslabs/service-workbench-on-aws#769]
I'm following through the [documentation](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/Service_Workbench_Post_Deployment_Guide.pdf) for creating a new AWS hosting account from SW with AppStream enabled. 

What value should I enter for `AppStreamImageName`? The documentation only talks about what to do when onboarding an existing account (i.e. creating an image in the hosting account) but this doesn't make sense when the hosting account doesn't exist yet. 
  

 - Release Version installed - 4.0.0

**Comment by nguyen102** [comment]
Ah sorry about this, this is a mistake in our documentation. AppStream Image should be built in the `main` account, not the `member` account. We'll make a fix for this in our documentation.

**Comment by liamcoatman** [comment]
No worries. That makes sense. Thanks @nguyen102

**Comment by nguyen102** [comment]
Doc fix has been merged
