### ISSUE TITLE
[Misc] User access logs

### ISSUE THREAD

**Issue by sbalian** [awslabs/service-workbench-on-aws#785]
Is there a way to see study access logs by SW user? For example, I would like to know if user X made a read request to the data stored in study Y.

 - Release Version installed [e.g. v1.0.3]

**Comment by sbalian** [comment]
Sorry, figured this out.

**Comment by carvantes** [comment]
Hi,

Sorry for the delayed response. Glad that you figured it out. Still, here's one tip:
You can use the audit logs to find out which studies were mounted to which workspaces and which user owned them.
Once a workspace is created and a study is mounted, there are no logs for when a specific file is accessed, but we know that the user was able to access all the files from the study.

The following ClouwdWatch Logs Insights query may be a good starting popint:
```
log-group-names: /aws/lambda/va-swb-backend-<stage>-apiHandler

fields actor, body.studyIds.0, body.studyIds.1, body.studyIds.2, body.studyIds.3, body.studyIds.4
| filter logEventType = 'audit' and action = 'create-environment-sc'
```

**Comment by sbalian** [comment]
Thanks!
