### ISSUE TITLE
[Misc] Hello example for code customization not working

### ISSUE THREAD

**Issue by carvantes** [awslabs/service-workbench-on-aws#788]
**What's on your mind?**
The code customization example at https://github.com/awslabs/service-workbench-on-aws#code-customization is not working.

By default you get the following error when visiting `/hello`: https://reactjs.org/warnings/invalid-hook-call-warning.html

The root cause is "3. You might have more than one copy of React in the same app." and can be worked around by manually ensuring that `@aws-ee/base-ui` and `@aws-ee/ui` use the exact same `react` version (i.e. pinning react to the exact same version, deleting node_modules and re-running `pnpm`). This should ideally be solved by declaring react as a peer dependency.

Once that is fixed `/hello` still fails with:
```
Error: MobX injector: Store 'helloStore' is not available! Make sure it is provided by some Provider
```

Is the hello sample code correct? 
Would it be possible to add more instructions if anything needs to be configured to run the hello page?

Also, why is the `/hello` page reachable by default? It's a bit odd that sample code is accessible on a prod deployment.

**Versions (please complete the following information):**
 - 4.0.2 (latest at the time of writing this)

**Comment by jxuamazon** [comment]
packages/controller/lib/plugins/routes-plugin. was not registered in "route" in src/lambdas/plugins/plugin-registry.js   

Once added, the hello plugin works .

**Comment by maghirardelli** [comment]
We have added this issue to our backlog to look into. We will update here when any progress has been made.
