### ISSUE TITLE
[Misc] Logging in as a local user when federated login is enabled

### ISSUE THREAD

**Issue by liamcoatman** [awslabs/service-workbench-on-aws#792]
In our first deployment of SW we used local users only. We then added Google as an IdP and redeployed SW. When I navigate to the CloudFront URL I now see a "Login" button which takes me to the Google login flow (previously there was a username and password box). My question is - with an IdP configured is it still possible to login as local user? I want to be able to login to SW as a local user so I can add federated users, but this is not currently possible. Am I missing something? 

- Release Version installed [e.g. v4.0.2]

**Comment by ssvegaraju** [comment]
Hi @liamcoatman, after adding an IdP, the internal auth will be available at this URL: `<cloudfront URL>/internal`.

**Comment by liamcoatman** [comment]
Thanks for the suggestion, but `<cloudfront URL>/internal` and indeed `<cloudfront URL>/any string` all redirect me to the same screen with the "Login" button that starts the IdP login flow.

**Comment by SanketD92** [comment]
Hi @liamcoatman, the correct URL to visit internal login page is this: `<cloudfront URL>/?internal` (notice the question mark)

**Comment by liamcoatman** [comment]
Thanks @SanketD92. This solves my problem.
