### ISSUE TITLE
Add support non-standard endpoints (e.g. GovCloud, Cn)

### ISSUE THREAD

**Issue by estebane22** [awslabs/service-workbench-on-aws#806]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to run this in GovCloud

**Describe alternatives you've considered**
N/A. Same features, just available for GovCloud

**Additional context**
N/A

**Comment by rsmayda** [comment]
Thank you for reporting this feature! It is currently on our roadmap

**Comment by estebane22** [comment]
Hi There! Wondering if there are any plans to make this available soon. Appreciate any information!

**Comment by kcadette** [comment]
Hi @estebane-frb, GovCloud support is planned to be included in the new version of Service Workbench and is tentatively planned for release at the end of 2022. Also please use the new repository at https://github.com/awslabs/solution-spark-on-aws
