### ISSUE TITLE
[Bug] Installation Guide PDF is blank

### ISSUE THREAD

**Issue by crashGoBoom** [awslabs/service-workbench-on-aws#840]
The current installation guide pdf is blank.

**To Reproduce**
1. Go to https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/Service_Workbench_Installation_Guide.pdf
2. The pdf has several pages but is blank both on Chrome and Safari and when downloaded.

<img width="1383" alt="Screen Shot 2021-12-20 at 11 28 54 AM" src="https://user-images.githubusercontent.com/17323411/146800239-f3b45e8c-9db6-4279-b74f-c1bafd67353f.png">

Previous releases work correctly:
https://github.com/awslabs/service-workbench-on-aws/blob/d0767904d21fa316c4af9df1a0b78f0e0044d320/docs/Service_Workbench_Installation_Guide.pdf

**Comment by nguyen102** [comment]
Thanks for bringing this to our attention! We're making a fix for that now. The fix is currently in `develop` ([link](https://github.com/awslabs/service-workbench-on-aws/blob/develop/docs/Service_Workbench_Installation_Guide.pdf)), and we'll be merging it into `mainline` soon.

**Comment by nguyen102** [comment]
Latest doc changes have been merged to mainline
https://github.com/awslabs/service-workbench-on-aws/commit/d8aa731d1b4115767e3e2c832cb49ea72841cfce
