### ISSUE TITLE
[Bug] CORS policy error after deployment

### ISSUE THREAD

**Issue by crashGoBoom** [awslabs/service-workbench-on-aws#846]
**Describe the bug**

Once the workbench is deployed and I visit the site it just hangs and asks me to refresh the page. CORS errors are in the network logs:

```
Access to fetch at 'https://[...].execute-api.us-east-1.amazonaws.com/sbx/api/authentication/public/provider/configs' from origin 'https://[...].com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**To Reproduce**
1. Deploy with environment-deploy.sh or manually deploy each step
2. Open the url for the new workbench

**Expected behavior**
Expect to see a user login page.

**Screenshots**
<img width="775" alt="Screen Shot 2021-12-21 at 4 43 52 PM" src="https://user-images.githubusercontent.com/17323411/147001410-b32d8306-2ebe-4394-8f79-0386cbd3de96.png">

**Versions (please complete the following information):**
 - Release Version installed [4.1.1]

Any help troubleshooting this would be very helpful. I am not seeing any CORS settings in the config files.  Thank you!

**Comment by crashGoBoom** [comment]
After leaving this overnight it finally now prompts for a user login. How long does it usually take after a deployment for the site to be functional? Thanks.

**Comment by jn1119** [comment]
Usually the website should be up immediately. I have seen that error come up when there is an issue on the backend side but not completely sure what would have been the cause. Do you seen any relevant error logs in CloudWatch that would help understanding what was going on around that time. 

Api Gateway Log Group: /aws/api-gateway/[region initial]-[solutionName]-backend-[stageName]
Lambda Log Group: /aws/lambda/[region initial]-[solutionName]-backend-[stageName]-apiHandler

**Comment by tdmalone** [comment]
For others coming across this - I had the same issue, after setting up a custom domain, when still trying to access the installation through the CloudFront domain. Only the custom domain gets configured for CORS.

This can be resolved (in a temporary hacky way) by adding the CloudFront domain to the `APP_CORS_ALLOW_LIST` env var on the `<region-short>-<solution-name>-backend-dev-apiHandler` Lambda function (CORS isn't handled by the API Gateway settings which was where I was originally looking). Make sure you don't include a trailing slash.
