### ISSUE TITLE
[Feature Request] Ability to support multiple CIDR ranges for template

### ISSUE THREAD

**Issue by thedavidwhiteside** [awslabs/service-workbench-on-aws#874]
**Is your feature request related to a problem? Please describe.**
By default you can only add one CIDR by default.  We need multiple CIDR ranges for example 172.17.0.016,192.168.0.1/16 for the AccessFromCIDR.

**Describe the solution you'd like**
The ability to specify multiple CIDR ranges, for example 172.17.0.016,192.168.0.1/16.

**Describe alternatives you've considered**
Editing the cloud formation templates directly to use multiple ranges.

**Comment by Bingjiling** [comment]
Hi @thedavidwhiteside, 

Thanks for reaching out! 

The CIDR range can be updated to include multiple ranges after the environment is provisioned. I'm not sure if that would unblock you on this issue? Or if you're specifically looking for a way to set multiple ranges when provisioning an environment? 

Thanks,
Yanyu

**Comment by thedavidwhiteside** [comment]
> 

We have multiple CIDR ranges that need to be allowed.  Users are not really aware of what CIDR ranges to add, so as a short term solution we have provided a list of CIDR ranges for users to add at launch/provision, but long term we need a way for multiple CIDR ranges by default.

**Comment by Bingjiling** [comment]
Got it! I'll create a ticket for this request in our backlog. Thanks for your input!

**Comment by kpark277** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.
