### ISSUE TITLE
[Bug] Current stable Node version fails installation with error 'Uploaded file must be a non-empty zip'

### ISSUE THREAD

**Issue by crabba** [awslabs/service-workbench-on-aws#879]
**Describe the bug**
Node versions higher than v14 cause installation to fail during preDeployment==>PreDeploymentLambdaFunction with error "**Uploaded file must be a non-empty zip**"

The current [recommended version](https://nodejs.org/en/) of node is v16.  Installation using the default current version of node will therefore fail.  SWB documentation refers to 'Node.js v12 or later' in the following files:

[README.md](https://github.com/awslabs/service-workbench-on-aws/blob/a48588803c7333f86b444b3e318c3d6b9a840df5/README.md?plain=1#L82)
[docs/docs/deployment/pre_deployment/prereq_commands.md](https://github.com/awslabs/service-workbench-on-aws/blob/a48588803c7333f86b444b3e318c3d6b9a840df5/docs/docs/deployment/pre_deployment/prereq_commands.md?plain=1#L11)
[addons/addon-base/packages/serverless-go-build-tools/README.md](https://github.com/awslabs/service-workbench-on-aws/blob/a48588803c7333f86b444b3e318c3d6b9a840df5/addons/addon-base/packages/serverless-go-build-tools/README.md?plain=1#L9)
[addons/addon-base-raas/packages/serverless-packer/README.md](https://github.com/awslabs/service-workbench-on-aws/blob/a48588803c7333f86b444b3e318c3d6b9a840df5/addons/addon-base-raas/packages/serverless-packer/README.md?plain=1#L5)
[addons/addon-base-ui/packages/serverless-ui-tools/README.md](https://github.com/awslabs/service-workbench-on-aws/blob/a48588803c7333f86b444b3e318c3d6b9a840df5/addons/addon-base-ui/packages/serverless-ui-tools/README.md?plain=1#L5)

Note that [docs/docs/installation_guide/installation/cloud9install.md](https://github.com/awslabs/service-workbench-on-aws/blob/a48588803c7333f86b444b3e318c3d6b9a840df5/docs/docs/installation_guide/installation/cloud9install.md?plain=1#L67) refers to `nvm install lts/erbium` which is [v12](https://nodejs.org/en/about/releases/).

**To Reproduce**
1. Install the current default version of Node from [nodejs.org](https://nodejs.org/en/download/) (currently v16) or [nvm](https://github.com/nvm-sh/nvm) (currently v17)
2. Configure SWB and run `environment-deploy.sh`
3. Installation will fail with message 'Uploaded file must be a non-empty zip'

**Expected behavior**
Successful installation

**Versions (please complete the following information):**
 - Node versions >= 16 cause this error
 - Node version 14 works reliably

**Additional context**
The bug is caused by the [archiverjs/node-archiver](https://stackoverflow.com/questions/65916681/uploaded-file-must-be-a-non-empty-zip-service-awslambdainternal-status-code) dependency used within Serverless and was initially reported Jaunuary 2021. 

Recommend that the installation docs change all references to installing Node to state that Node v14 should be used.  This text can be removed when the dependency issue is resolved.

**Comment by Bingjiling** [comment]
Hi Andrew, 

Thanks for reaching out! 

I just created a spike on SWB compatibility with Node 16. I'll talk to the team to decide if we want to prioritize Node 16 compatibility, if not, I'll update the documentation on supported Node versions. 

Thanks,
Yanyu

**Comment by Bingjiling** [comment]
Documentation has been updated to reflect Node v14 instead of v12 and up.

**Comment by portisto** [comment]
@Bingjiling , can you pls point to this documentation? I'm using the Service_Workbench_Installation_Guide.pdf and I don't see anything about the version of node in there.

**Comment by maghirardelli** [comment]
After v5.2.3, you should be able to deploy with Node 16 too.
