### ISSUE TITLE
[Feature Request] Enable custom usernames for SSH connections

### ISSUE THREAD

**Issue by raids** [awslabs/service-workbench-on-aws#920]
**Is your feature request related to a problem? Please describe.**
It doesn't seem possible to customise which username to use for SSH connections. For example, Ubuntu-based AMIs use the `ubuntu` username, or maybe we would like to create a custom username while building AMIs.

**Describe the solution you'd like**
We've noticed that there is some plumbing already implemented for custom usernames, e.g. [here](https://github.com/awslabs/service-workbench-on-aws/blob/ed2e7dc60a35a12a8f14f55964ade66a88e38298/addons/addon-base-raas/packages/base-raas-services/lib/environment/service-catalog/environment-sc-connection-service.js#L315) it defaults to `ec2-user` if `sshConnectionInfo.instanceOsUser` isn't passed, but from what we could see, it doesn't look like the API endpoint `'/:id/connections/:connectionId/send-ssh-public-key'` or any other functions accept/expect `instanceOsUser`. Ideally, this implementation thread would be finished and we could have a way to pass this parameter through to the backend and EC2 instance connect.

We're open to other suggestions, I expect we're not the first ones to try and use a different username.

**Describe alternatives you've considered**
* find and replace `ec2-user` with `ubuntu`, but it's all over the js and bash bootstrap scripts and we'd rather not fork the repo
* provision a new user named `ec2-user` on the AMIs we build. This is also not ideal, but probably easier than the other option

**Additional context**

**Comment by maghirardelli** [comment]
We have added this request to our backlog! Thank you for reaching out.

**Comment by kpark277** [comment]
Thank you for reaching out. Your request has been added to our backlog for research computing solutions. Our team curates these requests for fit with our solutions vision on a regular basis. Please watch this space for new updates. If you require immediate assistance, please reach out to your AWS account team. Please note that security issues should be reported directly to AWS Security at aws-security@amazon.com.
