### ISSUE TITLE
[Bug] the studies data cannot be mounted on EMR workspace type in Hongkong region

### ISSUE THREAD

**Issue by dengmingtong** [awslabs/service-workbench-on-aws#922]
**Describe the bug**
After I create emr workspace type, I found the studies data is not mounted to emr node.
In emr node /tmp folder, there is no get_bootstrap.sh file.

Region: Hongkong

**Comment by SanketD92** [comment]
This seems to be a unique issue for Hong Kong region. I was able to debug using an EMR instance in this region and locate the [source](https://github.com/awslabs/service-workbench-on-aws/blob/fec1c92a108f275fa68dffd308acff518c33c43d/main/solution/post-deployment/config/environment-files/get_bootstrap.sh#L9) of the error. 

Reading a boto [issue](https://github.com/boto/boto3/issues/2098) speaking about a similar error, I was able to make the command work by adding the region flag like so:
```
sudo aws s3 sync "$bootstrap_s3_location" "$INSTALL_DIR" --region "ap-east-1"
```

Please update the script, deploy the application, and create a new EMR instance with studies mounted.

**Comment by dengmingtong** [comment]
The issue has been fixed according you SanketD92 suggestions
Thank you very much
