### ISSUE TITLE
[Bug] Connecting to Rstudio workspace errors with "parameter not found" 

### ISSUE THREAD

**Issue by mbussa** [awslabs/service-workbench-on-aws#923]
**Describe the bug**

 Connecting to Rstudio workspace errors with "parameter not found" 

**To Reproduce**
1. Go to '...' new created rstudio workspace
2. Click on 'connect 
4. you will see something went wrong and further troubleshooting "parameter not found" erro 

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]
 - latest install of SWB and Studio templates.

**Additional context**

**Comment by mbussa** [comment]
Set rstudio-user password
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 8787 after 17 ms: Connection refused
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https:/
/docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --value: expected one argument
Stored rstudio public key in SSM

**Comment by SanketD92** [comment]
Fix specified in this [comment](https://github.com/RLOpenCatalyst/Service_Workbench_Templates/issues/10#issuecomment-1016925882), please use this while creating your RStudio AMI. Reached out to Relevance Labs team member [Manikandan](https://github.com/manikandan-thangavelu-rl) for the fix to be merged.

No code changes needed on Service Workbench repo, closing issue.
