### ISSUE TITLE
[Bug] Timeout issue

### ISSUE THREAD

**Issue by avillach** [awslabs/service-workbench-on-aws#924]
**Describe the bug** Session Expired message while working on SWB creating a study

**To Reproduce**
This is the pop up I got yesterday in SWB while I was creating some studies. I was typing and this popped up and I had to log in again and re-do what I was doing. 

**Expected behavior**
![image](https://user-images.githubusercontent.com/4821297/154186993-ba5df8fc-12bb-44bf-9aa2-ee710d69af63.png)

**Screenshots**

**Versions (please complete the following information):**
v 4.3.1

**Additional context**

**Comment by SanketD92** [comment]
This is a security feature. Service Workbench currently does not refresh access tokens, therefore it has to automatically log the user out when their current token expires. 

To increase the expiration timeout of your token:
- Legacy internal authentication (pre-v5.0.0): Create a `<stage>.yml` file in `main/solution/backend/config/settings/` folder and set your `jwtOptions` body with a custom `expiresIn` value (for reference, take a look at `main/solution/backend/config/settings/.defaults.yml`).
- non-internal authentication: Please update your IdP/native Cognito user pool configuration accordingly.
