### ISSUE TITLE
[Bug] Cognito email validation is too strict (TLD can be more than 3 letters)

### ISSUE THREAD

**Issue by manics** [awslabs/service-workbench-on-aws#926]
**Describe the bug**
`PreSignUpLambda` for verifying user emails in AWS Cognito is too strict, and doesn't allow all gTLDs.

**To Reproduce**
1. Deploy SWB, go to the AWS Cognito user pool
2. Create a new user using an email address such as `example@example.scot`
3. This fails `PreSignUpLambda` due to the regex requiring the last component of the domain to be 2 or 3 characters:
   https://github.com/awslabs/service-workbench-on-aws/blob/fec1c92a108f275fa68dffd308acff518c33c43d/main/solution/post-deployment/config/infra/cloudformation.yml#L526-L527
4. Note there is no error when creating a user in SWB using the same email address, only when adding the user in Cognito.

**Expected behavior**
All email addresses should be accepted by the Cognito verifier, include gTLDs longer than 3 characters.

~~**Screenshots**~~

**Versions (please complete the following information):**
 - v5.0.0

~~**Additional context**~~

**Comment by maghirardelli** [comment]
@manics -- fix has been merged into mainline from #928. Closing issue.
