### ISSUE TITLE
[Bug] Unable to launch EMR with AppStream enabled

### ISSUE THREAD

**Issue by gazzyt** [awslabs/service-workbench-on-aws#927]
**Describe the bug**
Launching an EMR workspace within an environment configured with `isAppStreamEnabled: true` fails with the following error:

    Error provisioning environment DevWorkspace01. Reason: AmazonCloudFormationException Parameter 'AccessFromCIDRBlock' must contain at least 9 characters

**To Reproduce**
1. From Studies
2. Select a study
3. Launch an EMR workspace

**Expected behavior**
The workspace should launch successfully. Running the same test in an environment with `isAppStreamEnabled: false` produces a working workspace.

**Screenshots**

**Versions (please complete the following information):**
 - v4.3.1

**Additional context**
My environment configuration:

    awsRegion: eu-west-1
    awsProfile: sw
    solutionName: sw-d
    envType: dev
    isAppStreamEnabled: true

I have attempted to fix this myself with each fix leading to a different issue. Here is what I did:

1. Removed the `MinLength` requirement from `AccessFromCIDRBlock`. This fixed the immediate problem and started a cluster launching which later failed.
2. Attached the security group `${SolutionNamespace}-WorkspaceSG`. This fixed the issue of being unable to access the KMS VPC endpoint to retrieve the key.
3. Allow S3 access to the Amazon Linux and EMR repos as detailed here https://docs.aws.amazon.com/emr/latest/ManagementGuide/private-subnet-iampolicy.html
4. Remove all the `BootstrapActions` to rule those out.

You can see these changes here: https://github.com/gazzyt/service-workbench-on-aws/commit/20992c4a6fcf17f47f60974c835440ff2b64ecc3

These left me with a cluster which launches, spends about 40 minutes trying to bootstrap and then terminates. The error is:

    ElasticMapReduce Cluster with Id j-1UPL8DQFW92A4, is in state STARTING and did not stabilize due to the following reason: {}

I was able to ssh onto the master node to review the logs but nothing stood out as an obvious cause.

I am now wondering if this is even possible although this page seems to imply it is but I can't make it work: https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-clusters-in-a-vpc.html#emr-vpc-private-subnet
Everything else seems to say you need a NAT instance which would seem to defeat the purpose of a secure research environment.

A couple of other experiments I tried:
1. Use the console to launch an EMR cluster in the SWB private subnet. The console offered to create a NAT instance as it detected no route to the internet. I declined this and ended up with a self-terminating cluster as before.
2. Use EMR version 5.30 as this version seems to have a change related to private subnets but it made no difference. I did see port 9443 added to the security groups though as mentioned here https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-man-sec-groups.html.

I am out of ideas at this point but maybe this info will help others progress.

**Comment by maghirardelli** [comment]
Hello @gazzyt! 

EMR is not currently supported in our TRE SWB deployments. This was a design choice, and we will be updating the documentation to clearly reflect that this is not a bug. Thank you for bringing this to our attention. Would you like me to convert this issue into a Feature Request to have EMR supported in TRE/AppStream environments in the future?

**Comment by gazzyt** [comment]
Hi @maghirardelli 
Thanks for the reply. I think for the moment it is enough to know that this is not supported.
