### ISSUE TITLE
[Misc] Plugin example "Hello" store injection error

### ISSUE THREAD

**Issue by jxuamazon** [awslabs/service-workbench-on-aws#929]
**Describe the bug**
First of all, need clear documentation on how to enable the "hello" plugin example in the code base:

After going through the code, I was able to enable "hello" in the NavMenuItems , but the page produce the following error 

"Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem."

**To Reproduce**
Steps to reproduce the behavior:  modify the following files 
main/packages/controllers/lib/plugin/routes-plugin.js - route /api/hello to hello-controller
main/solution/backend/src/labda/api-handler/plugins/plugin-registry - need to add the "packageRoutesPlugin in "route"
main/solution/ui/src/helpers/api.js - enable the API
main/solution/ui/src/plugins/app-context-items-plugin.js - register hell store in context
main/solution/ui/src/plugins/menu-items-plugin.js - add /hello to the menu
main/solution/ui/src/plugins/routes-plugin.js - register /hello to the routesMap

**Expected behavior**
Expect to see hello messages. 

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]

**Additional context**

**Comment by maghirardelli** [comment]
Hello @jxuamazon!

Per Issue #788, it is known that the hello customization examples are not currently working. See that issue for additional context. We have a backlog item to address this. Thank you for your issue!
