### ISSUE TITLE
[Bug] External study mount fails cross region with AppStream enabled

### ISSUE THREAD

**Issue by gazzyt** [awslabs/service-workbench-on-aws#932]
**Describe the bug**
Service Workbench allows the creation of external Data Sources in any region and these can be attached to Workspaces. If AppStream is enabled and the Workspace and external Data Source are in different regions then the studies fail to mount when connecting to the workspace.

**To Reproduce**
1. Deploy Service Workbench in region A (eu-west-1 in my case) with isAppStreamEnabled: true and enableEgressStore: true
2. Setup an external study via the Data Source UI to an S3 bucket in an external account in region B (eu-west-2 in my case)
3. Wait until the Study status is Available
4. In the Studies UI, select the study you created and launch an EC2 Linux workspace
5. Connect to the workspace via the usual AppStream/Putty process
6. Observe that the login login is very slow and shows an error message (see screenshots)

**Expected behavior**
Study is mounted successfully

**Screenshots**
The error message:

![external-study-01](https://user-images.githubusercontent.com/366998/155138555-67d27e0b-f50f-499f-a6aa-6a0feb23da06.png)

Contents of syslog:

![external-study-02](https://user-images.githubusercontent.com/366998/155138697-b1f06f9c-8c4c-44e9-b0f5-0d459ce9e3b9.png)

Checking connectivity:

![external-study-03](https://user-images.githubusercontent.com/366998/155138752-3c3f12f1-9a48-4555-a46b-1632c8038a1b.png)

**Versions (please complete the following information):**
 - v4.3.1

**Additional context**
This seems to be caused by the S3 Gateway endpoint in the hosting account which can only access services in the same region as the VPC.

**Comment by Bingjiling** [comment]
Hi @gazzyt, 

Thanks for reaching out! We'll look into this issue. 

Thanks,
Yanyu

**Comment by nguyen102** [comment]
Hi @gazzyt,

SWB does not not support mounting external studies that are not in the same region as the SWB deployment if AppStream is enabled. AppStream workspaces does not have access to the internet and therefore we use [S3 VPC Endpoints](https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html) to connect the workspace to the S3 bucket. The endpoint does not support cross region requests.
