### ISSUE TITLE
[Bug] ERROR ValidationException: Rate exceeded” when you hit the Workspace Types page if you have lots of versions of a product in Service Catalog

### ISSUE THREAD

**Issue by jianjun66** [awslabs/service-workbench-on-aws#937]
**Describe the bug**
When you create lots of new versions of a product in Service Catalog ( in my case, 12 versions of SageMaker Notebook), AWS backend API will error out with “ERROR	ValidationException: Rate exceeded” when you hit the Workspace Types page. - this is due to  serviceCatalogClient.listProvisioningArtifacts({ ProductId: product.ProductId }).promise(),   gets called too many times in a short burst.  I think this is a bug that needs to be fixed

**To Reproduce**
1. cretate 10 versions of a workspace type , 
2. Go to 'workspaces types'
3. See error

**Expected behavior**
Should see the list of Service Catalog items

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]
V5.0

**Additional context**

**Comment by Bingjiling** [comment]
Hi @jianjun66 ,

Thanks for reaching out! We'll take a look into this issue.

Thanks,
Yanyu

**Comment by Bingjiling** [comment]
Hi @jianjun66,

We're working on pagination to address scaling issues in SWB, and a ticket has been created in the backlog for this specific issue.

Thanks,
Yanyu
