### ISSUE TITLE
[Bug] CICD Pipeline Fails if Environment Is Not Already Deployed

### ISSUE THREAD

**Issue by gazzyt** [awslabs/service-workbench-on-aws#938]
**Describe the bug**
The policy applied to the deployer does not allow it to deploy the edge lambda as this is always in `us-east-1` while the other lambdas are in the chosen region for the environment (`eu-west-1` in my case). If the edge lambda does not already exist (e.g. from a previous manual deployment) then the pipeline tries to create it and fails with a permissions error.

**To Reproduce**
1. Create a config file for a new environment
2. Setup and deploy cicd-source
2. Setup and deploy cicd-pipeline
3. In AWS Console, observe that the pipeline has started a build
4. Deployment fails with error:

`An error occurred: RoleCloudFrontInterceptor - API: iam:CreateRole User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/dev-irl-sw-d-cicd-pipeline-AppDeployerRole-1BBIUPS6ATIWH/AWSCodeBuild-9ee91fcf-c2b2-448d-b139-c3255970434a is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::xxxxxxxxxxxx:role/dev-va-sw-d-edgeLambda-RoleCloudFrontInterceptor-FWWO3CFN90M0.`

**Expected behavior**
The deployment should succeed

**Screenshots**

**Versions (please complete the following information):**
 - v5.0.0 (mainline commit 4b2658950b9565a7f5e0074031ce1a4625aedc7a)

**Additional context**
We hit other missing permissions once the first is granted as follows:

`An error occurred: EdgeLambda - Resource handler returned message: "User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/dev-irl-sw-d-cicd-pipeline-AppDeployerRole-1BBIUPS6ATIWH/AWSCodeBuild-ce4eddca-093b-4d87-8c45-31a2e6ec2198 is not authorized to perform: lambda:CreateFunction on resource: arn:aws:lambda:us-east-1:xxxxxxxxxxxx:function:dev-va-sw-d-edgeLambda-EdgeLambda-cgviGgFimY4v because no identity-based policy allows the lambda:CreateFunction action (Service: Lambda, Status Code: 403, Request ID: 61e8e441-a059-43af-82ad-5a022a7a1263, Extended Request ID: null)" (RequestToken: e5ca95ab-a5e9-d090-e34f-13587ccacfa0, HandlerErrorCode: AccessDenied).`

`An error occurred: EdgeLambda - Resource handler returned message: "User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/dev-irl-sw-d-cicd-pipeline-AppDeployerRole-1BBIUPS6ATIWH/AWSCodeBuild-78001c86-ac5a-4ac3-a4be-b785011f101e is not authorized to perform: iam:PassRole on resource: arn:aws:iam::xxxxxxxxxxxx:role/dev-va-sw-d-edgeLambda-RoleCloudFrontInterceptor-J4E5VOR16HN2 because no identity-based policy allows the iam:PassRole action (Service: Lambda, Status Code: 403, Request ID: ad648fab-e578-4edd-9a35-1d3715027d58, Extended Request ID: null)" (RequestToken: 13ffc13f-7622-e3e4-54c7-d504488a80bc, HandlerErrorCode: AccessDenied).`

**Comment by Bingjiling** [comment]
Hi @gazzyt ,

Thanks for reaching out! We'll look into this issue. 

Thanks,
Yanyu
