### ISSUE TITLE
[Bug] Workspace Status Unknown after Starting

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#948]
When a workspace is stopped, and then restarted, the returned status is `STARTING_FAILED`, causing the workspace to display 'unknown' in the UI. More critically, this causes the connect button to fail when clicked, returning a 'Something went wrong' message and json response like, `{"requestId":"","code":"ValidationException","message":"Something went wrong"}`. There's also an error in the `wf-start-sagemaker-environment-sc` workflow for this user, which states, `A "wait" decision with its check function checkNotebookStarted() reached its maximum number of attempts "120".`

We can resolve this issue by changing the Status in DynamoDB from `STARTING_FAILED` to `COMPLETED`, which returns it to a state that can be connected to and interacted with normally.

**To Reproduce**
Workspace Settings:
- Workspace Type: SageMaker Notebook-v3
- Configuration Name: Sagemaker_Large
- Instance Type: ml.t2.2xlarge

1. On a stopped workspace, click the 'Start' button.

**Expected behavior**
GIVEN the workspace is in the stopped state
WHEN the start button is clicked
THEN the workspace should start and become available for connection.

**Screenshots**
Unknown status and mouseover message:
![unknown-swb](https://user-images.githubusercontent.com/21109191/157916013-ed28829a-1129-4c63-9ea8-cf3eeaf63063.jpg)

On connect click, error message:
![unknown-swb-connect](https://user-images.githubusercontent.com/21109191/157916010-1c732b83-debc-456d-8079-90330ec2444c.jpg)

User stop workflow item:
![unknown-swb-workscreen-stop](https://user-images.githubusercontent.com/21109191/157920036-6b7ad74a-0c1e-4466-83d5-5d3d625f9536.jpg)

User start workflow item:
![unknown-swb-workscreen-start](https://user-images.githubusercontent.com/21109191/157920030-5abd151e-99b5-4b77-b8e1-15dea9d35ade.jpg)

**Versions (please complete the following information):**
 - Service Workbench - Version 4.3.1 (2022-02-01)

**Additional context**
Does not seem to happen with every notebook generated with these specs, or the exact right conditions are not being met to cause this to occur each time.

**Comment by Bingjiling** [comment]
Hi @srpiatt , 

Thanks for reaching out! 

Looks like the SageMaker did not restart successfully within the expected time. To avoid the workspace getting stuck in 'STARTING' status forever, the status is then updated to 'STARTING_FAILED', so attention is called upon to fix the issue. 

Have you checked if the underlying workspace started successfully? 

Thanks,
Yanyu

**Comment by avillach** [comment]
Hi Yanyu, I work with Samantha. 
yes, changing "by hand" the dynamo Database resolved the issue for this workspace. 
The main problem is that this issue happened **6 times in the past 2 weeks on different sagemaker notebooks.** 
We have 20 students using each one notebook in class and since we upgraded to v4.3.1  OR when using Sagemaker notebook-v this issue happened 
Thanks!
Paul

**Comment by srpiatt** [comment]
As a follow up, it looks like on one of the instances that we currently have in 'unknown' status in the SWB UI (which occurs after a stopped instance has failed on start command), is listed as 'stopped' in the AWS console under Amazon SageMaker Instances. This leads me to believe that the notebook did not start correctly. I have not tested if this is the case for every notebook that ends up in 'unknown' status.

Is there any particular place we could look for more debugging information to help find the root cause of this issue?

**Comment by nguyen102** [comment]
@avillach  were you on `v4.3.0` before upgrading to `v4.3.1`. If yes, I don't think the changes in `v4.3.1` should affect Sagemaker.

Is the Sagemaker workspace that you're using the default Sagemaker workspace that SWB comes with? I'm wondering if there was a customization that was made to the workspace that caused the notebook to take longer to start. 
The [code](https://github.com/awslabs/service-workbench-on-aws/blob/c30c55f50b7aae7dd4dde5ebf340038dca907996/addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/start-sagemaker-environment/start-sagemaker-environment-sc.js#L61) waits a maximum of 5 * 120 seconds for Sagemaker to start. 

Can you try checking how long it's taking Sagemaker to start from a stopped state? If it's taking longer than 10 minutes, I would try increase the wait time.

**Comment by srpiatt** [comment]
@nguyen102 We were on v4.3.0 before, yes. And, we are using the default Sagemaker workspace.

Where would I look to find how long Sagemaker is taking during the startup phase? Is there logging output on the start/stop times and errors?

Also, Is the documentation for customizing wait time in the User guides?

**Comment by raids** [comment]
I've also experienced this issue for EC2 instances when AWS was not able to fulfil the request to start the instance due to a lack of capacity.

1. In SWB, start an EC2 workspace which is currently in a stopped state in the SWB UI
2. In SWB, it goes into a `STARTING` state, then `UNKNOWN`
3. In AWS, the instance is `Stopped`
4. In AWS, try and start the instance, receive an error from AWS: `InsufficientInstanceCapacity`

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-launch.html#troubleshooting-launch-capacity

For what it's worth, if an instance is in a state where a request to start it _can_ be made, i.e. `Stopped`, we would probably prefer the behaviour of SWB to be to mirror that as opposed to setting a status of `STARTING_FAILED`. Are we able to customise this behaviour, perhaps by editing the workflow?

**Comment by nguyen102** [comment]
@srpiatt You can change the code at this [line](https://github.com/awslabs/service-workbench-on-aws/blob/c30c55f50b7aae7dd4dde5ebf340038dca907996/addons/addon-environment-sc-api/packages/environment-sc-workflow-steps/lib/steps/start-sagemaker-environment/start-sagemaker-environment-sc.js#L61). Right now the workflow waits for 5 * 120 seconds for the Sagemaker notebook to start up. Try changing the `5` to `10`. This will give the notebook 20 minutes to start up before failing.

@raids We're working on improving SWB and a ticket has been added to our backlog to have the instance state reflect the status of the instance in AWS.
