### ISSUE TITLE
GitHub not working on workspaces with studies linked to an s3 bucket

### ISSUE THREAD

**Issue by aGutierrezSacristan** [awslabs/service-workbench-on-aws#949]
**Describe the bug**
Within the studies folder in SWB, we can see all the studies we have linked to s3 buckets, but we cannot work with Github in any of these folders within the studies folder. We cannot clone, push or pull anything to Github.
We can clone/push and pull from any other folder in our SWB research workspace (if not linked to s3 buckets). 

**To Reproduce**
Workspace Settings:
- Workspace Type: SageMaker Notebook-v3 
         - Studies linked to an s3 bucket
- Configuration Name: Sagemaker_Large
- Instance Type: ml.t2.2xlarge

1. Open a terminal in SageMaker, on the study linked to an s3 bucket
2. git clone your repository
3. error: "cannot pread pack file: No such file or directory"; "Index-pack failed" (see screenshot below) 

**Expected behavior**
git clone, git pull and push worked fine when running it in any other folder that is not linked to s3

**Screenshots**
Error message got when trying to clone a GitHub repository on a study folder in oour workspace linked to an s3 bucket
![thumbnail_image](https://user-images.githubusercontent.com/19646530/157963122-cfddf176-7c48-4864-96aa-92c84b13eb69.png)

Same git clone command run in the same SWB workspace but in another folder not linked to s3, working fine
![Screen Shot 2022-03-11 at 3 54 55 PM](https://user-images.githubusercontent.com/19646530/157963952-f6e7fa6d-9fb5-4eb9-943c-a6b2733307c5.png)

**Versions (please complete the following information):**
Service Workbench - Version 4.3.1 (2022-02-01)

**Comment by Bingjiling** [comment]
Hi @aGutierrezSacristan , 

Thanks for reaching out! 

Support for GitHub actions in a study folder is not in scope for SWB. That being said, I'm curious the use case for cloning a GitHub repository in a folder that's synced with S3? Usually, GitHub is used for version control for source code and S3 is used for storing data, they would reside in different folders. 

Thanks,
Yanyu

**Comment by aGutierrezSacristan** [comment]
Hi @Bingjiling thanks for letting us know. We use it for research and for teaching purposes, so when we work on Sagemaker on our folder sync with s3 we need to push to GitHub the updates on our work. We are experiencing other issues in the sync folder not only with GitHub, but with some tools we need to use that need to write, so probably not GitHub related. Also to give more context on this, we are admin on those folder, and we have read and write permissions.

**Comment by nguyen102** [comment]
I'm currently looking into why GH doesn't work with a study folder. 

In the meantime, have you considered cloning your GH repo into the Sagemaker workspace (`/home/ec2-user`) and running your code from there? Your GH code in the Sagemaker workspace can reference the study data in the study folder. 

The study folder is where you should store research data that can be shared with other users. The Sagemaker workspace  is where you should run your code. To share code with other researchers, you should push the code changes to GH, and then other researchers can pull the updated code from GH.

**Comment by aGutierrezSacristan** [comment]
Hi @nguyen102 thank you so much!

**Comment by nguyen102** [comment]
I think the the error you mentioned is a limitation with using [goofys](https://github.com/kahing/goofys). We use `goofys` to mount studies to Sagemaker. Goofys does not support storing file permissions, which GIT requires. 

I would recommend not using the study folder to store your code. You can store your script and code on Sagemaker's home directory. If needed, you could copy the script to the study folder once you finish editing the script. 

Preferably you would use GH to store your code and share it with other researchers/students that way.
