### ISSUE TITLE
[Bug] Study role sts:AssumeRole permissions not being added

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#957]
**Describe the bug**
When launching a new workspace, the instance role is missing `sts:AssumeRole` permissions for the study role (`swb-study-*`). This is preventing the egress store from mounting on login.

**To Reproduce**
1. Launch a Linux workspace (doesn't have to be from a study; the same problem occurs whether or not a study is linked to the workspace at launch)
2. Start an SSH session to the new box 
3. Observe the following error:
```
Last login: Tue Mar 29 03:09:42 UTC 2022 on pts/0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0   4217      0 --:--:-- --:--:-- --:--:--  5000
Bucket region is not specified. Defaulting to "ap-southeast-2" for mounting
Mounting external study "egress-store-75dbe6bc-da79-4305-8f29-fb20baad7b8b" at "/home/ec2-user/studies/egress-store-75dbe6bc-da79-4305-8f29-fb20baad7b8b" using role "arn:aws:iam::XXXXXXXXXXXX:role/swb-study-75dbe6bc-da79-4305-8f29-fb20baad7b8b", kms arn "arn:aws:kms:ap-southeast-2:XXXXXXXXXXXX:role:key/6e3a9e93-c801-4ba4-ab47-2f44de632fbf" and region "ap-southeast-2"
2022/03/29 03:10:05.351233 main.FATAL Unable to mount file system, see syslog for details
[ec2-user@ip-10-0-25-22 ~]$
```

Syslog (in `/var/log/messages`) doesn't have much more information:
```
Mar 29 03:29:58 ip-10-0-25-22 /usr/local/bin/goofys[32127]: s3.INFO Falling back to v2 signer
Mar 29 03:29:58 ip-10-0-25-22 /usr/local/bin/goofys[32127]: main.ERROR Unable to access 'XXXXXXXXXXXX:role-dev-syd-YYYYYYYY-egress-store': permission denied
Mar 29 03:29:58 ip-10-0-25-22 /usr/local/bin/goofys[32127]: main.FATAL Mounting file system: Mount: initialization failed
```

**Expected behavior**
I expected the egress store to mount successfully.

NOTE: The specific issue here can be confirmed by manually adding the necessary permission:
```
{
  "Effect": "Allow",
  "Action": "sts:AssumeRole",
  "Resource": "arn:aws:iam::XXXXXXXXXXXX:role/swb-study-75dbe6bc-da79-4305-8f29-fb20baad7b8b"
}
```
to the inline policy `analysis-YYYYYYYY-test-1648520171082-s3-bootstrap-script-policy` on the instance's role.

Mounting then succeeds:
```
Last login: Tue Mar 29 03:30:24 UTC 2022 on pts/0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0  14150      0 --:--:-- --:--:-- --:--:-- 15000
Bucket region is not specified. Defaulting to "ap-southeast-2" for mounting
Mounting external study "egress-store-75dbe6bc-da79-4305-8f29-fb20baad7b8b" at "/home/ec2-user/studies/egress-store-75dbe6bc-da79-4305-8f29-fb20baad7b8b" using role "arn:aws:iam::XXXXXXXXXXXX:role:role/swb-study-75dbe6bc-da79-4305-8f29-fb20baad7b8b", kms arn "arn:aws:kms:ap-southeast-2:XXXXXXXXXXXX:role:key/6e3a9e93-c801-4ba4-ab47-2f44de632fbf" and region "ap-southeast-2"
[ec2-user@ip-10-0-25-22 ~]$
```

And from syslog:
```
Mar 29 03:30:31 ip-10-0-25-22 /usr/local/bin/goofys[32287]: main.INFO File system has been successfully mounted.
```

**Versions (please complete the following information):**
 - 5.0.0

**Additional context**
_Might_ be caused by something going wrong here?
https://github.com/awslabs/service-workbench-on-aws/blob/35f6cce3ccc301921ead742240c15c1a7e332f0c/addons/addon-base-raas/packages/base-raas-services/lib/helpers/iam/study-policy.js#L153-L162

**Comment by ssvegaraju** [comment]
Hi @tdmalone, thanks for bringing up this issue! I've added this to our team's backlog, and we'll update here when we have more information.

**Comment by tdmalone** [comment]
@ssvegaraju This is still an issue on a fresh install of SWB; how is this one going in the backlog?
