### ISSUE TITLE
[Misc] Cost data not available

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#959]
**What's on your mind?**
I'm not sure if I've missed setting something up, but after trying out Service Workbench for several weeks (with many workspaces being launched and terminated in that time), there isn't any cost data to view within the SW interface:

![image](https://user-images.githubusercontent.com/900469/161664265-7c1ecaf7-ba65-4b98-b99b-eb20e4779104.png)

This includes the dashboard as well as on individual workspace cards.

**Versions (please complete the following information):**
 - 5.0.0

**Comment by avillach** [comment]
did you activate the cost allocation tags?

**Comment by tdmalone** [comment]
@avillach Thanks for the fast reply and apologies for my delay. I see - I'll have to get that enabled at the payer level. That's likely the issue, thank you!
