### ISSUE TITLE
[Bug] Minor: pending workspace background colour is incorrect

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#968]
**Describe the bug**
The background colour used for pending workspaces is orange, the same as for Stopped workspaces:
![image](https://user-images.githubusercontent.com/900469/163307807-9d34846e-4b68-47f2-bc2a-5589a662a830.png)

For pending workspaces however, it should be yellow, to match the menu:
![image](https://user-images.githubusercontent.com/900469/163307958-dab5b32b-53ca-41cc-aff6-752592fa7a92.png)

**To Reproduce**
1. Go to Workspaces
2. Click on Create Research Workspace
3. Observe that while the workspace is launching, 'PENDING' shows with an orange background

**Expected behavior**
'PENDING' to display with a yellow background (or at least, a different background to 'STOPPED').

**Versions (please complete the following information):**
- 5.0.0

**Additional context**
This is obviously quite minor! Just something I noticed, that I thought I'd record. I will submit a PR.

**Comment by Bingjiling** [comment]
Hi @tdmalone ,

Thanks for your contribution! We're working on getting the PR merged. 

Thanks,
Yanyu
