### ISSUE TITLE
[Feature Request] Ability to customise cost reporting tags

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#975]
**Is your feature request related to a problem? Please describe.**
We're deploying Service Workbench into an AWS organisation that has stringent tagging requirements, around using specifically named tags (incl. `Environment`, `App` and `CostCenter`. Cost reporting across the organisation is already done using these tags.

Service Workbench deploys solutions with, and uses cost data from, the tags `Env`, `Proj`, and `CreatedBy`. These tags are hardcoded in a number of places across the Service Workbench codebase, and aren't trivial to change.

**Describe the solution you'd like**
The ability to customise the cost tracking tags that Service Workbench uses.

**Describe alternatives you've considered**
We have a Lambda hooked up to the `RunInstances` event to add the additional tags to instances Service Workbench launches,  and then we essentially just ignore the `Env`, `Proj` and `CreatedBy` tags elsewhere in the org. This solves one part of the problem, but solving the second part - having Service Workbench pull in cost data from those existing activated cost allocation tags - I think we could only achieve if we actually changed them throughout the codebase, which would be a bit hacky.

Thanks for your consideration!

**Comment by SanketD92** [comment]
Thank you for reporting this issue. We've created a ticket in our backlog.

**Comment by tdmalone** [comment]
As an additional use case for this, I also have another client that cannot enable additional cost allocation tags at the payer level on a per-project basis, because if they did it for every project billing would become unmanageable.

This means that this client can't access any billing data in SWB, unless we go through and change the hardcoded tag names.
