### ISSUE TITLE
[Feature Request] AWS WAF Deployment Option

### ISSUE THREAD

**Issue by spensireli** [awslabs/service-workbench-on-aws#977]
**Is your feature request related to a problem? Please describe.**
Today Service Workbench is deployed without AWS WAF.

**Describe the solution you'd like**
A deployment option or parameter that allows you to deploy AWS WAF with a base rulset of the OWASP top 10. 

**Describe alternatives you've considered**
Deployed AWS WAF separately and associated the ACL post deployment. 

**Additional context**
Extra protection of the resources seems like a cheap easy win. This is something we have added outside of Galileo but it would be nice if it was included in deploys.

**Comment by SanketD92** [comment]
Thank you for reporting this issue. We've created a ticket for this in our backlog.
