### ISSUE TITLE
[Feature Request] Production access to EMR workspace without a default password

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#981]
We cannot use EMR workspaces in productions because the password to access it is a hard coded default value.

Managing access using SWB credentials/authentication would be the preferred approach.

Is there a work around we can use, or is there a feature planned which should addresses this in the future?

For reference, please see the README document, which notes this default password.
https://github.com/awslabs/service-workbench-on-aws/blob/d48035f67b63a5f06e85470021fa484acbfa18bf/README.md?plain=1#L230

 - Release Version installed: Our forked copy is at version 5.0.0

**Comment by SanketD92** [comment]
Hi @srpiatt, thanks for creating this issue.

You're right, the EMR password is currently hardcoded and is baked into the AMI [here](https://github.com/awslabs/service-workbench-on-aws/blob/c6dd022200fde668476f5aee247f2383d8d54bf2/main/solution/machine-images/config/infra/provisioners/provision-hail.sh#L51). 

Work-around: If you'd like to update the password to something else, you'd need to get the SHA encrypted hash for the new password value, replace it on the file mentioned above, and create a new AMI for EMR.

Hope this helps.

**Comment by srpiatt** [comment]
Thank you for the work around. Are there any plans to make these log-in credentials more flexible or dynamic, in the future?

**Comment by nguyen102** [comment]
Hi @srpiatt ,

This is not currently on our roadmap. However, we'll make note of this feature request.

**Comment by srpiatt** [comment]
@nguyen102 Our team was wondering if this feature request has been considered for the roadmap? :) We are still unable to use this kind of workspace in our more secured environments.
