### ISSUE TITLE
[Bug] environment_delete.sh script not emptying EgressStoreBucket

### ISSUE THREAD

**Issue by dcloud9** [awslabs/service-workbench-on-aws#983]
**Describe the bug**
Out use case is to enable Egress Store.
Running ./scripts/environment_delete.sh empties successfully some buckets but not the EgressStoreBucket.
Though all buckets are `versioned`, including the EgressStoreBucket, the script errors with 
```
The bucket you tried to delete is not empty. You must delete all versions in the bucket. 
```
Seems, that is not included in the default [list](https://github.com/awslabs/service-workbench-on-aws/blob/mainline/scripts/environment-delete.sh#L323).

**To Reproduce**
1. Enable `enableEgressStore: true` in `settings.yml` -> deploy SWB -> Launch some Workspaces -> Egress some reports/data to populate S3 EgressStore buckets - **this is important to reproduce!**. 
1. Login to SWB builder that built the stack
1. Run `./scripts/environment_delete.sh <stageName>`

**Expected behavior**
All buckets emptied first before being deleted successfully.

**Screenshots**
```
--- Backend stack
- Emptying bucket <redacted>-studydata ...  Done !
- Emptying bucket <redacted>-external-templates ...  Done !
- Emptying bucket <redacted>-env-type-configs ...  Done !
- Emptying bucket <redacted>-environments-bootstrap-scripts ...  Done !
- Removing Stack Backend ...
S3 Sync: Removing S3 objects...
.
S3 Sync: Removed.
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking Stack removal progress...
............................................................................................
Serverless: Operation failed!
Serverless: View the full error output: https://eu-west-2.console.aws.amazon.com/cloudformation/home?region=eu-west-2#/stack/detail?stackId=<redacted>

  Serverless Error ---------------------------------------

  An error occurred: EgressStoreBucket - The bucket you tried to delete is not empty. You must delete all versions in the bucket. (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; Request ID: 5SW<redacted>; S3 Extended Request ID: 6c7Syp<redacted>; Proxy: null).
```
**Versions (please complete the following information):**
 - `v4.1.1`

**Additional context**

**Comment by SanketD92** [comment]
Thank you for reporting this issue. We've created a ticket in our backlog.
