### ISSUE TITLE
[Bug] environment_delete.sh script running over 2 hours to empty Logging bucket

### ISSUE THREAD

**Issue by dcloud9** [awslabs/service-workbench-on-aws#987]
**Describe the bug**
Running ./scripts/environment_delete.sh is taking over 2 hours to empty `-logging` bucket, and that's only 2k+ over 5k+ files, so could take over 4hrs to completely empty so I terminated the script.
Emptying the same bucket in AWS console takes **2 sec**

**To Reproduce**
1. Login to SWB builder that built the stack
1. Run ./scripts/environment_delete.sh <stageName>

**Expected behavior**
If emptying bucket programmatically, that has the same effect of rapid emptying using AWS console, is not possible, then might as well remove this slow bit of code and rather create a how-to guide to empty the buckets using the console before running this script.

**Screenshots**
```
--- Infrastructure stack
- Emptying bucket <redacted>-website ...  Done !
- Emptying bucket <redacted>-logging ...  Done ! #this bit is where seems the script is looping the bucket per file to delete, hence extremely slow.
- Removing Stack Infrastructure ...
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking Stack removal progress...
...............
Serverless: Stack removal finished...
```
**Versions (please complete the following information):**
 - Release Version installed `5.1.1`

**Additional context**

**Comment by ssvegaraju** [comment]
Hi @dcloud9, thanks for bringing this up! I've added this to our team's backlog.
