### ISSUE TITLE
[Bug] environment_delete.sh script should delete SSM param for native admin password

### ISSUE THREAD

**Issue by dcloud9** [awslabs/service-workbench-on-aws#988]
**Describe the bug**
Running `./scripts/environment_delete.sh` does not delete SSM param for `*/usr/native/admin/password`.
If redeployed again using `./environment_deploy.sh`, the postDeployment stack doesn't update the param with new password value, therefore login denied.

**To Reproduce**
1. Login to SWB builder that built the stack
2. Run ./scripts/environment_delete.sh
3. Run /scripts/environment_deploy.sh
4. Login to SWB URL using the `rootUserEmail` account

**Expected behavior**
I expect to user the SSM param value and successfully login.

**Screenshots**
```
---- SSM Parameters
Deleting param /<redacted>/jwt/secret
Deleting param /<redacted>/user/root/password
**Deleting param /<redacted>/user/native/admin/password #this should be removed as well for SWB >= v4.2.0**

--- Edge Lambda Associations in Cloudfront Distribution


*******************************************************************
*****     ----- ENVIRONMENT DELETED SUCCESSFULLY  🎉!! -----     *****
*******************************************************************
You still have to remove the following elements :
  -[Edge lambda]: It can be deleted manually in 1 hour,
     Navigate here on the main account:
       https://console.aws.amazon.com/lambda
  -[Consumer Accounts]: The stacks and resources deployed on your
     hosting accounts are not deleted as part of this script
     Navigate here on those accounts:
       https://console.aws.amazon.com/ec2/v2/home,
       https://console.aws.amazon.com/sagemaker/home
       https://console.aws.amazon.com/cloudformation
```
**Versions (please complete the following information):**
 - Release Version installed `4.2.0` to `5.1.1`

**Additional context**

**Comment by ssvegaraju** [comment]
Thanks for catching this @dcloud9, I've added this to the team's backlog!

**Comment by tdmalone** [comment]
In the meantime a potential workaround for this situation is to manually reset the password with eg.:
```
aws cognito-idp admin-set-user-password --user-pool-id region-name_XXXXXXXXX --username root@example.com --password 'CHOOSE_A_UNIQUE_TEMPORARY_PASSWORD'
```

**Comment by tdmalone** [comment]
Adding response so this doesn't get closed

**Comment by t-young31** [comment]
I've also just hit this – a fix would be much appreciated! Thanks 😄
