### ISSUE TITLE
[Bug] Deployment failures due to incompatible pnpm version

### ISSUE THREAD

**Issue by nguforw** [awslabs/service-workbench-on-aws#995]
**Describe the bug**
The current install guide asks the user to install pnpm. The command, as written, will install the latest version of pnpm (currently v7.0). However this leads to failures at the build stage due to "unmet peer dependencies". 

**To Reproduce**
1. Run 'npm install -g pnpm' together with all the other standard environment preparation steps
2. Run the 'environment-deploy.sh' script

**Expected behavior**
Service Workbench should deploy successfully with the latest version of pnpm. Alternatively, update the documentation and guide the user to pin to a known working version of pnpm.

**Versions (please complete the following information):**
 - Release Version installed [v5.1.1]

**Additional context**
Currently the workaround is to pin to an older version of pnpm. v5.18.9 is known to work. Obviously pinning to an old version has its downside as these may have security vulnerabilities that have been patched in later versions.

**Comment by manics** [comment]
There was a breaking change in pnpm: https://github.com/pnpm/pnpm/issues/4684

**Comment by Bingjiling** [comment]
Hi @nguforw,

Thanks for reaching out! I'll create a ticket in our backlog to specify the version of pnpm in the documentation. 

Thanks,
Yanyu

**Comment by tdmalone** [comment]
Experiencing the same issue here - thanks @nguforw for mentioning the known-working older version.

@Bingjiling Is `pnpm` necessary in this project? I imagine it would make things a little easier, with one less dependency to manage these sorts of issues for, if `npm` was just used instead?

**Comment by nguyen102** [comment]
Yep, pnpm is necessary to handle package management. The installation instruction was updated in this PR to address this issue.
